### ISSUE TITLE
Add `assert_json_eq!` macro to simplify common use case

### ISSUE THREAD

**Issue by nyurik** [serde-rs/json#1006]
In many cases, especially unit tests, it is required to compare two arbitrary json blobs - very often as strings, e.g. this:

```rust
#[test]
fn test_lib_output() {
  let json_result = my_lib.get_json_result();
  assert_eq!(r#"{"expected": 42, "result": 13}"#, json_result.to_string());
}
```

Sadly, this is not going to work because of two reasons:
* the expected result must be perfectly identical to the jsonified result (spacing, newlines, utf-8 normalization/escaping, etc)
* the order of the json keys must be identical

I think we all could benefit from a simple assertion macro, something like this (untested):

```rust
macro_rules! assert_json_eq {
    ($left:expr, $right:expr $(, $arg:tt)* $(,)?) => {
        let left = serde_json::from_str::<serde_json::Value>($left).unwrap();
        let right = serde_json::from_str::<serde_json::Value>($right).unwrap();
        assert_eq!(left, right ($($arg)+));
    };
}
```

**Comment by dtolnay** [comment]
Thanks for the suggestion! I think I would prefer not to build this into serde_json though.
