### ISSUE TITLE
Allow simpler `json!` macro usage without extra brackets / parenthesis

### ISSUE THREAD

**Issue by nyurik** [serde-rs/json#1009]
I would like `json!` macro to understand simpler usage without an extra pair of parenthesis:

```rust
json! {
    "type": "Point",
    "coordinates": [25, 17]
}

json![1, 2, 3]
```

instead of the `json!({ ...})` form.  This would only work for non-empty usage.

### Pros
* more consise and readable json creation for objects and arrays

### Cons
* syntax for empty arrays/objects would still require an extra parens.
* it is possible to misuse it, e.g.  `json! { 1, 2, 3 }`

**Comment by dtolnay** [comment]
I think I prefer the current way and would prefer not to support this.
