### ISSUE TITLE
timeout reporting changed in serde-json 1.0.94 

### ISSUE THREAD

**Issue by plugwash** [serde-rs/json#1012]
It seems the reporting of timeouts changed in serde-json 1.0.94 and that this broke the tests of the ureq crate.

    git clone https://github.com/algesten/ureq/
    cd ureq
    git checkout 2.6.2
    cargo test --lib --all-features

    ---- test::timeout::overall_timeout_reading_json stdout ----
    thread 'test::timeout::overall_timeout_reading_json' panicked at 'expected timeout but got something else: "Unexpected io::ErrorKind: Custom { kind: InvalidData, error: \"Failed to read JSON: timed out reading response at line 6 column 1\" }"', src/test/timeout.rs:175:6
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
    
    failures:
        test::timeout::overall_timeout_reading_json
    
    test result: FAILED. 134 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.41s

With serde-json 1.0.93 the tests pass, with serde-json 1.0.94 and newer they fail. As a quick fix ureq upstream has set an upper limit on the version of serde-json but that isn't a good long term soloution, nor is it an acceptable soloution for distros like Debian.

**Comment by dtolnay** [comment]
Serde_json does not implement anything relating to timeout so I am not sure what this is referring to.

**Comment by dtolnay** [comment]
I see what changed &mdash; ureq was expecting to do `serde_json_error.source().unwrap().downcast_ref::<std::io::Error>().unwrap().kind()` to get the same ErrorKind that serde_json obtained from the std::io::Read argument to `from_reader`.

In order for that to work, error messages would necessarily end up getting duplicated (either in the caller, or in serde_json). Either

```console
Error: failed to read JSON

Caused by:
  timed out waiting on channel at line 6 column 1

Caused by:
  timed out waiting on channel
```

or:

```console
Error: failed to read JSON

Caused by:
  failed to read JSON bytes from io::Read at line 6 column 1

Caused by:
  timed out waiting on channel
```

Possibly we could expose a `pub fn io_error_kind(&self) -> Option<ErrorKind>` on serde_json::Error instead to avoid errors being redundant like this.

**Comment by plugwash** [comment]
> Possibly we could expose a pub fn io_error_kind(&self) -> Option<ErrorKind> on serde_json::Error instead to avoid errors being redundant like this.

That does sound like a reasonable soloution to me.
