### ISSUE TITLE
Serializing f64 with arbitrary significant figures.

### ISSUE THREAD

**Issue by junderw** [serde-rs/json#1041]
I did a search and found a lot of issues and features surrounding f64 -> JSON -> f64 and JSON -> Number -> JSON etc.

However, I am looking for something that can specify the sig figs for the JSON output when serializing with serde_json.

ie. for C++ you can set the `precision` parameter of the cout steam https://en.cppreference.com/w/cpp/io/manip/setprecision to get it to print out an arbitrary precision of sig figs.

My question:

Is there a way to get this behavior with serde_json? Is there a workaround I can do without needing something implemented on the serde_json end?

I am trying to get float numbers to match a C++ program which is outputting a JSON via setprecision 16 and Rust is sometimes outputting JSON numbers which are in line with setprecision 17.

**Comment by dtolnay** [comment]
You can plug in your own float renderer.

```rust
use serde::Serialize;
use serde_json::json;
use std::io;

struct JunderwFormatter;

impl serde_json::ser::Formatter for JunderwFormatter {
    fn write_f64<W>(&mut self, writer: &mut W, value: f64) -> io::Result<()>
    where
        W: ?Sized + io::Write,
    {
        write!(writer, "{:.15E}", value)
    }
}

fn main() -> serde_json::Result<()> {
    let thing = json!({ "float": std::f64::consts::E });
    let out = io::stdout();
    let mut ser = serde_json::Serializer::with_formatter(out, JunderwFormatter);
    thing.serialize(&mut ser)?;
    Ok(())
}
```

**Comment by junderw** [comment]
Is there a way to isolate this behavior to a specific type?

ie. I create a wrapper type, derive Deserialize using skip and flatten etc. But somehow manually implement Serialize with a custom formatter.

Thanks for your answer, though. I will close the issue since I've gotten a good enough clue as to where to look at.

But if you could answer my follow up question when you get the chance I'd appreciate it.
