### ISSUE TITLE
How to deserialize a string to an enum that's either a unit variant or a tuple "other" variant ?

### ISSUE THREAD

**Issue by gagbo** [serde-rs/json#1044]
Hello,

I'm basically trying to find a way to make [this playground work](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8a7c171baacf35f2205ad45d6c409681):

```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum UnitOrTuple {
    User,
    // Anything that's not exactly "user"
    DeployKey(String)
}

fn main() {
    let user = UnitOrTuple::User;
    let deploy_key = UnitOrTuple::DeployKey("a long string".to_string());
    assert_eq!(serde_json::from_str::<UnitOrTuple>(r#""user""#).unwrap(), user);
    assert_eq!(serde_json::from_str::<UnitOrTuple>(r#""a long string""#).unwrap(), deploy_key);
}
```

I would like to be able to match exactly known-in-advance strings while having a catch-all value that's a tuple variant of an enum to read the value if possible. Is there a way to do it? When I tried to use `untagged` on the enum, the `User` variant basically disappears and we cannot pass the first test. In the version above, it fails the second test.

**Comment by jonasbb** [comment]
You can use `untagged` on individual enum variants like:

```rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum UnitOrTuple {
    User,
    // Anything that's not exactly "user"
    #[serde(untagged)]
    DeployKey(String),
}
```

**Comment by gagbo** [comment]
Thanks a lot, don't know why I didn't try that!

**Comment by gagbo** [comment]
For the record, I think the reason I didn't try it was that the serde.rs page does not talk about it in the ["Variant attributes"](https://serde.rs/variant-attrs.html) page (nor the "Field attributes" one). It might be worth it to add a section about it on the website.
