### ISSUE TITLE
json string with `0` on prefix of numbers are not considered a valid JSON by `serde_json::from_string`

### ISSUE THREAD

**Issue by KunalSin9h** [serde-rs/json#1050]
For example see this output:

![image](https://github.com/serde-rs/json/assets/82411321/35811297-b675-4516-8549-eaf3bf20b5c5)

Here the nums array have **01** as 2nd element which makes the string invalid for JSON conversion, i am paring the string with help code i have written [livejq](https://github.com/KunalSin9h/livejq/blob/669006db3f1ee305fc188c0261a7c403e45d9fc2/src/main.rs#L15) which is using `serde_json::from_string` to convert the string to JSON.

```rust
if let Ok(parsed_json) = serde_json::from_str::<Value>(&input) {
    // Token is a valid JSON
    // recursively print the JSON values 
    print_json(parsed_json, true, 0);
} else {
    // Token is not a valid JSON 
    // So just print it
    println!("{}", input);
}
```

I think the desired result would be ignoring the **0** in the prefix of number.

**Comment by dtolnay** [comment]
I think this is correct behavior according to the specification of JSON.
