### ISSUE TITLE
Cannot compile serde_json to Web Assembly with target-feature=+multivalue

### ISSUE THREAD

**Issue by eastside** [serde-rs/json#1052]
The issue is that if you use serde_json and you're trying to compile to Web Assembly with multi-value returns turned on, a strange compilation error results.

I've made a [minimum reproducible here](https://github.com/eastside/minirepro-libserde-multivalue-return) which includes a complete description of the error.

Here's a rust-lang/rust thread on [multivalue support](https://github.com/rust-lang/rust/issues/73755#issuecomment-1670292554) that may prove useful. I'm not entirely sure if this is an issue more for Rust core, or if it's a serde_json issue (or a little of both?).

**Comment by dtolnay** [comment]
I don't know much about WebAssembly, but I am skeptical that this is a serde_json issue.
