### ISSUE TITLE
can `Number` decode into `int64` with rounding?

### ISSUE THREAD

**Issue by keepsimple1** [serde-rs/json#1060]
https://github.com/serde-rs/json/blob/0daacdd52e4abb4a47a7f7fc598c5bd4492aa104/src/number.rs#L181-L185

Is there a way in `serde_json` to decode a double (e.g. "256.0") into integer (e.g. 256) ? 

I wanted to use a single API / approach to handle both "256" and "256.0",  and also wanted to ideally convert "256.5" into 256, i.e. with rounding. 

The API seems like be strict with float and int64.  For example, calling `is_f64()` on the number "64" return false.

**Comment by dtolnay** [comment]
You would need to write something like:

```rust
if let Some(int) = value.as_i64() {
    Some(int)
} else if let Some(float) = value.as_f64() {
    if i64::MIN as f64 <= float && float <= i64::MAX as f64 {
        Some(float as i64)
    } else {
        None
    }
} else {
    None
}
```

**Comment by keepsimple1** [comment]
Thanks!
