### ISSUE TITLE
It would be great if `Number` had an `as_str` method if `"arbitrary_precision"` is enabled.

### ISSUE THREAD

**Issue by chanced** [serde-rs/json#1066]
Would you be open to a pull request that added an `as_str` method to `Number` if `"arbitrary_precision"` is enabled?

**Comment by dtolnay** [comment]
I agree &mdash; seems good to me. Please send a PR.

**Comment by chanced** [comment]
Awesome, on the way!

By the way, thanks for the awesome work... on all of your crates.
