### ISSUE TITLE
Option<Option<T>> does not roundtrip correctly

### ISSUE THREAD

**Issue by mousetail** [serde-rs/json#1096]
```rs
use serde::{Serialize, Deserialize}; // 1.0.193
use serde_json; // 1.0.108

fn main() {
    let single_none: Option<Option<u32>> = Some(None);

    let serialized = serde_json::to_string(&single_none).unwrap();
    let deserialized: Option<Option<u32>> = serde_json::from_str(&serialized).unwrap();
    assert_eq!(deserialized, single_none);
}
```

[Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7019e26df7d227daec6df136116f2b58)

Both `Some(None)` and `None` serialize to `"null"`, so it can't tell which one was intended.

## Potential solutions

* Serialize nested options more like normal results `{"Some": x} | null`
* Disallow de-serializing `Option<Option<T>>`
* Find some other non-ambiguous representation

I've not been able to find if other serde formats have the same problem, since the rust playground doesn't have them, so I'm not sure if it's a serde or or a serde-json issue.

## Relevant code

https://github.com/serde-rs/json/blob/c3670913423329c166add9d85ecdfc3e3da21e7a/src/ser.rs#L272-L277

**Comment by dtolnay** [comment]
Both of these are the intended behavior: that `Option::None` is represented by `null` in JSON, and that `Option::Some` serializes in the same representation as the contained value. Roundtripping arbitrary data is not a goal for serde_json.
