### ISSUE TITLE
json serialization compatible problem

### ISSUE THREAD

**Issue by kwsc98** [serde-rs/json#1121]
For example, in java interactions, fields of type String are serialized directly to sds instead of /"sds/", and using serde results in an error when serialization fails
expected value at line 1 column 1
Hopefully this is compatible

**Comment by TinusgragLin** [comment]
Can not reproduce this on my end. Using the latest version of `serde` and `serde_json` and this simple test code:
```rust
use serde::{Deserialize, Serialize};
#[derive(Serialize, Deserialize)]
struct Test {
    sds: String
}
fn main() {
    let test = Test { sds: "sds".to_string() };
    let res = serde_json::to_string(&test).unwrap();
    println!("{}", res);
}
```
yields:
```
{"sds":"sds"}
```
as expected, please provide more information and perhaps an simple example illustrating your issue.

**Comment by kwsc98** [comment]
like 
```rust
    let str = "sds";
    let str_json = serde_json::to_string(str).unwrap();
    println!("{:?}", str_json); //   "\"sds\""
    let res: Result<String, serde_json::Error> = serde_json::from_str(str);
    println!("{:?}", res); //  Err(Error("expected value", line: 1, column: 1))
```

**Comment by TinusgragLin** [comment]
`serde_json::from_str()`  deserialize a structure from a **json string**. I don't think
```
sds
```
is a valid json string.

**Comment by TinusgragLin** [comment]
Maybe you have confused the variable `str` with `str_json`?

**Comment by TinusgragLin** [comment]
Oh, I guess you have confused "the string type in json (as well as in javascript)" with "a string that is in the json format", am I right?

**Comment by kwsc98** [comment]
I have a project that communicates with Java projects, and in some Java json parsing libraries, the String type is treated directly as
`sds`
Instead of
`\"sds\"`
so
```
let res: Result<String, serde_json::Error> = serde_json::from_str("sds");
println!("{:?}", res); //  Err(Error("expected value", line: 1, column: 1))

let res: Result<String, serde_json::Error> = serde_json::from_str("\"sds\"");
println!("{:?}", res); //  Ok("sds")
```
Now I receive a Java response that I must process before I can use serde_json
like 
```
pub fn json_field_compatible(ty: &str, mut field: String) -> String {
    if ty == "String" && !field.starts_with("\"") {
        field.insert(0, '\"');
        field.insert(field.len(), '\"');
    }
    field
}
```

**Comment by TinusgragLin** [comment]
> ... the String type treated directly as `sds` instead of `"sds"`

Such implementation would be incompatible with the JSON format specification, as both  [RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259#section-7) and [ECMA-404](https://ecma-international.org/publications-and-standards/standards/ecma-404/) define `string` as:
```
'"' characters '"'
```
Here is a simple [JSON format verifier](https://jsonformatter.curiousconcept.com/#) if you don't want to look into the specs (remember to **uncheck the `Fix JSON` option** as this will enable **auto-correction**).

**Comment by kwsc98** [comment]
i know  , so i hope have like a "Fix JSON" Feature,

**Comment by TinusgragLin** [comment]
In that case, you probably should change your title to "Feature request: apply simple auto-corrections when deserialize", though I don't think that would be accepted.

**Comment by dtolnay** [comment]
Deserializing things other than JSON is out of scope for this library.
