### ISSUE TITLE
[Bug] Fails to parse root string array

### ISSUE THREAD

**Issue by tymur999** [serde-rs/json#1139]
It can parse a root array of objects but not a root array of strings.

```rs 
let val : Vec<String> = serde_json::from_str("['hello','two']").unwrap();
```

Expects a value after key 'hello' (but this is not a key, it is a string array)

**Comment by tymur999** [comment]
ChatGPT recommends this alternative:
```rs
    let deserialized: Value = serde_json::from_str(json_str).unwrap();

    // Convert the serde_json::Value into a vector of strings
    if let Value::Array(array) = deserialized {
        let string_array: Vec<String> = array.into_iter()
            .filter_map(|v| v.as_str().map(|s| s.to_string()))
            .collect();

        // Print the vector of strings
        println!("{:?}", string_array);
    }
}
```
But as you can see, this is very unwieldy

**Comment by dtolnay** [comment]
`['hello','two']` is not valid JSON.

**Comment by tymur999** [comment]
Originally this was stored in an env variable as ["hello","two"] which was for some reason parsed as [hello, two] which explains the err.

When I escape the " as \", it parses fine.
