### ISSUE TITLE
Adding the spreadsheet operator as part of the `json` macro

### ISSUE THREAD

**Issue by cook-f** [serde-rs/json#1158]
In some cases it could be useful to have the spread operator available in the `json` macro. E.g.

```
let x = my_struct {
    a: 10,
    b: 15,
    c: "foo"
}

let json_return = json!(
    "type": "my_struct",
    ...my_struct
)
```

Doesn't make anything impossible possible but just makes things more convenient in some ways

**Comment by dtolnay** [comment]
I would prefer not to support this in this crate. But there may be other libraries providing more fully-featured json construction macros.
