### ISSUE TITLE
Force Serde JSON to not use preserve order feature

### ISSUE THREAD

**Issue by chrisbll971** [serde-rs/json#1162]
Hello,

It looks like a third-party dependency crate we are using enabled the "preserve_order" feature for serde_json and this is causing all packages in my workspace to use this feature as well. Do you know if there any options to get around this? Is there is a way to force a "Value" to use a BTreeMap or somehow disable this feature for just my crate? I've tried a lot of options with no success.

Thanks

**Comment by tvsfx** [comment]
I've run into the same issue; we have many workspace members that don't care about ordering, and a few that do. It would be useful to still expose a variant of the `Value` type that does not preserve ordering for (de)serialization in case the `preserve_order` feature is activated, or expose the opposite type when `preserve_order` is not active.
To keep this backwards compatible, I was imagining something like the following, using a new feature `expose_other_value` (throwaway name) to have the user specify that they want to expose both types of value:

```rust
// Move `impl Map<String, Value>` block into trait
trait JsonMap: Serialize + Deserialize + IntoIterator + ... {
  clear(...);
  get(...);
  contains_key(...);
  get_mut(...);
}

/// More general version of current `Value` that is agnostic over how it is sorted, using a generic `JsonMap` interface
enum GenValue<M: JsonMap> {
  ...
  Object(M)  
  ...
}

// Instantiate `JsonMap` in one or two different ways, depending on active features
#[cfg(any(not(feature="preserve_order"), feature="expose_other_value"))]
struct JsonBtreeMap(BTreeMap<String, GenValue<JsonBtreeMap>>);
#[cfg(any(feature="preserve_order", feature="expose_other_value"))]
struct JsonIndexMap(IndexMap<String, GenValue<JsonIndexMap>>);

#[cfg(any(not(feature="preserve_order"), feature="expose_other_value"))]
impl JsonMap for JsonBtreeMap {
  ...
}

#[cfg(any(feature="preserve_order", feature="expose_other_value")]
impl JsonMap for JsonIndexMap {
  ...
}

// Expose the active value types
#[cfg(any(not(feature="preserve_order"), feature="expose_other_value"))]
pub type OrderedValue = GenValue<IndexMap<String,Value>>;
#[cfg(any(not(feature="preserve_order"), feature="expose_other_value"))]
pub type OrderlessValue = GenValue<IndexMap>;

// Backwards compatibility: expose the old value type
#[cfg(not(feature = "preserve_order"))]
pub type Value = GenValue<BTreeMap>;
#[cfg(feature = "preserve_order")]
pub type Value = GenValue<IndexMap>;
```
I could implement this if the maintainers deem it useful.

I guess a workaround for now is to duplicate the `Value` type in your own code and manually tweak it to use the right map, but this requires duplication of quite a bit of code ((de)serialize implementation, `json!` macro, etc.)

**Comment by dtolnay** [comment]
The recommended approach is that the few places which desire a guaranteed sorted order should call [`.sort_all_objects()`](https://docs.rs/serde_json/1/serde_json/value/enum.Value.html#method.sort_all_objects). For example, right before writing a particular JSON value to disk that has to be sorted. This will only perform any work if something in the dependency graph has enabled "preserve_order". Otherwise it will do nothing.

Alternatively there may be crates that provide an always-sorted Value type that you could use for dealing with such data.
