### ISSUE TITLE
Deserializing 2^53-1 or -(2^53-1) into an `f64` loses precision

### ISSUE THREAD

**Issue by linabutler** [serde-rs/json#1170]
Hi! 👋🏻 I noticed that `serde_json::from_str` seems to lose precision when deserializing the smallest and largest integers that can fit into the mantissa an `f64`. [This Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f67150547cfe57ea335dc181d4ea0836) prints:

```
min_string = "-9007199254740991.0"; max_string = "9007199254740991.0"
min_value = -9007199254740990.0; max_value = 9007199254740990.0
```

...But I think the correct output would be:

```
min_string = "-9007199254740991.0"; max_string = "9007199254740991.0"
min_value = -9007199254740991.0; max_value = 9007199254740991.0
```

Enabling the `"arbitrary_precision"` feature fixes this—though it's a little dicey to do that in our project, because we're using `serde_json` as a workspace dependency 😬—as does serializing and then deserializing those numbers as `i64`s instead of `f64`s.

Thanks!

**Comment by Skgland** [comment]
`-8.990567403888024e-203` as well, found while writing a proptest for roundtripping values through json.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f87d95e51c7b645922193c5bda08afba)

**Comment by linabutler** [comment]
I'm a little embarrassed that I completely missed `float_roundtrip`. Its comment suggests that `serde_json`'s less precise but much faster default behavior is intentional:

> This comes at an approximately 2x performance cost for parsing floats compared to the default best-effort precision.

...So I'll go ahead and close this out. Thank you so much, @0f-0b!

**Comment by V0ldek** [comment]
@dtolnay  Could we get specific documentation on the behaviour without this feature? In my case a fuzz test found this value to get deserialized differently:
```
4.05831638439668e266
```

It has exactly 15 significant digits, so according to `binary64` it should not lose precision. Is there a specific limit of precision for the algorithm when `float_roundtrip` is disabled? Are there any guarantees for the "best-effort precision" as stated in the feature's comment?
