### ISSUE TITLE
deserialize from jsons that do not follow conventions(no " or ' instead of ")

### ISSUE THREAD

**Issue by frederik-uni** [serde-rs/json#1181]
Some jsons do not use "" for key & value. Ive seen some jsons that don't use any quotation marks for keys/or only when needed & ' instead of ".

I don't know what the best way for deserializing this would be. maybe something like this.
```
#[serde_json(key_qm = "'")]
#[serde_json(key_qm = "")]
#[serde_json(value_qm = "'")]
```
or 
```
serde_json::from_str_opt(s, opt)
```

**Comment by dtolnay** [comment]
I would prefer not to support formats other than JSON in this crate.
