### ISSUE TITLE
Support JSON without objects and support JSON without objects or arrays

### ISSUE THREAD

**Issue by SamuelMarks** [serde-rs/json#1189]
Technically that's not JSON.

I hacked around your codebase to implement it here - https://github.com/SamuelMarks/serde-json-extensions

Would you be amenable to PRs to make more of your API `pub`lic so I don't need to steal *ahem* copy so much of your codebase into mine; and can just depend on it?

I can imagine people creating relaxed supersets of JSON (e.g., to allow trailing commas and comments like [JSON5](https://json5.org/)), and more restricted subsets of JSON (like mine).

Thanks for creating a great library!

**Comment by dtolnay** [comment]
Copying the code is all right. Someone could even make a crate expressly for the purpose of facilitating JSON superset and JSON subset crates. But I would prefer not to expose serde_json internals for this purpose.
