### ISSUE TITLE
How do I customize the serialization and deserialization to custom json format?

### ISSUE THREAD

**Issue by leonardoraele** [serde-rs/json#1191]
I want to customize the JSON representation of my struct.

For example, given a `Color` struct...
```rust
pub struct Color {
	pub r: u8,
	pub g: u8,
	pub b: u8,
	pub a: u8,
}
```

...with methods to convert to and from hexadecimal...

```rust
impl Color {
	pub fn from_hex(hex: &str) -> Self {
		// ...
	}

	pub fn to_hex(&self) -> String {
		// ...
	}
}
```

...I want `Color` to be serialized to and from a string, using those hexadecimal methods.

```rust
struct ColoredObject {
	color: Color,
}

assert_eq!(
	serde_json::to_string(
		ColoredObject {
			color: Color { r: 255, g: 0, b: 0, a: 0 },
		}
	),
	"{\"color\":\"#FF000000\"}"
);
```

How do I do that?

**Comment by dtolnay** [comment]
Hi @leonardoraele, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.
