### ISSUE TITLE
bug: from_value fails to parse enum whereas from_str does not

### ISSUE THREAD

**Issue by JosiahParry** [serde-rs/json#1193]
I'm encountering an issue where serde_json cannot deserialize an untagged enum from a `Value` but it _can_ for a string. 

Playground below: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d9e924ca9756538e0ad886f8bc3fa04c

`from_str()` returns `Ok` whereas `from_value()` returns an error

**Comment by dtolnay** [comment]
This is working correctly as far as I can tell. `serde_json::Value::from(json)` is a JSON string containing JSON, whereas `serde_json::from_value::<Settings>` would require the input to be a JSON map (not a string).
