### ISSUE TITLE
expected identifier, found reserved identifier

### ISSUE THREAD

**Issue by learnwithsobhit** [serde-rs/json#1198]
I am getting this error in serde_json with latest version v1.0.128 , also other dependency crate while using , any clue whats the issue 

 use crate::_::_serde::de::Error;
  |            ^ expected identifier, found reserved identifier

**Comment by dtolnay** [comment]
That code does not appear in serde_json, serde, or any code generated by serde's derive macros. So your issue is somewhere else.
