### ISSUE TITLE
Value::as_u64, as_i64 docs inconsistent with Value::is_number

### ISSUE THREAD

**Issue by Ryanl92** [serde-rs/json#133]
There seems to be a small difference in the documentation of `Value` where [`Value::is_number()`](https://github.com/serde-rs/json/blob/dd864cb98438976283dd710d9653d183ebc4457c/json/src/value.rs#L281) considers f64 to be a number and will return `true` for a F64 variant, whereas [`Value::as_i64()`](https://github.com/serde-rs/json/blob/dd864cb98438976283dd710d9653d183ebc4457c/json/src/value.rs#L312) and [`Value::as_u64()`](https://github.com/serde-rs/json/blob/dd864cb98438976283dd710d9653d183ebc4457c/json/src/value.rs#L322) don't and return `None` for the F64 variant.
I would guess that this is because the f64 -> i/u64 downcast loses precision so was left out. If so I can update the docs to clarify which conversions will automatically happen, as currently the docs for these two conversions suggest that any number will be cast.

[`Value::as_f64()`](https://github.com/serde-rs/json/blob/dd864cb98438976283dd710d9653d183ebc4457c/json/src/value.rs#L332) Will cast any number type as the docs suggest.

**Comment by dtolnay** [comment]
I clarified this with examples in 95ac90522101556a64e553bbdee8321a5d485565.
