### ISSUE TITLE
Sample serialize/deserialize implementation

### ISSUE THREAD

**Issue by luxvio** [serde-rs/json#14]
Hi !
I've been looking on the internets how to implement my own serialize/deserialize on a type (particularly on the crate time, for TimeSpec or Tm), so I can seamlessly parse a date to a json string (using strftime) ... but I couldn't find a simplified example on how to implement that on a type and how.

¿Is there any place to look for such information?

Thanks for reading and  for making serde !  ♥

**Comment by erickt** [comment]
The best doc is the [README.md](https://github.com/serde-rs/serde/blob/master/README.md), which your issue has inspired me to make some improvements to it. I'll try to land it tonight.

The simplest way to get serde support would be to use macros. Here are the [stable rust doc](https://github.com/serde-rs/serde#using-serde-with-stable-rust-syntex-and-serde_codegen) and the [nightly rust doc](https://github.com/serde-rs/serde#using-serde-with-nightly-rust-and-serde_macros).

Let me know if that helps!

**Comment by luxvio** [comment]
Yes, it helps !
I'll give it a shot tomorrow, but the generals solves most doubts.

Ty :D

**Comment by luxvio** [comment]
Got it ! :smile: 
Here's how I managed to solve this → https://users.rust-lang.org/t/time-serde-json/3346

Thank you !
