### ISSUE TITLE
Custom errors should not introduce useless `at line 0 column 0` into fmt::Display output

### ISSUE THREAD

**Issue by jnicklas** [serde-rs/json#147]
The [serde::ser::Error](https://docs.rs/serde/0.8.4/serde/ser/trait.Error.html) trait's `custom` methods is meant to be used by serializers in case they encounter an unforeseen error during serialization. serde_json currently implements this like this:

``` rust
impl ser::Error for Error {
    /// Raised when there is general error when deserializing a type.
    fn custom<T: Into<String>>(msg: T) -> Error {
        Error::Syntax(ErrorCode::Custom(msg.into()), 0, 0)
    }
}
```

Note that line and column are _always_ `0` here. `serde_json::Error` then has the following `fmt::Display` implementation:

``` rust
impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Error::Syntax(ref code, line, col) => {
                write!(fmt, "{} at line {} column {}", code, line, col)
            }
            Error::Io(ref error) => fmt::Display::fmt(error, fmt),
        }
    }
}
```

This results in an error message like this:

> MissingType: missing type NoSuchFields at line 0 column 0

Not only is the `at line 0 column 0` part useless, it is also plain wrong, since the error did not in fact occur at that line and column.

IMO it would make sense to move `Custom` out of `ErrorCode` and make it a variant of `Error` instead, without any line and column information at all.

**Comment by dtolnay** [comment]
I removed "at line 0 column 0" in #206.
