### ISSUE TITLE
Feature `preserve_order` is not additive 

### ISSUE THREAD

**Issue by bluss** [serde-rs/json#152]
Cargo unions all features that all rdeps in a project of a crate want, and compiles the crate with that. This requires features to be additive. Since this feature changes the types used in the public API of the crate, it is not.

**Comment by dtolnay** [comment]
We can avoid affecting types in the public API by replacing `serde_json::value::Map` (which is currently either `BTreeMap` or `LinkedHashMap`) with an opaque newtype wrapper around `BTreeMap` or `LinkedHashMap`. @oli-obk do you see a better approach?
