### ISSUE TITLE
Consider making ser::MapKeySerializer public

### ISSUE THREAD

**Issue by traviskaufman** [serde-rs/json#154]
I've been working on a serialization library for [bencode](https://wiki.theory.org/BitTorrentSpecification#Bencoding) in rust using serde, borrowing heavily from json's [ser.rs](https://github.com/serde-rs/json/blob/master/json/src/ser.rs). For bencoded maps, I essentially have to copy pretty much the exact same functionality over from `MapKeySerializer`.

I was wondering if the team would consider publicly exposing `MapKeySerializer` so that other serialization formats that need similar functionality could use it? If it would be too weird to have a sibling-level dependency from one serialization library to another, would you consider refactoring MapKeySerializer into `serde` proper, or its own standalone helper library? Thanks!

**Comment by dtolnay** [comment]
I think this belongs in a standalone helper library. Nothing in serde requires that map keys are strings, so the behavior in MapKeySerializer is specific to JSON and bencode.

**Comment by dtolnay** [comment]
I would be happy to see MapKeySerializer factored into a standalone helper library but I don't plan to do it myself.
