### ISSUE TITLE
Value::pointer_mut

### ISSUE THREAD

**Issue by Mange** [serde-rs/json#166]
I need to change a specific value in a deep `Value` document, depending on the type.

Here's an example:

```json
{"foo": {"bar": {"baz": ["hello"]}}}
{"foo": {"bar": {"baz": {"greeting": "hello"}}}}
```

In the first case I need to append the value to the array. In the second case I need to add another key.

```json
{"baz": ["hello", "world"]}
{"baz": {"greeting": "hello", "recipient": "world"}}
```

Thanks to the very awesome `pointer` method, I can quickly see what value it has:

```rust
use serde_json::Value;

// Assume I own `value` here and that there are no other uses of it.
let baz = value.pointer("/foo/bar/baz");

match baz {
  Some(ref list @ Value::Array(_)) => # ...
  Some(ref obj @ Value::Object(_)) => # ...
  _ => return Err("This example is very contrived.")
}
```

However, there seems to be no way of drilling down and get a mutable reference like `as_object_mut` since `pointer` only gives back references. Do you think it would make sense to add method like this? 

```rust
fn pointer_mut<'a>(&'a mut self, pointer: &str) -> Option<&'a mut Value>
```

Maybe I'm missing something obvious here. I'm still learning the ownership system.

**Comment by oli-obk** [comment]
fixed by #171
