### ISSUE TITLE
Help implementing deserialization for enum

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#170]
From IRC:

> **\<shinglyu>** Anyone familiar with serde_json? I have some problem with implementing deserialization an enum

@shinglyu did you figure this out? What problem were you having?

**Comment by shinglyu** [comment]
@dtolnay One of my enum variant is a custom type which is hard to serialize/deserialize. I want to skip the variant but still derive `Deserialize` for the other simple enum variants. But there doesn't seem to be a easy way to do this, right?

**Comment by dtolnay** [comment]
Makes sense. I filed https://github.com/serde-rs/serde/issues/638 to support this use case in a better way.
