### ISSUE TITLE
code example at https://serde-rs.github.io/json/serde_json/ is fucked up

### ISSUE THREAD

**Issue by ben0x539** [serde-rs/json#20]
The code block after "If we assume that FirstName is optional and all other fields are mandatory, the above JSON could correspond to the following Rust structs:" is not recognized as such and so there's a bunch of rust code interpreted as html:

![](http://i.imgur.com/Y2zAiNO.png)

**Comment by JohnHeitmann** [comment]
Looks like this was fixed in https://github.com/serde-rs/json/commit/c10a4c7f33cbcefd5630830b77ae7c79054eb0ea

**Comment by erickt** [comment]
@JohnHeitmann: you're right, it's been fixed. Thanks!
