### ISSUE TITLE
Bug when parsing without type

### ISSUE THREAD

**Issue by kybishop** [serde-rs/json#201]
https://gist.github.com/kybishop/ecf48136e0a189ebd8dbac4b93303d33

When type info is omitted, a cryptic `Syntax(TrailingCharacters, 1, 2)` error is returned.

Interestingly, this bug does not occur if the array in the example is empty (instead of containing an empty object).

**Comment by oli-obk** [comment]
It looks like the `?` defaults the first argument to `()`. At least giving it a json string containing `[]` works like a charm and prints `()`: http://play.integer32.com/?gist=acb0db4233e5162db4ad8f2532ae2714&version=nightly

I could extend the serde-clippy lint to error when calling a function that takes a `Deserialize` and is given a `()`. Outside of implementing `Deserialize` this is never intended as far as I know

**Comment by dtolnay** [comment]
I don't think this is a serde_json bug. It is just the confusing way that type inference works. In the code below, the type parameter T also gets inferred as ().

```rust
#![feature(core_intrinsics)]

fn main() {
    let _ = decode_json();
}

fn decode_json() -> Result<(), ()> {
    let json = from_str("[{}]")?;

    println!("JSON from string: {:?}", json);

    Ok(())
}

fn from_str<T>(_: &str) -> Result<T, ()> {
    println!("{}", unsafe { ::std::intrinsics::type_name::<T>() });
    unimplemented!()
}
```

Once we get function type parameter defaults we may be able to do something like:

```rust
pub fn from_str<T = serde_json::Value>(s: &str) -> Result<T>
```

but for now I don't think there is anything we can do to make this better.

(Of course the error message could be better but that is tracked at https://github.com/serde-rs/serde/issues/528.)
