### ISSUE TITLE
Serialize optional key/value sets

### ISSUE THREAD

**Issue by dbrgn** [serde-rs/json#21]
In the [spaceapi-rs](https://github.com/coredump-ch/spaceapi-rs) crate, we're implementing the [Space API](http://spaceapi.net/). The crate basically provides the structs for all types in the spec, as well as the serialization and deserialization code.

Right now we're using rustc-serialize. The problem is how rustc-serialize handles optional values. In the Space API spec, there are some values that must be either absent, or contain a value. So `"phone": "012 345 67 89"` is fine, not specifying a phone is also fine, but `"phone": null` is invalid according to the spec. (You could consider the value a non-nullable type.)

rustc-serialize always serializes an `Option::None` to `null`. So we created our own enum called `Optional` that can be either `Value(T)` or `Absent`. The unfortunate result of that is that we have to write custom serialization code for each and every one of our types: https://github.com/coredump-ch/spaceapi-rs/blob/master/src/status.rs#L175-L188

Skimming through the documentation, I didn't see a way to do this more easily with serde. Did I miss something? Or if not, would it be possible to implement something like that in serde?

**Comment by JohnHeitmann** [comment]
Check out the annotation ``#[serde(skip_serializing_if_none)`` here [1]. Does that do what you want?

[1] https://github.com/serde-rs/serde#annotations

**Comment by dbrgn** [comment]
This is *perfect*! :) Thanks!
