### ISSUE TITLE
Clarify interpolation of keys in the tt muncher

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#214]
From reddit:

---

The serde_json "any value that implements Serialize" example is a bit ambiguous:

> Any expression can be included in the serde_json::Value that you build. This works as long as the type of the expression implements Serde's Serialize trait.
>
> let value = json!({ "code": code, "success": code == 200, "payload": { features[0]: features[1] } });

Obviously `features[0]` must be a string or the result cannot be valid JSON.

So will this fail at run or compile time? If compile time, will it allow any `Borrow<str>` for keys, or only `String`?

---

cc @christophebiocca

**Comment by christophebiocca** [comment]
Thanks, that's very clear now.
