### ISSUE TITLE
Promote preserve_order feature

### ISSUE THREAD

**Issue by killercup** [serde-rs/json#216]
Congrats on the 0.9 release! It looks fantastic.

By chance (i.e., curiosity that led me to read the read the implementation of `Map`), I discovered that this crate has a preserve_order feature using linked hash maps, which is very cool! Sadly, it doesn't seem to be mentioned anywhere in the documentation. Is this not an 'official' feature? (Also, there don't seem to be tests that test that the order of fields is actually preserved.)

**Comment by dtolnay** [comment]
Fixed in 0338c0e738464323552565f513d0ad8eec06b42e.
