### ISSUE TITLE
Bad error code propagated for missing field when deserializing a struct

### ISSUE THREAD

**Issue by cmbrandenburg** [serde-rs/json#22]
When deserializing a structure from a JSON string that's missing a field, `serde_json` propagates an `ExpectedSomeValue` error code variant, not the `MissingField` error code variant.

The program below shows the behavior.

Expected output (roughly speaking):

    Got: "missing field x" at line 3 column 5
    OK, got 'missing field' x

Actual output:

    Got: "expected value" at line 3 column 5
    BAD, got 'expected some value'

Here's the program:

    extern crate serde;
    extern crate serde_json;

    #[derive(Debug)]
    struct Foo {
        x: i32,
        y: i32,
    }

    impl serde::Deserialize for Foo {
        fn deserialize<D>(d: &mut D) -> Result<Self, D::Error> where D: serde::Deserializer {

            enum Field {
                X,
                Y,
            }

            impl serde::Deserialize for Field {
                fn deserialize<D>(d: &mut D) -> Result<Self, D::Error> where D: serde::Deserializer {

                    struct Visitor;

                    impl serde::de::Visitor for Visitor {
                        type Value = Field;

                        fn visit_str<E>(&mut self, value: &str) -> Result<Self::Value, E>
                            where E: serde::de::Error
                        {
                            match value {
                                "x" => Ok(Field::X),
                                "y" => Ok(Field::Y),
                                _ => Err(E::unknown_field(value)),
                            }
                        }
                    }

                    d.visit(Visitor)
                }
            }

            struct Visitor;

            impl serde::de::Visitor for Visitor {
                type Value = Foo;

                fn visit_map<V>(&mut self, mut visitor: V) -> Result<Foo, V::Error>
                    where V: serde::de::MapVisitor
                {
                    let mut x = None;
                    let mut y = None;

                    loop {
                        match try!(visitor.visit_key()) {
                            Some(Field::X) => {
                                x = Some(try!(visitor.visit_value()));
                            }
                            Some(Field::Y) => {
                                y = Some(try!(visitor.visit_value()));
                            }
                            None => { break; }
                        }
                    }

                    try!(visitor.end());

                    let x = match x {
                        Some(x) => x,
                        None => try!(visitor.missing_field("x")),
                    };

                    let y = match y {
                        Some(x) => x,
                        None => try!(visitor.missing_field("y")),
                    };

                    let v = Foo {
                        x: x,
                        y: y,
                    };

                    Ok(v)
                }
            }

            static FIELDS: &'static [&'static str] = &["x", "y"];
            d.visit_struct("Foo", FIELDS, Visitor)
        }
    }

    fn main() {

        let s = r#"{
            "y": 17
        }"#;

        let got = serde_json::from_str::<Foo>(&s).unwrap_err();

        println!("Got: {}", got);

        match got {
            serde_json::Error::SyntaxError(code, _line, _column) => {
                match code {
                    serde_json::ErrorCode::MissingField(field) => {
                        println!("OK, got 'missing field' {}", field);
                    }
                    serde_json::ErrorCode::ExpectedSomeValue => {
                        println!("BAD, got 'expected some value'");
                    }
                    _ => { println!("BAD, got some other error code variant"); }
                }
            }
            _ => { println!("BAD, Got unexpected error variant"); }
        }
    }

**Comment by skylerberg** [comment]
I am running into this issue too. I have such a large json object that I actually cannot find the missing field either.

**Comment by cmbrandenburg** [comment]
Here's more information about the root cause. In the `error.rs` source file, there's a `From` implementation for converting upstream `serde` errors into `serde_json` errors. (Here's the [source]( https://github.com/serde-rs/json/blob/b7a6592d8cb76c2eeef6e25c8f7b374883a0edbc/json/src/error.rs#L159-L161).) This converts an upstream `SyntaxError` into the `ExpectedSomeValue` error I'm seeing. The conversion function would correctly propagate a `MissingField` error, but it's not getting one. So the problem is that the upstream `serde` crate is reporting the wrong error. Why?

The `serde_json::de::MapVisitor::missing_field` method, which is the publicly facing function returning the wrong error code here, uses the upstream `serde` crate's `UnitDeserializer` type. This type provides default values for some types—e.g., a `None` value for `Option<T>`, and for other types, such as `i32`, it reports a `SyntaxError`. This is the same `SyntaxError` that's passed to the `From` conversion, above. Aha! 

Presumably, the `UnitDeserializer` type is doing exactly what it's supposed to be doing, and the problem here is that `serde_json` should use some other deserializer type—let's call it `D`—when deserializing missing fields. This `D` type should provide default values for types such as `Option<T>` and report a `MissingFieldError` for other types. I'm still figuring out the best way to implement this.
