### ISSUE TITLE
Enums can parse invalid JSON

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#220]
```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

#[derive(Debug, Deserialize)]
enum E {
    V(u8),
}

fn main() {
    println!("{:?}", serde_json::from_str::<E>(r#" "V"0 "#));
}
```

```
Ok(V(0))
```

**Comment by dtolnay** [comment]
The bug is that KeyOnlyVariantVisitor is parsing the string `"V"` inside visit_variant_seed and then parsing the number `0` inside visit_newtype_seed. The point of KeyOnlyVariantVisitor is that it is supposed to handle unit variants only so it should unconditionally return an error in all the VariantVisitor methods except visit_unit. Let's also rename KeyOnlyVariantVisitor to UnitVariantVisitor to clarify this.

@killercup would you be interested in tackling this?

**Comment by killercup** [comment]
Sure, let me have a look.
