### ISSUE TITLE
Type parameter on Value to control btreemap vs linkedhashmap

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#225]
Idea from @nox: using a defaulted type parameter would be more flexible than the "preserve_order" cfg.

> **\<nox>** In general, I think Value should have many type parameters, one per "complex" type.
> **\<nox>** So you can use it to generate some JSON array of strings or whatever,
> **\<nox>** by doing Value::Array(&[Value::String("foo"), Value::String("bar")]),
> **\<nox>** or something like that.

**Comment by oli-obk** [comment]
This won't allow us to have a `Value::Array(&[Value::Array(vec![]))` without variadic templates and/or HKT

I like the thought in general. Maybe something could be hacked up with `Cow` or a custom enum that makes this somewhat usable through helpers like static functions on `Value` or various `From` impls.

**Comment by dtolnay** [comment]
I would like to see this in an external library. I think it makes sense for serde_json::Value to be the most straightforward representation that it is.

**Comment by nox** [comment]
Making such a type in a separate crate wouldn't allow users to use your `json!` macro, would it?

**Comment by dtolnay** [comment]
I imagine it would provide its own json macro.
