### ISSUE TITLE
Entry API to the Map object

### ISSUE THREAD

**Issue by mathstuf** [serde-rs/json#236]
This API is really nice and would be great to have exposed on the type.

**Comment by dtolnay** [comment]
I agree. Would you be interested in implementing this yourself?

**Comment by dtolnay** [comment]
Actually first we would need to fix https://github.com/contain-rs/linked-hash-map/issues/5.

**Comment by mathstuf** [comment]
I could; not sure of a timeline though.

**Comment by dtolnay** [comment]
Waiting on a linked-hash-map release - https://github.com/contain-rs/linked-hash-map/pull/77.

**Comment by dtolnay** [comment]
I released this in serde_json 0.9.8: [`Map::entry`](https://docs.serde.rs/serde_json/struct.Map.html#method.entry)

**Comment by mathstuf** [comment]
Thanks!
