### ISSUE TITLE
to_value should be bound on ToJson, not Serialize

### ISSUE THREAD

**Issue by kballard** [serde-rs/json#242]
All types that implement `Serialize` implement `ToJson`, but not all types that implement `ToJson` necessarily implement `Serialize`. So `to_value()` should be bound on `ToJson`, not `Serialize`, since that's all it really needs. That way I can implement `ToJson` on my custom types and then use them with the `json!()` macro.

For reference, I'm implementing `ToJson` on my type and not `Serialize` because my type can actually be serialized to both JSON and XML, but the serializations have very different representations, and I don't want to confuse anyone.

**Comment by dtolnay** [comment]
Or `json!` should use ToJson instead of to_value. Would that work for your use case?

I think there is value in consistency across various Serde crates and part of that is `to_*` functions that take Serialize as input.

**Comment by kballard** [comment]
I think that sounds reasonable. For my specific use case, having `json!` use `ToJson` instead of `to_value()` would certainly work.
