### ISSUE TITLE
Derive from custom trait fix

### ISSUE THREAD

**Issue by MMKnight** [serde-rs/json#254]
> `#[derive]` for custom traits is not stable enough for use. It is deprecated and will be removed in v1.15 (see issue #29644)

I have this issue now the code is

```
#[derive(Serialize, Deserialize)]
struct Address {
    street: String,
    city: String,
}
```

Please do anything or fix it.

**Comment by oli-obk** [comment]
have you updated your compiler? Have you added `#[macro_use] extern crate serde_derive` to your crate root?

**Comment by dtolnay** [comment]
`#[macro_use] extern crate serde_derive` is probably what is missing. Remember it needs to be in `lib.rs` and `main.rs` if you have both of those, and it needs to be in every test file that uses derive.
