### ISSUE TITLE
Support deserializing arbitrary bytes inside strings

### ISSUE THREAD

**Issue by bennofs** [serde-rs/json#256]
I know that it's not correct according to the JSON standard, but sometimes you get to deal with json that has arbitrary bytes inside a string literal (except '"'). To accomodate this use case, I suggest that we explictly implement the following two functions for the Deserializer:

* deserialize_bytes
* deserialize_byte_buf

to parse Strings without doing any processing on them, just returning the bytes. They can then be used to explictly request that one wants to parse a "raw" string.

**Comment by bennofs** [comment]
If I were to implement this and submit a PR, would the PR be accepted?

**Comment by dtolnay** [comment]
Yes I would accept this.
