### ISSUE TITLE
write_string_fragment should take &str instead of &[u8]

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#268]
https://docs.serde.rs/serde_json/ser/trait.Formatter.html#method.write_string_fragment

rq is using unsafe to get a &str: https://github.com/dflemstr/rq/blob/v0.9.2/src/value/json.rs#L224

```rust
let s = unsafe { str::from_utf8_unchecked(fragment) };
```

It should be our responsibility to guarantee that the fragment is UTF-8.

cc @dflemstr

**Comment by dtolnay** [comment]
Frustratingly, it is such an easy fix: #269.

**Comment by dflemstr** [comment]
I approve of this :+1:

**Comment by dtolnay** [comment]
Fixed in #297.
