### ISSUE TITLE
 Same as  #254, but putting "#[macro_use] extern crate serde_derive" in lib.rs doesn't fix

### ISSUE THREAD

**Issue by Paul-E** [serde-rs/json#277]
I am getting the same error as #254 ,

`error: '#[derive]' for custom traits is not stable enough for use. It is deprecated and will be removed in v1.15 (see issue #29644)`

despite putting

      #[macro_use
      extern crate serde_json;

in my lib.rs

I have uploaded the smallest example I could construct [here](https://github.com/Paul-E/rust_compile_issue). It isn't clear if this is something wrong with the way I am using the module system, something in serde, or something in rust.

**Comment by oli-obk** [comment]
Please read the [setting up codegen](https://serde.rs/codegen.html) page on serde.rs.

For `#[derive(Serialize, Deserialize)]` to work you need to depend on `serde_derive` and include it with `#[macro_use] extern crate serde_derive;`

**Comment by dtolnay** [comment]
@Paul-E did you get this working?

**Comment by Paul-E** [comment]
Yes, my mistake. Everything necessary was in the provided link. I was using serde_json when I should have been using serde_derive after the macro use. Thank you for the help.On Mar 9, 2017 6:34 AM, David Tolnay <notifications@github.com> wrote:@Paul-E did you get this working?
