### ISSUE TITLE
null deserializes as an empty Vec

### ISSUE THREAD

**Issue by alex-shapiro** [serde-rs/json#283]
The following code compiles and runs without panicking:

```rust
let x: Vec<i32> = vec![];
let y: Vec<i32> = serde_json::from_str("null").unwrap();
assert!(x == y);
```
However, it seems like this breaks some fundamental serde assumptions - for other types, deserializing from null requires wrapping the type in an `Option`. Is there a reason why `Vec` behaves this way?

**Comment by dtolnay** [comment]
I agree. I filed https://github.com/serde-rs/serde/issues/836 to follow up on the Serde side because this affects all formats.
