### ISSUE TITLE
Error with Example: "invalid type: map, expected unit"

### ISSUE THREAD

**Issue by bryaan** [serde-rs/json#284]
With a copy straight from the example I get:
```rust
    let data = r#" { "age": 43, "name": "John Doe" } "#;
    let v: Value = serde_json::from_str(data)?;
```

Error:
```
let v: Value = serde_json::from_str(data)?;
the trait `std::ops::Carrier` is not implemented for `()`

```

After reworking a little to get it to compile:

```rust
    let data = r#"{ "age": 43 }"#;
    match from_str(data) {
        Ok(v) => v,
        Err(e) => panic!("{:?}", e)
    };
```
Error:
thread 'main' panicked at 'Syntax(Message("invalid type: map, expected unit"), 1, 3)'

**Comment by dtolnay** [comment]
Check out [this chapter of the book](http://rust-lang.github.io/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-) to learn about the question mark, and [this chapter](http://rust-lang.github.io/book/second-edition/ch02-00-guessing-game-tutorial.html) (where it talks about `let guess: u32`) to learn about types in `let` statements.

Here is how it works:

```rust
extern crate serde_json;
use serde_json::{Value, Error};

fn bryaan() -> Result<(), Error> {
    let data = r#" { "name": "John Doe", "age": 43, "phones": ["+44 1234567"] } "#;
    let v: Value = serde_json::from_str(data)?;
    println!("Please call {} at the number {}", v["name"], v["phones"][0]);
    Ok(())
}

fn main() {
    bryaan().unwrap();
}
```

Eventually I will add links to runnable versions of all the example code. This is tracked in #264.

**Comment by bryaan** [comment]
@dtolnay Thanks! I'm trying to figure out what the relationship is between adding the return type which allows the ? to work.

**Comment by dtolnay** [comment]
It is explained in the [next section](http://rust-lang.github.io/book/second-edition/ch09-02-recoverable-errors-with-result.html#-can-only-be-used-in-functions-that-return-result).

**Comment by bryaan** [comment]
@dtolnay Now I understand it, the ? brings the possibility of returning with Err and therefore requires the Result return type

**Comment by morristai** [comment]
Thanks @dtolnay, I came here and realized I forgot to add `Value` as type.
