### ISSUE TITLE
Line Numbers on Valid JSON

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#286]
From https://github.com/maciejhirsz/json-rust/issues/110:

> I am considering using this library to facilitate syntax highlighting capabilities. I understand you currently report line / col numbers for syntax errors. However, I am interested in reporting errors on well-formed JSON documents and I'd like to be able to reference the line/col information within the document. For example...
>
> {
> "name": "test123"
> }
>
> ... is a valid JSON document, but my program would report an error stating that "name must only contain letters", and thus I would like to be able to lookup the line number for the 'name' property and visually highlight it. Is providing such information something you would consider?

**Comment by dtolnay** [comment]
Validation can happen during deserialization. With Serde you don't have to deserialize into a String and then validate separately afterward. Would something like this work?

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::fmt;
use serde::de::{self, Deserializer, Visitor};

#[derive(Deserialize, Debug)]
struct Esheri3 {
    #[serde(deserialize_with = "letters_only")]
    name: String,
}

fn letters_only<D>(deserializer: D) -> Result<String, D::Error>
    where D: Deserializer
{
    struct NameVisitor;

    impl Visitor for NameVisitor {
        type Value = String;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("string containing only letters")
        }

        fn visit_str<E>(self, s: &str) -> Result<Self::Value, E>
            where E: de::Error
        {
            if s.chars().all(char::is_alphabetic) {
                Ok(s.to_owned())
            } else {
                Err(de::Error::custom("name must only contain letters"))
            }
        }
    }

    deserializer.deserialize_string(NameVisitor)
}

fn main() {
    let j = r#"
        {
          "name": "test123"
        }
    "#;
    println!("{}", serde_json::from_str::<Esheri3>(j).unwrap_err());
}
```

The error message points to the string "test123":

> name must only contain letters at line 3 column 27

**Comment by EliSnow** [comment]
@dtolnay, I'm wondering if it is possible to store the line numbers with a successful deserialization? I have the case where I deserialize from a YAML file to a string, and later on (long after serde has deserialized) with more context, I have a pest parser which parses that string. Pest gives really nice error messages when it fails and even includes the ability to adjust the line numbers. I'd like to be able to display to the end-user the pest error message with the line numbers coordinating with the correct location in the YAML file.
