### ISSUE TITLE
Unable to parse double between 0 and 1

### ISSUE THREAD

**Issue by hamersaw** [serde-rs/json#293]
Using this library I'm unable to parse a json string like {"field":0.123}. Quickly looking through the code it appears you can only fall through to parse_decimal(...) in the case that the decimal number is >= 1. This happens from parse_integer() -> parse_long_integer() -> parse decimal(). I think it would make sense to integrate a b'.' match case in th parse_integer() function to handle the case described.

**Comment by dtolnay** [comment]
Can you share your code? It works when I tried it.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Deserialize, Debug)]
struct Hamersaw {
    field: f64,
}

fn main() {
    println!("{:?}", serde_json::from_str::<Hamersaw>("{\"field\":0.123}").unwrap());
}
```

**Comment by hamersaw** [comment]
Apologies, the conversion error is definitely not in this crate. It paniced during conversion from json::Value to Bson::Document.
