### ISSUE TITLE
`serde_json` should accept `serde` versions above 0.9.11

### ISSUE THREAD

**Issue by khuey** [serde-rs/json#298]
I'd like to pull in serde-rs/serde@f500db6e91d46a9f61a7e9775137deb2ba45fed2 to the copy of `serde` my project is using directly but `serde_json` insists on 0.9.11.

**Comment by dtolnay** [comment]
The current version of serde_json allows any serde version 0.9.11 <= x < 0.10.0. Does the newest serde not get pulled in when you run cargo update? Also the commit you linked to is included in every serde version since 0.9.8, including 0.9.11.

**Comment by khuey** [comment]
Hrm, indeed.  Not sure what I was doing wrong before but it works fine for me now.
