### ISSUE TITLE
Breaking changes in 1.0.0

### ISSUE THREAD

**Issue by kosta** [serde-rs/json#305]
Hi! 

I tried to upgrade my (non-open-source) project to serde_json 1.0.0 but I ran into the following errors. They are _not_ mentioned in the release notes:

* std::io::Error can no longer be converted to serde_json::Error using `.into()`. This used to work. I guess it's ok to break but please mention in the release notes.
* serde_json::to_writer now _consumes_ the writer. Is this on purpose? It seems to have been introduced in this commit  https://github.com/serde-rs/json/commit/391821c6348852f1eeb2df737fb9d77518cb694c with commit message "Allow writing to writer by value". This one does not make sense to me.

**Comment by dtolnay** [comment]
Thanks for calling this out! I added both of these.

- The serde_json::Error type is intended to be constructed by serde_json, not by your code. Having the From\<io::Error> impl was API sloppiness on our part to make `?` work in our code.

- The standard library provides `impl<'a, W: Write + ?Sized> Write for &'a mut W` which means if we take W by value, you can pass \&mut W using this impl. At the same time, by value is nicer for some Write implementations. For example `&mut [u8]` implements Write so before you would have had to pass `&mut &mut [u8]` as the argument. Or writing to a file:

    ```diff
    - let mut file = File::open(...)?;
    - serde_json::to_writer(&mut file, &v)
    + let file = File::open(...)?;
    + serde_json::to_writer(file, &v)
    ```

**Comment by kosta** [comment]
Thanks for your quick reply and for updating the release notes! 

I agree that these changes looks good. Thank you for driving serde forward! 👍
