### ISSUE TITLE
ser: some way to opt-in canonical JSON output

### ISSUE THREAD

**Issue by lucab** [serde-rs/json#309]
When relying on digests of JSON data, it is often required that the content should be in some canonical form so that different serializer can deterministically reproduce the same data bit-by-bit.

The topic is a bit tricky as there is not a single JSON canonical format, but several similar efforts:
 * an expired IETF draft - https://tools.ietf.org/html/draft-staykov-hu-json-canonical-form-00
 * keybase spec - https://keybase.io/docs/api/1.0/canonical_packings#json
 * OLPC / TUF spec - http://wiki.laptop.org/go/Canonical_JSON

(I'd personally be interested in one of the latter twos)

I'm not sure whether a `CanonicalFormatter` would be enough for this or if it requires something more invasive?

**Comment by dtolnay** [comment]
https://github.com/vtduncan/canonical_json may implement this already. If it can be as simple as swapping in Formatter, I would be open to providing it in serde_json.

**Comment by lucab** [comment]
Ah, it looks like I didn't do enough due diligence investigation before filing this, as I missed the above crate. Also, it looks like it needs update to 1.0 and I hit this at the right time, as you reported it yesterday :smile:

But yes, I would love to see it integrated here.
/cc @vtduncan

**Comment by dtolnay** [comment]
I'm happy to focus on conventional JSON here and leave Canonical JSON to a different library. Thanks!

**Comment by lucab** [comment]
@dtolnay ack, thanks. While at it, it looks the repo you originally linked disappeared in the meanwhile (and it was quite obsolete even before). Do you know about any up-to-date efforts on this?

**Comment by cyberphone** [comment]
Standard-in-progress needing the same basic features:
https://tools.ietf.org/id/draft-erdtman-jose-cleartext-jws-00.html

**Comment by dtolnay** [comment]
I think it moved to https://github.com/zmanian/canonical_json.

But that library is a full fork of serde_json. The way I would recommend exposing this in a library instead is as a [`Formatter`](https://docs.serde.rs/serde_json/ser/trait.Formatter.html) implementation:

```rust
let mut ser = serde_json::Serializer::with_formatter(&mut out, canonical_json::Formatter);
t.serialize(&mut ser)?;

// equivalent for convenience
let cj = canonical_json::to_string(&t)?;
```

**Comment by cyberphone** [comment]
The hard part is the formatting of numbers.  I just ported 2000 lines of java code to .NET to achieve compatibility wit the Internet-Draft:
https://github.com/cyberphone/json-canonicalization/blob/master/dotnet/es6numberserialization/README.md

**Comment by radu-matei** [comment]
Hey, @dtolnay!
Quick question about implementing this as a `Formatter` -- one of the key aspects of canonical JSON is the lexicographical order of the keys in the JSON -- is there a way to sort the order the object keys only through a formatter?

Thanks, and thanks for all the work on a really nice library and API!

**Comment by dtolnay** [comment]
Yes @radu-matei, the formatter will need to sort the entries -- probably in Formatter::object_end since by then all the entries have been seen.
