### ISSUE TITLE
Possibility to deserialize &Value to type cloning on-the-way?

### ISSUE THREAD

**Issue by daboross** [serde-rs/json#310]
I'm trying to deserialize json input into either a "success" or an "error" type, both of which are fully owned (no borrows) by design.

In serde 0.9, I first deserialized the input stream to a json `Value`, then passed `&value` to two different call attempts - I assumed that this would be pretty cheap, since a failed parse would generally fail on the first field attempted being missed, and thus no strings would need to be reallocated for the failed attempt.

In serde 1.0 though, I can't seem to get this to work.

My code is roughly:

```rust
let json: serde_json::Value = match serde_json::from_reader(&mut response) {
    Ok(v) => v,
    Err(e) => return Err(Error::with_url(e, Some(response.url.clone()))),
};

let result = match R::RequestResult::deserialize(&json) {
    Ok(v) => v,
    Err(e) => {
        match R::ErrorResult::deserialize(&json) {
            Ok(v) => return Err(Error::with_json(v, Some(response.url.clone()), Some(json))),
            // Favor the primary parsing error if one occurs parsing the error type as well.
            Err(_) => return Err(Error::with_json(e, Some(response.url.clone()), Some(json))),
        }
    }
};
```

R::RequestResult and R::ErrorResult are associated types which are bound to `serde::Deserialize<'static> + 'static`.

The error I get with serde 1.0:

```
error: `json` does not live long enough
   --> src/lib.rs:560:59
    |
560 |         let result = match R::RequestResult::deserialize(&json) {
    |                                                           ^^^^ does not live long enough
...
572 |     }
    |     - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error: `json` does not live long enough
   --> src/lib.rs:563:52
    |
563 |                 match R::ErrorResult::deserialize(&json) {
    |                                                    ^^^^ does not live long enough
...
572 |     }
    |     - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...

error: aborting due to 2 previous errors
```

Ideally I would like to deserialize from a borrowed json value and only clone things only once each field has been successfully found - so that the most common error of "missing field" won't cause any extra allocations (like if I had to clone the whole json value).

If this isn't possible, I can always create a go-between struct which implements `Deserialize` for borrowed values, then provides a to_owned method. This wouldn't be ideal, as it would require an additional structure and implementation in every different result type, but it would be a workable solution if there isn't any other.

Hope that's a good explanation of my use case - I can provide more examples if needed. Thanks!

**Comment by daboross** [comment]
Managed to fix this, seems it was just an error in how I declared my trait! Thanks to oli-obk in irc.

Working version has `AssocItem: for<'de> Deserialize<'de>` instead of `AssocItem: Deserialize<'static>`

**Comment by Mark-Simulacrum** [comment]
You probably want to use `DeserializeOwned`, which is just an alias for the `for<'de> Deserialize<'de>`. Unfortunately it's not exported in crate root, you have to import like this: `use serde::de::DeserializeOwned;`.

**Comment by dtolnay** [comment]
@daboross https://serde.rs/lifetimes.html gives a bit more detail about these lifetimes, and trait bounds in particular.
