### ISSUE TITLE
Invalid JSON produced

### ISSUE THREAD

**Issue by nixpulvis** [serde-rs/json#33]
I was playing around with custom `Serialize` implementation, and granted this is not a sane thing, but I would expect this to not produce the JSON string `{1,2}` as it currently does.

```rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

extern crate serde;
extern crate serde_json;

#[derive(Deserialize, Debug)]
struct Point {
    x: i32,
    y: i32,
}

impl serde::Serialize for Point {
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: serde::Serializer
    {
        serializer.visit_struct("Point", PointMapVisitor {
            value: self,
            state: 0,
        })
    }
}

struct PointMapVisitor<'a> {
    value: &'a Point,
    state: u8,
}

impl<'a> serde::ser::MapVisitor for PointMapVisitor<'a> {
    fn visit<S>(&mut self, serializer: &mut S) -> Result<Option<()>, S::Error>
        where S: serde::Serializer
    {
        match self.state {
            0 => {
                self.state += 1;
                Ok(Some(try!(serializer.visit_seq_elt(&self.value.x))))
            }
            1 => {
                self.state += 1;
                Ok(Some(try!(serializer.visit_seq_elt(&self.value.y))))
            }
            _ => {
                Ok(None)
            }
        }
    }
}

fn main() {
    let point = Point { x: 1, y: 2 };
    let serialized = serde_json::to_string(&point).unwrap();
    println!("{}", serialized);

    let serialized = "{\"x\": 6, \"y\": 12}";
    let deserialized: Point = serde_json::from_reader(serialized.as_bytes()).unwrap();
    println!("{:?}", deserialized);
}
```

### Meta
```
rustc 1.8.0-nightly (303892ee1 2016-01-30)
```

**Comment by erickt** [comment]
Yeah, this is a known issue. The "serde" protocol is not yet enforced by the type system, so as of right now serde_json assumes you've implemented `Serialize`/`Deserialize` correctly. You're right though that it'd make sense for serde_json to check that it's being used correctly until we figure out how to statically enforce the protocol.

**Comment by dtolnay** [comment]
This is largely fixed by the SeqState / MapState mechanism in 0.8.0. It is no longer possible to call serialize_struct followed by serialize_seq_elt unless you really go out of your way.

If anyone comes across this issue after writing an incorrect Serialize by mistake and getting invalid JSON, please leave a comment and we can look at whether additional changes are warranted.
