### ISSUE TITLE
Unable to deserialise empty reader/str - shouldn't it be unit?

### ISSUE THREAD

**Issue by OJFord** [serde-rs/json#333]
Perhaps I just have funny expectations, but I thought I'd be able to do something like:

```rust
let unit = serde_json::from_str::<()>(some_str).expect("not what we expected");
```

which results in an `EofWhileParsingValue` error if `some_str == ""`. Instead, `"null"` would deserialise correctly.

In my actual use case, the type I'm deserialising to is variable, but in some cases it evaluates to `()`, which I intended to represent empty. For this reason, I can't simply do `unwrap_or(())` instead of `expect`.

The only alternative I can think of is to wrap the call, mapping empty inputs to `"null"` inputs, which is fine, it just seems slightly silly - is there a reason not to support empty, or existing support that I've missed?

**Comment by dtolnay** [comment]
The empty string is not valid JSON. See the diagrams on http://json.org/ for what is valid JSON syntax.

One workaround would be to use [`StreamDeserializer`](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html) which is able to deserialize zero or more JSON values from a single input—though note that the top level element(s) must be array `[...]` or object `{...}`.

**Comment by OJFord** [comment]
Ah, of course. It would be helpful if it could be `None`, as some top-level `Option<T>`, but I suppose you don't want to start special casing the possibilities for invalid JSON.

> One workaround would be to use StreamDeserializer which is able to deserialize zero or more JSON values from a single input

Unfortunately that would just move my problem - I'd then be either expecting `0` or `1` elements depending on the item type; accessing that still requires wrapping in something, probably with specialisation to return `()` in the `0` case.

I think I just need to re-think more thoroughly and avoid giving serde invalid JSON when I expect a valid response. Many thanks for your help.
