### ISSUE TITLE
serde_json::Error ought to derive a few more traits

### ISSUE THREAD

**Issue by generalelectrix** [serde-rs/json#335]
At the very least, it would be great if serde_json::Error derived Clone.  Eq and PartialEq would be nice bonuses.  This would make the library more ergonomic and improve testability as it allows a direct comparison of expected errors.  Clone would be nice if a serialization error needs to get passed to more than one thread across a channel.

**Comment by generalelectrix** [comment]
Hmm, well, it looks like even the std library error types generally don't provide Clone.  I'll just close this and go write newtype wrappers.

**Comment by brycefisher** [comment]
I'd like to request that this issue be re-opened. Without deriving `PartialEq` its impossible to test using `asserrt_eq!`. What's the best way to test code that uses `serde_json` internally?

**Comment by jplatte** [comment]
@dtolnay I'd also like this to be reconsidered. In ruma-events, I currently have to `.to_string()` json errors because I want structs that indirectly contain them to implement `Clone`.

**Comment by tyranron** [comment]
@dtolnay

+1 for the case. Lack of `Clone` implementation pushes developers to use `.to_string()` ending up with stringly-typed opaque errors.

**Comment by qwandor** [comment]
+1 for this, I'll send a PR.

**Comment by legoktm** [comment]
I stumbled upon this while trying to see if someone else had already asked for `Clone` on the Error type. https://github.com/seanmonstar/reqwest/issues/1053#issuecomment-705715212 suggested wrapping non-Clone errors in an `Arc`, which fulfilled my use case, I hope that might be helpful to others.
