### ISSUE TITLE
Map has no method get

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [serde-rs/json#337]
I am trying to `get` a value by a key from a `serde_json::Map<std::string::String, app_structs::Word>`, where `Word` is a custom `struct`, which looks as follows:

    #[derive(Serialize, Deserialize, Clone)]
    pub struct Word {
        pub metadata: WordMetadata,
        pub translation_data: WordTranslationData
    }

I saw on https://docs.serde.rs/serde_json/map/struct.Map.html#method.get that there is supposed to be some `get` method for the map, but I don't know how to use it. When I try to use it as follows:

    let the_word: Word = the_vocabularies.first().unwrap().words.get(word_id)
            .cloned()
            .collect::<Word>();

I always get an error:

    no method named `get` found for type `serde_json::Map<std::string::String, app_structs::Word>` in the current scope [E0599]

`Vocabulary` is also a custom `struct`, which looks like this:

    extern crate serde_json;

    use serde_json::map::Map;

    #[derive(Serialize, Deserialize, Clone)]
    pub struct Vocabulary {
        pub metadata: VocabularyMetadata,
        pub words: Map<String, Word>
    }

**Comment by dtolnay** [comment]
The type of JSON maps is always `Map<String, Value>`. You need to use [`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html) or [`HashMap`](https://doc.rust-lang.org/std/collections/struct.HashMap.html) if you need different types.

**Comment by ZelphirKaltstahl** [comment]
@dtolnay Thanks, that answered my question. I think this can be closed.
