### ISSUE TITLE
Add unwrap method to Deserializer to get the inner iterator

### ISSUE THREAD

**Issue by erickt** [serde-rs/json#34]
This should return the iterator, and the potentially buffered but unused character. I'm not sure if it'll ever actually have a value, but returning a value that's almost always `None` couldn't hurt.

**Comment by dtolnay** [comment]
Where would this be useful?

**Comment by dtolnay** [comment]
I am closing this until we see evidence that it would be useful. If anyone comes across this issue and would *actually use* this feature, please leave a comment.
