### ISSUE TITLE
How to get the original string value of floating point number?

### ISSUE THREAD

**Issue by shelbyd** [serde-rs/json#340]
I'm building an application that needs precise numbers. An API that I'm getting data from sends their numbers in JSON as raw numbers. I need the value as transmitted over the wire so I can build a num::Ratio from it without rounding errors.

```rust
extern crate serde;
extern crate serde_json;
#[macro_use] extern crate serde_derive;

#[derive(Deserialize, Eq, PartialEq, Debug)]
struct Test {
    foo: String
}

fn main() {
    let input = r#"{"foo": 1.01}"#;
    let t: Test = serde_json::from_str(input).unwrap();
    assert_eq!(t, Test { foo: "1.01".to_owned() });
}
```

The only thing I've thought that would work is to make my own struct that implements Deserializer and delegates to serde_json::Deserializer unless there are numbers. The problem is that I cannot interact with the read or call the parse_* methods of serde_json::Deserializer.

Am I going in the right direction? Am I missing something obvious?

I've seen https://github.com/serde-rs/serde/issues/185, but that doesn't seem to be in 1.0.2.

Next, I'm probably going to fork the repo and update the code to fit my purpose. But I hate doing that, so I'm checking for another option.

**Comment by dtolnay** [comment]
This is not supported. If you are forking the code, there is a working implementation in #252 to get you started.

**Comment by shelbyd** [comment]
For posterity, I got this working with the current release of serde/serde_json.

```rust
extern crate serde;
extern crate serde_json;
#[macro_use] extern crate serde_derive;

use serde::de::{Deserialize, Deserializer};
use serde_json::Number;

#[derive(Deserialize, Eq, PartialEq, Debug)]
struct Test {
    #[serde(deserialize_with = "foo")]
    foo: String
}

fn foo<'de, D: Deserializer<'de>>(d: D) -> Result<String, D::Error> {
    let n: Number = Deserialize::deserialize(d)?;
    Ok(n.to_string())
}

fn main() {
    let input = r#"{"foo": 1.01}"#;
    let t: Test = serde_json::from_str(input).unwrap();
    assert_eq!(t, Test { foo: "1.01".to_owned() });
}
```

My best guess is that the rust compiler notices I'm essentially calling `"1.01".parse::<f64>().to_string()` and removes the `parse` & `to_string` calls. It also works if I change the type from `Number` to `f64` inside the `foo` function.

I don't really like relying on compiler magic, but it's the best option I've found so far.

**Comment by dtolnay** [comment]
Be careful. That is definitely not giving you the precise number.

```rust
let input = r#"{"foo": 1.0000000000000001}"#;
let t: Test = serde_json::from_str(input).unwrap();
assert_eq!(t, Test { foo: "1".to_owned() });
```

If you need 1.0000000000000001, you need to use a fork or a different library.

**Comment by utkarshgupta137** [comment]
@dtolnay Can we implement `impl From<Number> for String` if `arbitrary_precision` is enabled? We want to get the string value, but don't want to rely on the compiler to optimize `.parse::<f64>.to_string()` away as @shelbyd said. I'll be happy to raise a PR.

**Comment by odisseylm** [comment]
Just FYI: now you can use serde_json/raw_value feature (I used it for BigDecimal precise parsing from json).
