### ISSUE TITLE
Feature request: a way to handle unrecognized enum variants

### ISSUE THREAD

**Issue by wfraser** [serde-rs/json#342]
It would be nice to be able to specify a fallback enum variant in case none of the others match.

Something like:
```
#[derive(Debug, Deserialize)]
#[serde(tag = ".tag")]
pub enum Foo {
    #[serde(rename = "a")] A(A),
    #[serde(rename = "b")] B(B),
    #[serde(fallback)] Unknown,    // <- this
}
```

where if you parse `{ ".tag": "c", "hello": "world" }`, it deserializes as `Foo::Unknown`.

Right now, you just get a deserialize error. I'd rather not write my own deserialization logic just to handle this common case.

It'd be nice to also be able to do `#[serde(fallback)] Unknown(serde_json::value::Value),` to capture the parsed JSON without a strongly-typed structure.

**Comment by dtolnay** [comment]
Thanks! We are tracking this in https://github.com/serde-rs/serde/issues/912.
