### ISSUE TITLE
Serialising BTreeMap

### ISSUE THREAD

**Issue by glennpierce** [serde-rs/json#343]
How can I serialise a BTreeMap and when deserialising it
convert it back to a BTreeMap from serde_json::map::Map  ?

Having trouble with

expected struct `std::collections::BTreeMap`, found struct `serde_json::Map`

Thanks

**Comment by dtolnay** [comment]
A serde_json::Map is not guaranteed to be backed by a BTreeMap. They are different types.

I would recommend deserializing to BTreeMap directly if that's the type you need.

```rust
extern crate serde_json;

use std::collections::BTreeMap;

fn main() {
    let j = r#" {"A":65, "B":66} "#;
    let m: BTreeMap<String, i32> = serde_json::from_str(j).unwrap();
    for (k, v) in m {
        println!("m[{:?}] = {:?}", k, v);
    }
}
```

Separately, in general any two map types can be converted like this.

```rust
extern crate serde_json;

use serde_json::Value;
use std::collections::{BTreeMap, HashMap};

fn main() {
    // Any map.
    let b = BTreeMap::<String, Value>::new();

    // Convert to any other map.
    let h: HashMap<_, _> = b.into_iter().collect();
}
```
