### ISSUE TITLE
Separate the JSON parser from the Deserializer

### ISSUE THREAD

**Issue by mehcode** [serde-rs/json#344]
I'd like to be able to use the parser directly and track line/column on parsed Values. Something like: http://chyh1990.github.io/yaml-rust/doc/yaml_rust/parser/enum.Event.html

If this is a use case you're interested in supporting, I don't mind trying to spike an implementation of ripping out the parser into an event streamer.

**Comment by dtolnay** [comment]
This would be great. I am interested to see what you come up with.

**Comment by dtolnay** [comment]
I continue to be interested in considering something like this, but I don't plan to work on it myself and it seems you are no longer working on it either. I am closing the issue but we can reopen as needed.
