### ISSUE TITLE
Allow deserialization of enum from integer types

### ISSUE THREAD

**Issue by mqudsi** [serde-rs/json#349]
For a plain enum such as 

```rust
enum E {
    Foo = 0,
    Bar
}
```

serde's json deserializer should support deserialization from integer types. Currently, when attempting to deserialize a json string containing such an enum represented as an integer, serde throws an incorrect error `ExpectedSomeValue`

Example:

```
> {"action":0," ...}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: ExpectedSomeValue, line: 1, column: 11 }', src/libcore/result.rs:860
```

where `action` is a plain enum like described above.

**Comment by dtolnay** [comment]
Seems reasonable. Would you be interested in implementing this?

We will need to generate a visit_u64 implementation for C-like enums in serde_derive.

**Comment by RalfJung** [comment]
Would this essentially amount to supporting something like <https://serde.rs/enum-number.html> in serde proper, probably controlled by an attribute like the other representations in https://serde.rs/enum-representations.html? If yes, I would be interested in implementing this.

**Comment by dtolnay** [comment]
Correct, I imagine this would be an attribute that tells serde_derive to produce Serialize and Deserialize impls that behave like the ones in that `enum_number!` macro.

**Comment by dtolnay** [comment]
Implemented in https://github.com/dtolnay/serde-repr:

```rust
#[derive(Serialize_repr, Deserialize_repr)]
#[repr(u16)]
enum SmallPrime {
    Two = 2,
    Three = 3,
    Five = 5,
    Seven = 7,
}
```

**Comment by linonetwo** [comment]
I think this can be reopened, because of dtolnay/serde-repr#18

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/211460684-bdbcc5b3-d87e-468d-9c9c-e4911e259765.png)

This is not working

```rust
#[derive(Type, Serialize, Deserialize, PartialEq, Eq, Debug, Clone, Copy, JsonSchema)]
#[serde(untagged)]
pub enum WorkspaceType {
    #[serde(with = "i8")]
    Private = 0,
    #[serde(with = "i8")]
    Normal = 1,
}
```
