### ISSUE TITLE
misleading error message

### ISSUE THREAD

**Issue by fmoor** [serde-rs/json#352]
I was going through the [serde_json :: de :: from_reader](https://docs.serde.rs/serde_json/de/fn.from_reader.html) example and encountered an error at run time "KeyMustBeAString". I went back to my json file and looked. All of the keys were strings... I scratched my head and stared. Then I noticed that I had a trailing comma after the last value.

It seems like adding another error code that has something to do with trailing commas would make the error messages more human friendly.

test.json
```json
{
  "fingerprint": "gray",
  "location": "1",
}
```

error message:
```rust
ErrorImpl { 
    code: KeyMustBeAString,
    line: 4,
    column: 1
 }
```

**Comment by dtolnay** [comment]
I agree! Would you be interested in implementing this? The code for parsing a map key will need to recognize when it gets a `}` and treat that as a trailing comma error.

**Comment by fmoor** [comment]
I give it a go.

**Comment by fmoor** [comment]
Is there documentation on contributing? It seems like the tests don't compile on rustc stable...

**Comment by fmoor** [comment]
I switched to nightly and the tests compile with warnings about unused extern crate. Only a hand full of tests run and they all fail. What gives?

```
rustc 1.21.0-nightly (7eeac1b81 2017-08-30)
cargo 0.22.0-nightly (3d3f2c05d 2017-08-27)
```

**Comment by fmoor** [comment]
Further study of travis.sh revealed that I was missing a build step
```
(cd "$DIR/tests/deps" && channel build)
```
All tests seem to be passing. On to the real work.
