### ISSUE TITLE
Failing clippy: cast_lossless

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#354]
```
error: casting u8 to u64 may become silently lossy if types change
   --> src/de.rs:284:31
    |
284 |                 let mut res = (c - b'0') as u64;
    |                               ^^^^^^^^^^^^^^^^^ help: try: `u64::from((c - b'0'))`
```

*(and lots more like this)*

**Comment by dtolnay** [comment]
Suppressed in fd96650377a112f9a82c8893fb61f22038ce53ea.

**Comment by oli-obk** [comment]
You dislike the lint? Is the issue you have with it just u8 to something else?

**Comment by dtolnay** [comment]
I agree that u64::from is theoretically safer and more correct but I disagree that there is any practical risk from refactoring the input type wrong. Do you have any examples of this causing problems in practice? Maybe it is the sort of thing I need to experience myself before becoming a believer.
