### ISSUE TITLE
serde_json 1.0.3 broke Diesel's build

### ISSUE THREAD

**Issue by sgrif** [serde-rs/json#357]
The following code will compile successfully on its own, but fails if `extern crate serde_json;` is added where serde_json is 1.0.3. 1.0.2 will compile successfully.

```rust
fn returns_generic_vec_result<T>() -> Result<Vec<T>, ()> {
    Ok(Vec::new())
}

fn main() {
    let bools = vec![true, false];
    let stuff = returns_generic_vec_result().unwrap();
    assert_eq!(bools, stuff);
}
```

I believe that [this commit](https://github.com/serde-rs/json/commit/7fbf18e95e1f85a8654534385931818d5135db7b) is what broke things. That is technically a minor breaking change as defined in [RFC #1105](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md). That said, I personally think that implementing a trait that is not defined in your library for a type that is not defined in your library should be reserved for semver-major, as it can cause completely unrelated code to break in surprising and hard to debug ways (like this case). I figured I'd bring it to your attention either way

**Comment by dtolnay** [comment]
Thanks for reporting this! I will be more mindful of new trait impls in the future.

**Comment by RalfJung** [comment]
Cc @ehuss, should this be mentioned in the semver compatibility rules / guidelines?

**Comment by ehuss** [comment]
That's a weird one!  I added it to the list at https://github.com/rust-lang/cargo/issues/8736. It might already be covered by one of the other "implement a trait can break things" entries, but this seems subtly different. I'm not too familiar with the inference algorithm, so I'm not sure how best to express inference issues (there's also a question of whether or not we should consider inference changes as breaking).
