### ISSUE TITLE
parsing enums inside structs with adjacent tags

### ISSUE THREAD

**Issue by alkis** [serde-rs/json#361]
Pardon the title. Let me explain with an example:

```json
{
  "id": 123,
  "desc": "lalala",
  "type": "animal",
  "details": {
    "limbs": 4,
    "color": "black"
  }
}
```

`type` defines what goes into `details`. Modeling this into Rust:

```rust
pub struct Entity {
  pub id: u64,
  pub desc: String,
  pub details: EntityDetails,
}

pub enum EntityDetails {
  #[serde(rename = "animal")]
  Animal {
    limbs: u64,
    color: String,
  },
  // etc
}
```

It seems there is no way to ser/de the above without writing a custom serializer/deserializer. Is there an easy way out? Or does serde need some extension to do this naturally?

**Comment by dtolnay** [comment]
I don't think there is an easy way out currently. This will fall under the flatten attribute in https://github.com/serde-rs/serde/issues/119.

```rust
#[derive(Serialize, Deserialize)]
struct Entity {
    id: u64,
    desc: String,
    #[serde(flatten)]
    details: EntityDetails,
}

#[derive(Serialize, Deserialize)]
#[serde(tag = "type", content = "details")]
#[serde(rename_all = "lowercase")]
enum EntityDetails {
    Animal {
        limbs: u64,
        color: String,
    },
    // etc
}
```

**Comment by alkis** [comment]
Indeed the flatten attribute will make this work!

**Comment by inv2004** [comment]
Hello,
Is it possible to have duplicate of the "type" field in Entity structure? Because serde raises that missing user "type" if it was used in two places.

Regards,
