### ISSUE TITLE
Saving pretty formatted json

### ISSUE THREAD

**Issue by glennpierce** [serde-rs/json#365]
Hi

This is probably something I am doing wrong but I can't seem to save my json in as a formatted string.

So I have my serde value object that I have been saving like

```
match file.write_all(json.as_bytes()) {
             
            Err(why) => {
                panic!("couldn't write to {}: {}", display, why.description())
            },
            Ok(_) => println!("successfully wrote to {}", display),
 }
```

This outputs with no formatting. ie like

{"connections":[{"dest":"CHANNEL1","dest_element_id":1,"source":"CHANNEL1","source_element_id":0},{"dest":"CHANNEL1","dest_element_id":2,"source":"CHANNEL1","source_element_id":1},{"dest":"CHANNEL1","dest_element_id":4,"source":"CHANNEL1","source_element_id":2},{"dest":"CHANNEL1","dest_element_id":3,"source":"CHANNEL2","source_element_id":2}], .......

It has no new lines or indents.

I have tried saving like
```

match file.write_all(serde_json::to_string_pretty(&json).unwrap().as_bytes()) { // json.as_bytes()) 
or
match serde_json::to_writer_pretty(file, &json) 

```

This produces files like

{\"connections\":[{\"dest\":\"CHANNEL1\",\"dest_element_id\":1,\"source\":\"CHANNEL1\",\"source_element_id\":0},{\"dest\":\"CHANNEL1\",\"dest_element_id\":2,\"source\":\"CHANNEL1\",\"source_element_id\":1},{\"dest\":\"CHANNEL1\",\"dest_element_id\":4,\"source\":\"CHANNEL1\",\"source_element_id\":2},{\"dest\":\"CHANNEL1\",\"dest_element_id\":3,\"source\":\"CHANNEL2\",\"source_element_id\":2}], ......

Again no formatting and it has added escape characters.

What am I doing wrong ?

Thanks

**Comment by dtolnay** [comment]
Can you share the non-working code? [It works for me.](https://play.rust-lang.org/?gist=aadb7566c66ff634f8f242b190efbf50)

```rust
#[macro_use]
extern crate serde_json;

fn main() {
    let j = json!({
        "connections": [{
            "dest": "CHANNEL1",
            "dest_element_id": 1,
            "source": "CHANNEL1",
            "source_element_id": 0,
        }]
    });
    println!("{}", serde_json::to_string_pretty(&j).unwrap());
}
```

**Comment by glennpierce** [comment]
Ah I think its because I and converting my json object to a string before writing.
Not sure why I am doing that.
