### ISSUE TITLE
Strings without quotes

### ISSUE THREAD

**Issue by twify93** [serde-rs/json#367]
Hello,
I started using serde_json 2 days ago, but I couldn't figure out why after deserializing `from_str`, returns the String with the quotes as well...

**Comment by oli-obk** [comment]
I cannot reproduce (see https://play.rust-lang.org/?gist=d38a85d3f3078c5bad40d6797fee665d&version=stable for an attempt). Can you provide an [MCVE](https://stackoverflow.com/help/mcve) please?

**Comment by twify93** [comment]
Update: Printing directly the value from an Object, causes this, but using `as_str()`, removes the quotes.

[Here](https://play.rust-lang.org/?gist=d87787579912514659d8bddfb6677071&version=stable)

**Comment by oli-obk** [comment]
Ah, that's expected. A field access on a `serde_json::Value` yields another `serde_json::Value`. If you want the types to be resolved automatically, you need to use custom structs and derives:

https://play.rust-lang.org/?gist=9e64149fe110c686619185a783e78fcc&version=nightly

**Comment by twify93** [comment]
Maybe this can be mentioned in the documentation?

**Comment by oli-obk** [comment]
I'm not sure how to change the docs. Can you explain where you'd like to see what kind of additional docs?

> Maybe this can be mentioned in the documentation?

"this" meaning...

* `Value::index` yielding another `Value`?
* typed deserialization needs `serde_derive`?
* ... something else?

**Comment by twify93** [comment]
That `A field access on a serde_json::Value yields another serde_json::Value`, meaning that if you have an Untyped Object with a string, the `String` object will be surrounded with `""`.
E.g. from the provided example of untyped:
`println!("Please call {} at the number {}", v["name"], v["phones"][0]);` doesn't says anything about the `""`
