### ISSUE TITLE
Support : new to rust and trying to handle serde_json::from_str errors

### ISSUE THREAD

**Issue by hortinstein** [serde-rs/json#370]
I have the following code:

```
    println!("{}",cp);  
    let v: Value = match serde_json::from_str(&cp){
        Result::Ok(val) => {val},
        Result::Err(err) => {panic!("Unable to get item")}
    };
```

but what I really want is on error to log a message and let v equal something that will tell me the operation was not successful so I can continue gracefully.  Any good ideas on how to do this?

The closest i got was 

```
   let v: Value = match serde_json::from_str(&cp){
        Result::Ok(val) => {val},
        Result::Err(err) => {
            format!("parsing was unsuccessful");
            serde_json::Value::Null
        }
    };
```
but i never see the message.

Thanks for your help!

**Comment by dtolnay** [comment]
Looks good so far, except that [`format!`](https://doc.rust-lang.org/std/macro.format.html) is for creating strings but not printing them out. Have a look at [this chapter of the book](https://doc.rust-lang.org/book/second-edition/ch02-00-guessing-game-tutorial.html) which covers how to print messages, or the [`log`](https://docs.rs/log) crate for another option.

**Comment by hortinstein** [comment]
yeah I switched to ```println!``` and that still doesn't print, but does give me a ```Null```
