### ISSUE TITLE
Deserialize JSON which uses numbers as keys

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#372]
From IRC:

> **\<Jokler>** hey, is there a simple way to deserialize json which uses numbers as keys?
> **\<Jokler>** in my case its "1", "1.5", "2", "3", "4"

@Jokler

**Comment by dtolnay** [comment]
Aside from whatever you do with Serde, you need to pick some way to represent these numbers that can be used as keys in a data structure. Plain f64 cannot be used as a HashMap or BTreeMap key.

Something like this could work, but the best approach will depend on what the rest of your code wants to do with the numbers.

```rust
extern crate serde;
extern crate serde_json;

use std::collections::BTreeMap as Map;
use std::cmp::Ordering;

use serde::de::{self, Deserialize, Deserializer};

// Number that can be used as a map key. Infinity and NaN are not allowed.
#[derive(Debug, PartialEq, PartialOrd)]
struct N(f64);

impl Eq for N {}
impl Ord for N {
    fn cmp(&self, other: &N) -> Ordering {
        match self.partial_cmp(&other) {
            Some(ord) => ord,
            None => unreachable!(),
        }
    }
}

impl<'de> Deserialize<'de> for N {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer<'de>
    {
        let s = String::deserialize(deserializer)?;
        let f = s.parse::<f64>().map_err(de::Error::custom)?;
        if f.is_finite() {
            Ok(N(f))
        } else {
            Err(de::Error::custom("N must be finite"))
        }
    }
}

fn main() {
    let j = r#" {"1":"one", "1.5":"three halves", "2":"two", "3":"three", "4":"four"} "#;
    println!("{:?}", serde_json::from_str::<Map<N, String>>(j).unwrap());
}
```

**Comment by Jokler** [comment]
I thought about it some more and came to the conclusion that it is probably better to make it a struct and rename the fields. Thanks for the help though, this helped me understand more of serde.

**Comment by schungx** [comment]
Just for whoever wants to do this, I find that you can actually declare a private _wrapper_ type to wrap the number (or some type with built-in deserialization) that you intend to use as a key but deserialize from string instead.

See this:
https://github.com/serde-rs/serde/issues/1369#issuecomment-515999542
