### ISSUE TITLE
Feature Request: Parse strings as other types

### ISSUE THREAD

**Issue by joshlf** [serde-rs/json#373]
The [GDAX API full channel](https://docs.gdax.com/#the-code-classprettyprintfullcode-channel) is a JSON API whose messages include numerical values that are for some reason encoded as strings. In order to parse these messages, I've had to implement manual parsing, but it'd be nice if there were some attribute that I could use to instruct serde_json to attempt to parse string-typed values as other types.

Example message from that API:

```json
{
    "type": "received",
    "time": "2014-11-09T08:19:27.028459Z",
    "product_id": "BTC-USD",
    "sequence": 12,
    "order_id": "dddec984-77a8-460a-b958-66f114b0de9b",
    "funds": "3000.234",
    "side": "buy",
    "order_type": "market"
}
```

**Comment by dtolnay** [comment]
The `from_str` helper from https://github.com/serde-rs/json/issues/317#issuecomment-300251188 looks like it would work for any type that implements `FromStr`. Does that cover all the types in the GDAX API full channel?

**Comment by joshlf** [comment]
Yeah, that's roughly what I've done in my implementation.

However, this gets tricky when you want to nest those fields. For example, if instead of having an `f64` field, you want it to be optional, making it an `Option<f64>` field, then the attribute isn't sufficient. I ended up writing my own type - `struct F64(f64)` - and then using `Option<F64>`. It'd be nice if instead I could just do something like:

```rust
struct Foo {
    #[serde(deserialize_string)]
    bar: Option<f64>,
}
```

**Comment by dtolnay** [comment]
Yes the interaction of `deserialize_with` and `Option` still needs to be implemented. Let's follow up in https://github.com/serde-rs/serde/issues/723.
