### ISSUE TITLE
Strange type/lifetime error with serde_json::from_value to outer and inner struct

### ISSUE THREAD

**Issue by saarw** [serde-rs/json#375]
I'm trying to run serde_json::from_value::<Outer>(value).unwrap() on structs that look as follows, but get a strange lifetime error in the compiler, is it a bug or am I doing something wrong? My structs don't have any generic parameters.

#[derive(Debug, PartialEq, Deserialize, Serialize)]
struct Inner {
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
struct Outer {
    field: Option<Inner>
}

The error I get is the following   

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'de> _IMPL_SERIALIZE_FOR_Inner::_serde::Deserialize<'de>` is not implemented for `Outer`
    |
    = help: the following implementations were found:
              <Outer as _IMPL_SERIALIZE_FOR_Inner::_serde::Deserialize<'static>>
 = note: required because of the requirements on the impl of `_IMPL_SERIALIZE_FOR_Inner::_serde::de::DeserializeOwned` for `Outer`
    = note: required by `serde_json::from_value`

**Comment by dtolnay** [comment]
I was not able to reproduce this [[playground]](https://play.rust-lang.org/?gist=dba3fb2b4852a2a67b6a2ed915f0935c). Could you share some code that reproduces the error?

**Comment by saarw** [comment]
Silly me, had a &'static str field in the Outer object, so Serialize worked but Deserialize clearly won't.
