### ISSUE TITLE
Disambiguating between the absence of a value and null is hard

### ISSUE THREAD

**Issue by chris-morgan** [serde-rs/json#376]
At present, I believe supporting the absence of a value requires `Option` (hard coded) or `#[serde(default)]`.

`Option`’s `Deserialize` implementation treats `null` as `None` and anything else as `Some(…)`.

The effect of this is that you can’t distinguish between a missing value and `null` without either (a) making a custom `Option`-like type with an additional `None` variant and using `#[serde(default)]` every time you use it; or (b) a custom deserializer.

It’d be nice to have a better way of doing this, or at the very least a canonical version of one or both of these workarounds.

**Comment by dtolnay** [comment]
I think the canonical solution to this currently is https://github.com/serde-rs/serde/issues/984#issuecomment-314143738.

**Comment by chris-morgan** [comment]
Hmm. Couldn’t find it in any docs and didn’t think to look in the serde issue tracker. Still a bit ugly, but such is life. Nonetheless, it’d be good to have such a function exported in serde_json with instructions on its use.

**Comment by dtolnay** [comment]
I agree! We are tracking this in https://github.com/serde-rs/serde/issues/1042 because it applies not only to JSON.

**Comment by chris-morgan** [comment]
OK, sounds good. Thanks.
