### ISSUE TITLE
Stop instantiating fix_position so many times

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#386]
The lambda here unfortunately seems to capture the `V` type parameter so it is instantiated lots of times. This tiny function contributes more LLVM IR than all but 5 much larger functions in https://github.com/serde-rs/json/issues/313#issuecomment-348120753. It should be instantiated only once per `R` type parameter on your deserializer.

https://github.com/serde-rs/json/blob/c5f30c3eb8f30bf7e4a15bc5b852dbdc94030a7e/src/de.rs#L259

@Rufflewind or @Coding-Doctors would you be interested in working on this?

**Comment by Mark-Simulacrum** [comment]
If we think that the lambda shouldn't function the V type parameter and be instantiated multiple times in IR, maybe this isn't really a Serde bug and more of a rustc bug; while potentially worth fixing here, it might be better to file at rust-lang/rust instead?

**Comment by dtolnay** [comment]
Seems reasonable. I can't do it right now but I will put together a self-contained repro case and report it if someone else hasn't done it by then.
