### ISSUE TITLE
Support significant whitespace

### ISSUE THREAD

**Issue by SoniEx2** [serde-rs/json#393]
I'd like for roundtripping to work with significant whitespace. More specifically, you can embed valid [whitespace](https://en.wikipedia.org/wiki/Whitespace_%28programming_language%29) in valid JSON, but "roundtripping" seems to not actually roundtrip at all.

(Alternatively, if this won't be supported, perhaps I should just embed comments as whitespace, since you don't wanna support comments because "roundtripping won't work" (even tho it already doesn't). Just execute the JSON as whitespace to get a human-readable documentation for the JSON!)

**Comment by dtolnay** [comment]
I would prefer for this to be handled by a different library. This one is geared around Serde interop (hence the name) which is concerned with data, not so much with formatting. Sort of the same distinction between the Serde-based [`toml`](https://github.com/alexcrichton/toml-rs) crate and the style-preserving [`molten`](https://github.com/LeopoldArkham/Molten) crate. These use cases have different enough requirements that a separate library would be a better fit.

**Comment by SoniEx2** [comment]
Can we have comments, then? They're basically whitespace/formatting.

**Comment by dtolnay** [comment]
Comments are not part of JSON. And if your input is not JSON, you should not expect to use a JSON parser to parse it. Check out #168 for previous discussion about comments.

If you need to parse JSON with comments, it may be better to find a JSON5 or other human-oriented JSON library and add a strict mode where it parses JSON with comments. As I understand it, commented JSON *is* valid JSON5 so it may make sense for a JSON5 library to support that. Commented JSON *is not* valid JSON so I don't plan to do it here.

**Comment by SoniEx2** [comment]
Why not add JSON5 support as a flag?

**Comment by dtolnay** [comment]
It is a different format. According to their readme "JSON5 is *not* an official successor to JSON." Why not add TOML behind a flag, which also is not a Perl clone?

**Comment by SoniEx2** [comment]
Because JSON and JSON5 share a common subset which is the entirety of JSON.

**Comment by dtolnay** [comment]
Why not add support for parsing the TypeScript language, which also shares a common subset with JSON?

I think ultimately it comes down to whether the Serde team has the bandwidth to maintain yet another format at the level of quality of current serde_json. Maintaining a production-quality JSON5 implementation is out of the question. Stashing a sloppy neglected implementation behind a flag in some un-advertised module may work, but is not a choice that reflects well on Serde or serde_json. I really believe for both JSON users and JSON5 users it will be better for JSON5 to happen somewhere else and be owned by someone who cares about it and has the time.

**Comment by SoniEx2** [comment]
Why not accept JSON5 by default and emit strict JSON by default?

Emitting JSON5 is easier than JSON but w/e.

**Comment by oli-obk** [comment]
What we could do is offer private `serde_json` APIs behind a cfg flag, so a `serde_json5` crate can reuse the code. Instead of making `serde_json` some feature-crate we could publish a `serde_json_internals` crate that does major version bumps on every change, but contains the same code just with everything public.

> Why not accept JSON5 by default and emit strict JSON by default?

It's not about configurability and defaults, it's as @dtolnay said: We (meaning @dtolnay mainly) do not have leftover capacity to support more formats, even closely related ones. Of course we don't want to hold back anyone trying to implement another format, thus my idea above.
