### ISSUE TITLE
JSON5 support

### ISSUE THREAD

**Issue by TGotwig** [serde-rs/json#394]
I'm interested in JSON5 support:
https://github.com/json5/json5

Particularly it should reduce storage of very large json files.

**Comment by dtolnay** [comment]
It is a different format, so I would prefer for this to live in a different library. This library is intended for the JSON format. Serde support for other formats like [TOML](https://github.com/alexcrichton/toml-rs) and [YAML](https://github.com/dtolnay/serde-yaml) and [CBOR](https://github.com/pyfisch/cbor) exist in other libraries.

If you are interested in helping implement JSON5 for Serde, [this chapter](https://serde.rs/data-format.html) of the documentation may be a good starting point.

**Comment by callum-oakley** [comment]
A note for people stumbling upon this issue after searching "json5 serde". I've made a start on JSON5 support for serde [here](https://github.com/callum-oakley/json5-rs). Issues / PRs very welcome. :)
