### ISSUE TITLE
Not compiled on Rust 1.5.0

### ISSUE THREAD

**Issue by Pjandro** [serde-rs/json#40]
Error:
serde_json-0.7.0/src/lib.rs:120:1: 120:19 error: use of unstable library feature 'core': the libcore library has not yet been scrutinized for stabilization in terms of structure and naming (see issue #27701)
serde_json-0.7.0/src/lib.rs:120 extern crate core;
rustc --version: rustc 1.5.0
cargo --version: cargo 0.8.0-nightly (b3273e5 2016-01-11)
Please fix this

**Comment by erickt** [comment]
Arg, I missed that getting slipped into a PR, fixing...

**Comment by erickt** [comment]
Just to check, is there a reason you're still using Rust 1.5 instead of 1.6? It would be useful to know if and when how old of a version of Rust should be supported.

**Comment by Pjandro** [comment]
On

**Comment by Pjandro** [comment]
rustc --version: rustc 1.6.0 (c30b771ad 2016-01-19)

**Comment by Pjandro** [comment]
cargo ---version: cargo 0.7.0-nightly (1af03be 2015-12-08)
All Work
