### ISSUE TITLE
[question] should serde_json re-export Serialize+Deserialize?

### ISSUE THREAD

**Issue by vitiral** [serde-rs/json#400]
I am mostly wondering if there is a real reason it doesn't export them. It seems like it would be a good idea. For instance if you had to depend on two `serde` versions, you could have access to the exact trait that `serde_json` implements (this occaisonally happens when libraries haven't updated serde in a while).

I'm not necessarily saying it would be a *good* idea to do this, I'm just wondering why it is not done.

**Comment by dtolnay** [comment]
For bridging across Serde versions I would prefer to point people to [these legacy shims](https://github.com/serde-rs/legacy). Having code in which `serde::Serialize` is different from `serde_json::Serialize` seems way more confusing than using `serde09::Serialize` and `serde1::Serialize`.

**Comment by vitiral** [comment]
that's cool, I didn't know about those.

I forgot to mention it above, but do you think there would be value in exportin `Serialize+Deserialize` so that users could remove a dependency on the `serde` crate itself if they just wanted to create a function that accepted serializable types?

**Comment by dtolnay** [comment]
Let's keep it without a re-export. A function that accepts any serializable type requires that type to be serializable to any format not just JSON, so using `serde_json::Serialize` as a trait bound would be misleading even if that trait is the same as `serde::Serialize`. I would prefer to see `serde::Serialize` and `serde::Deserialize` in trait bounds.

**Comment by vitiral** [comment]
cool, that is a reasonable choice for serde.

I feel like in general this question is up in the air though. I'm not sure what the "best practice" should be for a typical library. Thanks for your input though.
