### ISSUE TITLE
Provide a way of deserializing a string value from not-quoted string

### ISSUE THREAD

**Issue by vityafx** [serde-rs/json#419]
For example, I get a json object of `BTreeMap<String, String>` from some service:

      "rules": {
        "bot_minplayers": "10",
        "capturelimit": "8",
        "dmflags": "28",
        "fraglimit": "50",
        "g_adCaptureScoreBonus": "3",
        "g_gameState": "COUNT_DOWN",

I have created the type `GameState`:

```
/// The game state.
#[derive(Debug, Copy, Clone, Deserialize, Eq, PartialEq, Ord, PartialOrd)]
pub enum GameState {
    /// The match is in progress.
    #[serde(rename = "IN_PROGRESS")]
    InProgress,
    /// The count down has started.
    #[serde(rename = "COUNT_DOWN")]
    CountDown,
    /// The match is in pre-game state.
    #[serde(rename = "PRE_GAME")]
    PreGame,
    /// The game state is unknown.
    Unknown,
}
```

And when I try to deserialize this enum from a string it fails:

    /// Returns the game state.
    pub fn game_state(&self) -> GameState {
        use serde_json;

        if let Some(game_state) = self.rules.get("g_gameState") {
            return serde_json::from_str::<GameState>(game_state)
                .unwrap_or_else(|_| GameState::Unknown);
        }
        GameState::Unknown
    }

The result of this deserialization is `GameState::Unknown` always. To fix this I must quote the string:

    /// Returns the game state.
    pub fn game_state(&self) -> GameState {
        use serde_json;

        if let Some(game_state) = self.rules.get("g_gameState") {
            return serde_json::from_str::<GameState>(&format!("\"{}\"", game_state))
                .unwrap_or_else(|_| GameState::Unknown);
        }
        GameState::Unknown
    }

However, this is not obvious sometimes and not much friendly. I suggest fixing this by adding a trait it's and implementation for the `&str`:

```
trait QuoteStringForDeserialize {
    fn quoted(&self) -> &str {
        // returns quoted string
    }
}
```

I am just thinking about usability here.

**Comment by dtolnay** [comment]
A non-quoted string is not JSON so it is not clear that you would want to use a JSON deserializer to process it. [`serde::de::value`](https://docs.serde.rs/serde/de/value/index.html) would be more appropriate.

```rust
GameState::deserialize(game_state.as_str().into_deserializer())
    .unwrap_or_else(|_: serde::de::value::Error| GameState::Unknown)

**Comment by vityafx** [comment]
@dtolnay 
Yes, this did not come to my mind somewhy. Thanks.
