### ISSUE TITLE
Try to parse a JSON with "type" key

### ISSUE THREAD

**Issue by prisme60** [serde-rs/json#428]
Hello,

I am trying to parse a JSON like this:

```json
{
  "trains": [
    {
      "origdest": "LE HAVRE",
      "num": "3132",
      "type": "INTERCITES",
      "voie": "22",
      "heure": "21:41"
    },
    {
      "origdest": "LE HAVRE",
      "num": "3134",
      "type": "INTERCITES",
      "voie": "27",
      "heure": "22:10"
    }
  ]
}
```

but one of the key is named "type".

I define the following structures:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct JsonSncf {
    trains : Vec<TimeLineSncf>
}

#[derive(Serialize, Deserialize, Debug)]
struct TimeLineSncf {
    origdest: String, //	"LE HAVRE"
    num: String, //	"3132"
    type: String, //	"INTERCITES" <--- type is a reserved keyword of Rust language
    voie: String, //	"22"
    heure: String, //	"21:41"
}
```

The compiler give the following error: 
`error: expected identifier, found keyword `type``

The Json source is from the site (so I am not generating JSON myself ) :
[French train company : Paris Saint Lazare station](https://www.gares-sncf.com/fr/train-times/PSL/arrival)

1. My first idea is to use a workaround is to replace all "type" by another key in the JSON, but it is a kind of dirty hack.
2. Another possibility to find a way to link my struct field with "type" key of JSON.

Thanks for your support.

**Comment by dtolnay** [comment]
Check out the [rename attribute](https://stackoverflow.com/a/29118271/6086311) and [other possible attributes](https://serde.rs/attributes.html) to customize behavior of generated Serialize and Deserialize impls.

**Comment by prisme60** [comment]
Perfect, your answer is what I expected.
Thank you.
