### ISSUE TITLE
Please treat '\0' as end instead of raising error TrailingCharacters.

### ISSUE THREAD

**Issue by cathay4t** [serde-rs/json#433]
When a u8 array has \0 at the end, the Deserialize will fail with `TrailingCharacters`.
It's quit comment when json string is read from socket buffer.

Sample code:
```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Deserialize, Debug)]
struct User {
    fingerprint: String,
    location: String,
}

fn main() {
    // The type of `j` is `&[u8]`
    let j = b"{
                \"fingerprint\": \"0xF9BA143B95FF6D82\",
                \"location\": \"Menlo Park, CA\"
              }\0";

    let u: User = serde_json::from_slice(j).unwrap();
    println!("{:#?}", u);
}
```

**Comment by dtolnay** [comment]
I believe the current behavior is correct. I would prefer not to support trailing \0 because that is not a valid JSON document by the JSON grammar. I would recommend using CStr if your data is terminated by \0:

```rust
CStr::from_bytes_with_nul(b"{}\0").unwrap().to_bytes()
```

or trimming away the \0 before invoking serde_json:

```rust
"{}\0".trim_right_matches('\0')
```

**Comment by cathay4t** [comment]
Thank you. Closing issue.
