### ISSUE TITLE
Escaping forward slash

### ISSUE THREAD

**Issue by zpgaal** [serde-rs/json#435]
I'm using serde to communicate to a microsoft project. MS seems to be more strict with string escaping and I have no control over it. It requires to escape the forward slash too, but serde seems to not escaping them. As I could figure out it is completely valid json, escaping forward slash is optional. But can we turn it on somehow ?

I could implement a custom serialization for these strings (and that works) But serde has all the building blocks to handle it but they seems to be private (Ex. ony the ESCAPE table have to be altered for the serializer)

Is it possible to configure it or make the escaping "public" somehow ?

**Comment by dtolnay** [comment]
You can customize the escaping logic by plugging in your own formatter. Maybe something like:

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::io::{self, Write};
use serde::Serialize;
use serde_json::ser::Formatter;

struct EscapeSlashes;

impl Formatter for EscapeSlashes {
    fn write_string_fragment<W: ?Sized + Write>(
        &mut self,
        writer: &mut W,
        fragment: &str,
    ) -> io::Result<()> {
        writer.write_all(fragment.replace('/', "\\/").as_bytes())
    }
}

#[derive(Serialize)]
struct Zpgaal {
    s: String,
}

fn main() {
    let z = Zpgaal { s: "forward/slash".to_owned() };
    let mut out = Vec::new();
    z.serialize(&mut
        serde_json::Serializer::with_formatter(&mut out, EscapeSlashes)).unwrap();
    println!("{}", String::from_utf8(out).unwrap());
}
```
