### ISSUE TITLE
`preserve_order` changes semantics of equality on `Value`

### ISSUE THREAD

**Issue by Diggsey** [serde-rs/json#438]
Without `preserve_order` it is safe to compare two `Value`s for equality. However, with the feature enabled, two maps with the same keys may no longer compare equal:

https://contain-rs.github.io/linked-hash-map/src/linked_hash_map/lib.rs.html#760-764

This goes against the idea of cargo features being "additive", and can cause some very tricky to locate bugs...

IMO, the `Value` type should have consistent equality semantics, and you could add a wrapper type for retaining the original behaviour.

**Comment by dtolnay** [comment]
Thanks, I would accept a PR to replace [`impl PartialEq for Map<String, Value>`](https://github.com/serde-rs/json/blob/v1.0.16/src/map.rs#L230) with an order independent comparison.
