### ISSUE TITLE
Stream Deserializer not handling EOF Correctly

### ISSUE THREAD

**Issue by nixpulvis** [serde-rs/json#44]
The stream deserializer currently does not return none on the first EOF from the input stream, instead it takes two. This is related to the way the deserializer does it's peeking.

Why can't deserializer use the std `Peekable`.

``` rust
extern crate serde_json;

use serde_json::*;
use std::io::{self, Read};

fn main() {
    let stdin = io::stdin();
    let stream_deserializer: StreamDeserializer<Value, _> = StreamDeserializer::new(stdin.bytes());

    for v in stream_deserializer {
        match v {
            Ok(value) => {
                println!("{:?}", value);
            },
            Err(_) => println!("Encountered a json parsing error, closing"),
        }
    }
}
```

Running this you'll notice that it takes two control-D's to close the program.

**Comment by dtolnay** [comment]
This was fixed in #194 and released in serde_json 0.8.5.
