### ISSUE TITLE
Figure out what lenses are

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#443]
**Apparently the people want this.**

https://twitter.com/ReinH/status/983868004357177344

> This just in: working with JSON in Rust (via serde_json) is awesome. The only thing I really miss is lenses, but maybe I just don’t know the Rust idioms yet. OTOH, I wish I could use directives in Haskell for Aeson rather than writing bespoke instances so often.

https://twitter.com/leothrix/status/995023560321126400

> Even a little Haskell experience leaves you a bit spoiled, haha. I _really_ miss lenses for json introspection in other typed languages like go/rust

**Comment by dtolnay** [comment]
I think this is something a Haskeller would need to design for us. Happy to reopen if anyone is interested.

**Comment by jimmydivvy** [comment]
The Scala ecosystem is probably a good place to look for inspiration on this one if you're trying to get your head around Lenses

Circe is a JSON Library similar to Serde that implements Lenses. The documentation should hopefully give you a good overview of how that works - https://circe.github.io/circe/optics.html

It uses a library called Monocle for the actual implementation - http://julien-truffaut.github.io/Monocle/

There's also a decent Optics library in Kotlin for reference - https://arrow-kt.io/docs/optics/dsl/

Full Haskell style lenses can be quite complex to implement, but basic getter/setter style lenses are trivial and could probably be whipped up in a day or two.

**Comment by DevinR528** [comment]
Another thing that is somewhat related that may be helpful would be a `#[serde(lens = "foo.bar")] field attribute. So it would work something like this:

```rust
#[derive(Clone, Debug, Deserialize)]
pub struct Links {
    #[serde(lens = "outer.href")]
    pub link: Option<String>,
}
```

and would be capable of deserializing this

```json
{ "outer": { "href": "the.link.com"}}
```
