### ISSUE TITLE
Is there any way to customize property name?

### ISSUE THREAD

**Issue by windoze** [serde-rs/json#452]
What I asked is something like `@JsonProperty` annotation in FasterXML Jackson Java library.
If I've a struct:
```
#[derive(Serialize, Deserialize)]
struct Message {
    contents: String
}
```
The corresponding JSON will have "content" property, is there any way to change this name without change actual struct?

**Comment by dtolnay** [comment]
Yes, you could use a rename attribute on the field. https://serde.rs/attributes.html

**Comment by windoze** [comment]
Thanks, that's exactly what I needed.
