### ISSUE TITLE
Custom string deserializer no longer works with v1.0.15+

### ISSUE THREAD

**Issue by daboross** [serde-rs/json#460]
I recently tried picking up an old project of mine, and found that it no longer works. I was using several custom visitors to deserialize both strings and integers into `time::Timespec`.

This is the simplest failing deserializer:

```rust
/// Deserializes either a number or a string into a `Timespec`, interpreting both as the timespec's seconds.
pub fn deserialize<'de, D>(deserializer: D) -> Result<Timespec, D::Error>
where
    D: Deserializer<'de>,
{
    use serde::de::{Error, Unexpected, Visitor};
    use std::fmt;

    struct TimeVisitor;

    impl<'de> Visitor<'de> for TimeVisitor {
        type Value = Timespec;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("an integer or string containing an integer")
        }

        #[inline]
        fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
        where
            E: Error,
        {
            let seconds = value
                .parse()
                .map_err(|_| E::invalid_value(Unexpected::Str(value), &self))?;

            Ok(Timespec::new(seconds, 0))
        }
        #[inline]
        fn visit_i64<E>(self, value: i64) -> Result<Self::Value, E>
        where
            E: Error,
        {
            Ok(Timespec::new(value, 0))
        }

        #[inline]
        fn visit_u64<E>(self, value: u64) -> Result<Self::Value, E>
        where
            E: Error,
        {
            Ok(Timespec::new(value as i64, 0))
        }
    }

    deserializer.deserialize_i64(TimeVisitor)
}

#[test]
fn parse_string_timespec() {
    let spec = timespec_seconds::deserialize(&json!("1474674699273")).unwrap();

    assert_eq!(spec, time::Timespec::new(1474674699273i64, 0));
}

#[test]
fn parse_number_timespec() {
    let spec = timespec_seconds::deserialize(&json!(1475538699273i64)).unwrap();

    assert_eq!(spec, time::Timespec::new(1475538699273i64, 0));
}
```

In `serde-json` v1.0.14 and earlier, all of my tests and code succeeds.. In `serde-json` v1.0.15 and later, the string test fails with:

```rust
Error("invalid type: string \"1474674699273\", expected an integer or string containing an integer", line: 0, column: 0)
```

Another test involving `null` passed to a deserializer which defines `visit_none` fails with:
```rust
 Error("invalid type: null, expected an integer or string containing an integer", line: 0, column: 0)
```

Full reproducible example with the three failing deserializers at https://github.com/daboross/timespec-serde-demonstration.

I'm sure there's something wrong in my code, but I'm not sure what it is. The deserializers look alright, and "invalid type string" when my visitor defines `visit_str` seems strange. It doesn't seem like my visitor's methods are being called at all?

This codebase is not particularly important for anything, so it's not _really_ high priority, but it would be nice to know what's going on. Is there anything that could be done either in `serde_json` or in my codebase to fix this?

**Comment by daboross** [comment]
Seems most likely caused by my using `deserialize_i64` here. I'm 90% sure there was a reason I did that, but if not, I'll just close this issue.

**Comment by dtolnay** [comment]
Yes I believe `deserialize_i64` is the reason a string is not accepted. If a Deserialize impl requires type information from the input data to decide how to deserialize, it should call `deserialize_any`.

The 1.0.15 behavior of `timespec_seconds::deserialize(&json!(...))` is consistent with the following in 1.0.14 which already would have failed to deserialize:

```rust
let mut de = serde_json::Deserializer::from_str("\"1474674699273\"");
let spec = timespec_seconds::deserialize(&mut de).unwrap();
```

**Comment by daboross** [comment]
Ah cool, thanks.
