### ISSUE TITLE
Read multiple records from json file

### ISSUE THREAD

**Issue by hasanOryx** [serde-rs/json#466]
With the below code, I can read the json file and assign it to the struct member, only if it is of 1 record, 

`let u: User = serde_json::from_reader(file)?;`

How can I handle multiple records, is there a way that I can use it to read all the records at once, something like:

```
let records = xxx
for record in records {...}
```

**Comment by dtolnay** [comment]
There is, check out [`serde_json::StreamDeserializer`](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html).

**Comment by phiresky** [comment]
Just wanted to mention that this also allows parsing of jsonl files (since this information is very hard to find anywhere else)
