### ISSUE TITLE
Appending the JSON file

### ISSUE THREAD

**Issue by hasanOryx** [serde-rs/json#467]
I used the below code to add record to the JSON file:
```
 let mut json_file = std::fs::OpenOptions::new().append(true).read(true).open(json_file_path).expect("file not found");

  let age_last_year = 42;
  let random_phone = 12345678;
   let john = Person {
      name: "John Doe".to_string(),
      age: age_last_year + 1,
      phones: vec!(
                format!("+44 {}", random_phone),
                format!("+44 {}", random_phone)
            )
      };
 
   serde_json::to_writer(&json_file, &john).expect("error while writting json");  // ::to_string(&john).unwrap();
```
The result is the file amended as below:

`{"name":"John Doe","age":43,"phones":["+44 12345678","+44 12345678"]}{"name":"John Doe","age":43,"phones":["+44 12345678","+44 12345678"]}{"name":"John Doe","age":43,"phones":["+44 12345678","+44 12345678"]}{"name":"John Doe","age":43,"phones":["+44 12345678","+44 12345678"]}`

I think this is wrong, as there is no coma `,` separating the the elements from each others, which will cause a problem reading the generated file later!

**Comment by dtolnay** [comment]
JSON values are not typically separated by commas except inside of an array or object. StreamDeserializer will be able to read that file.
