### ISSUE TITLE
Working with JSON files separating data by comma 

### ISSUE THREAD

**Issue by hasanOryx** [serde-rs/json#468]
This is suggestion, hope to be considered.

I was able to read/write JSON files using `serde-json`, but the issues I've is:
1. I can not read JSON files from other sources, where the records are separated by comma `,` with  
[StreamDeserializer](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html) we I can read only the files written by `serde` or the first record only if the json file is from other sources, where records are seperated by comma.

2. The file I can write, is not separating the records by `,` so I can not use it properly in some other areas here they need the elements to be separated by comma.

Thanks

**Comment by dtolnay** [comment]
Here is how I would recommend reading and writing comma separated JSON records.
 
```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde::Serialize;
use std::error::Error;
use std::io::{self, Read, Write};

#[derive(Serialize, Deserialize, Debug)]
struct Record {
    id: u64,
}

fn main() -> Result<(), Box<Error>> {
    let input = br#"{"id":0}, {"id":1}, {"id":2}"#;
    let mut cursor = io::Cursor::new(input);

    let mut records = Vec::new();
    loop {
        match serde_json::Deserializer::from_reader(&mut cursor)
            .into_iter::<Record>()
            .next()
        {
            Some(record) => records.push(record?),
            None => break,
        }
        let mut comma = [0];
        if cursor.read(&mut comma)? < 1 {
            break;
        }
        if comma[0] != b',' {
            return Err("expected comma".into());
        }
    }

    println!("{:?}\n", records);

    let mut out = Vec::new();
    for record in records {
        record.serialize(&mut serde_json::Serializer::new(&mut out))?;
        write!(out, ",")?;
    }

    println!("{}\n", String::from_utf8(out)?);
    Ok(())
}
```
