### ISSUE TITLE
Improve syntax error messages for enums and structs

### ISSUE THREAD

**Issue by Yoric** [serde-rs/json#47]
I believe that the error messages for enums and structs can be made much more useful.

`Unknown field "foo" while parsing a`FooBar`, expected one of "a", "b", "c" (required), "d", "e", "f" (optional).`

or

`Unknown variant "foo" while parsing a`FooBar`, expected one of "a", "b", "c".`

These error messages would make it much easier to fix typos and/or locate documentation.

**Comment by dtolnay** [comment]
This has been implemented as of serde_json 0.9.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Deserialize, Debug)]
enum Yoric {
    A,
    B,
    C,
}

fn main() {
    println!("{}", serde_json::from_str::<Yoric>("\"foo\"").unwrap_err());
}
```

```
unknown variant `foo`, expected one of `A`, `B`, `C` at line 1 column 5
```
