### ISSUE TITLE
Error in reading from JSON file in serde_json version 1.0.27

### ISSUE THREAD

**Issue by addityasingh** [serde-rs/json#477]
I am getting the following error while trying to use version `1.0.27`

**Cargo.toml**
```
[dependencies]
clap = "2.26.0"
serde_json = "1.0.27"
```

>Blocking waiting for file lock on the registry index
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling serde v1.0.76
error[E0658]: use of unstable library feature 'inclusive_range_methods' (see issue #49022)
    --> /Users/adisingh/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.76/src/de/impls.rs:2084:12
     |
2084 |         Ok(RangeInclusive::new(start, end))
     |            ^^^^^^^^^^^^^^^^^^^
     |
     = help: add #![feature(inclusive_range_methods)] to the crate attributes to enable

**Comment by dtolnay** [comment]
What compiler version are you using? `rustc --version`
If you are using an old nightly compiler, we generally do not support nightlies any older than the most recent one. If you are using nightly the expectation is that you upgrade the compiler every night, or else stick to library versions from that nightly date and no newer.

**Comment by addityasingh** [comment]
Seems to be working with latest nightly

**Comment by addityasingh** [comment]
Seems to be working with latest nightly
