### ISSUE TITLE
from_value(&Value)

### ISSUE THREAD

**Issue by emilk** [serde-rs/json#483]
Currently [`from_value`](https://docs.serde.rs/serde_json/value/fn.from_value.html) consumes the value (it is passed by value). This is often desirable for performance reason, but there are cases where a signature `fn from_value<T>(value: &Value) -> Result<T, Error>` is preferred (and currently lacking).

In particular, I have a big `serde_json::Value` and I want to parse *parts of it*. Luckily I can define a `struct` with the fields I am interested in and derive `Deserialize`. The extra keys in the `Value` are ignored. However, my big `Value` is now gone, and I still want it. The only option for me is to clone the `Value` before parsing it, but that is slow as it is big. Here is an example of what I mean:

``` rust

let value = json!({
    "interesting_key": "foo",
    "one_of_thousands_of_other_keys": 42,
    …
});


#[derive(Deserialize)]
struct TheGoodParts
{
    interesting_key: String,
}

fn slow {
    let good_parts: TheGoodParts = serde_json::from_value(value.clone()); // Cloning a huge Value even though I only want to parse parts of it
    analyze_all_keys(&value);
}

fn desired {
    let good_parts: TheGoodParts = serde_json::from_value(&value); // Not currently allowed
    analyze_all_keys(&value);
}
```

**Comment by dtolnay** [comment]
I would recommend writing this as:

```rust
use serde::Deserialize;

let good_parts = TheGoodParts::deserialize(&value)?;
```

**Comment by emilk** [comment]
@dtolnay that works beautifully, thank you!

**Comment by cecton** [comment]
> Currently [`from_value`](https://docs.serde.rs/serde_json/value/fn.from_value.html) consumes the value (it is passed by value). This is often desirable for performance reason, (...)

I was wondering why this is desirable for performance reason? Is it just to free some memory? Or are there underlying mechanics that make the deserializer faster if it can consume its source object?

**Comment by dtolnay** [comment]
It means owned data in the output doesn't need to be copied from the input. For example we can deserialize from Value to a struct containing Strings without allocating memory, but deserializing the same thing from &Value means you must clone even if you immediately destroy the Value afterward.

**Comment by cecton** [comment]
@dtolnay thanks a lot for the answer, it makes totally sense now!

I do have another question if I may:

**Q:** Is there a way to deserialize to a `Value`, then deserialize one struct with part of that Value, then deserialize another struct with the rest of the Value?

Something like this:

```rust
let (good_parts: TheGoodParts, rest: Value) = serde_json::from_value(value);
// here "rest" will be the JSON with the Strings
// that have not been used to create TheGoodParts
```

A bit like you would do [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Syntax) in JS:

```javascript
const { interesting_key, ...rest } = input;
```

### Use Case

I believe @emilk and I are using serde_json using the same pattern:
1. we deserialize partially a JSON to a struct
2. we execute some logic to determine what to do next
3. we deserialize the same JSON to a different struct

```rust
let value = json!({
    "interesting_key": "foo",
    "another_interesting_key": 42,
    …
});


#[derive(Deserialize)]
struct TheGoodPart
{
    interesting_key: String,
}

#[derive(Deserialize)]
struct AnotherGoodPart
{
    another_interesting_key: i64,
}

let good_part = TheGoodPart::deserialize(&value)?;

if good_part.interesting_key == "foo" {
    let another_good_part = AnotherGoodPart::deserialize(&value)?;

    do_something_with_both(good_part, another_good_part);
}
```
