### ISSUE TITLE
map trait on Value enum

### ISSUE THREAD

**Issue by johnkarasev** [serde-rs/json#484]
Is there a map trait on the Value enum so I can do value.map(|x| (x["temp"], x["loc"])

**Comment by dtolnay** [comment]
Could you show more of your code where this would be valuable and explain the behavior?

**Comment by johnkarasev** [comment]
`    let n = match s["properties"]["periods"] {
        Value::Array(v) => v.map(|x| (x["temperature"], x["startTime"])),
        _ => panic!("no match")
    };`

**Comment by johnkarasev** [comment]
I am getting json requests that look like: 

`  {
    "detailedForecast": "Rain likely before 5am, then rain showers likely. Mostly cloudy, with a low around 59. South wind around 10 mph. Chance of precipitation is 70%.",
    "endTime": "2018-09-22T06:00:00-07:00",
    "icon": "https://api.weather.gov/icons/land/night/rain,70?size=medium",
    "isDaytime": false,
    "name": "Overnight",
    "number": 1,
    "shortForecast": "Light Rain Likely",
    "startTime": "2018-09-22T02:00:00-07:00",
    "temperature": 59,
    "temperatureTrend": null,
    "temperatureUnit": "F",
    "windDirection": "S",
    "windSpeed": "10 mph"
  },
  {
    "detailedForecast": "Rain showers likely. Partly sunny, with a high near 69. Southwest wind around 10 mph. Chance of precipitation is 60%. New rainfall amounts less than a tenth of an inch possible.",
    "endTime": "2018-09-22T18:00:00-07:00",
    "icon": "https://api.weather.gov/icons/land/day/rain_showers,60?size=medium",
    "isDaytime": true,
    "name": "Saturday",
    "number": 2,
    "shortForecast": "Rain Showers Likely",
    "startTime": "2018-09-22T06:00:00-07:00",
    "temperature": 69,
    "temperatureTrend": null,
    "temperatureUnit": "F",
    "windDirection": "SW",
    "windSpeed": "10 mph"
  },
`

I want to use map to get only temperature and maybe wind. So somthing like 
`let mapped = jsn.map(|x| x["temperature"]); `

**Comment by dtolnay** [comment]
I would recommend writing this as:

```rust
use serde::Deserialize;
use serde_derive::Deserialize;
use serde_json::Value;

const J: &str = r#"
    {
      "properties": {
        "periods": [
          { "detailedForecast": "Rain likely before 5am, then rain showers likely. Mostly cloudy, with a low around 59. South wind around 10 mph. Chance of precipitation is 70%.", "endTime": "2018-09-22T06:00:00-07:00", "icon": "https://api.weather.gov/icons/land/night/rain,70?size=medium", "isDaytime": false, "name": "Overnight", "number": 1, "shortForecast": "Light Rain Likely", "startTime": "2018-09-22T02:00:00-07:00", "temperature": 59, "temperatureTrend": null, "temperatureUnit": "F", "windDirection": "S", "windSpeed": "10 mph" },
          { "detailedForecast": "Rain showers likely. Partly sunny, with a high near 69. Southwest wind around 10 mph. Chance of precipitation is 60%. New rainfall amounts less than a tenth of an inch possible.", "endTime": "2018-09-22T18:00:00-07:00", "icon": "https://api.weather.gov/icons/land/day/rain_showers,60?size=medium", "isDaytime": true, "name": "Saturday", "number": 2, "shortForecast": "Rain Showers Likely", "startTime": "2018-09-22T06:00:00-07:00", "temperature": 69, "temperatureTrend": null, "temperatureUnit": "F", "windDirection": "SW", "windSpeed": "10 mph" }
        ]
      }
    }"#;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Period {
    temperature: i16,
    start_time: String,
}

fn main() -> serde_json::Result<()> {
    let s: Value = serde_json::from_str(J)?;

    let periods = Vec::<Period>::deserialize(&s["properties"]["periods"])?;
    let mapped = periods
        .into_iter()
        .map(|period| (period.temperature, period.start_time));

    for (temperature, start_time) in mapped {
        println!("temperature={} start_time={}", temperature, start_time);
    }

    Ok(())
}
```
