### ISSUE TITLE
README.md example usage of raw string literal using one character sentinels not recommended

### ISSUE THREAD

**Issue by omac777** [serde-rs/json#494]
Please change: 

let data = r#"{
                    "name": "John Doe",
                    "age": 43,
                    "phones": [
                      "+44 1234567",
                      "+44 2345678"
                    ]
                  }"#;

to 

let data = r###uselongsentinels###"{
                    "name": "otherwise this# will crap out with indecipherable compile errors Doe",
                    "age": 43,
                    "phones": [
                      "+44 1234567",
                      "+44 2345678"
                    ]
                  }"###uselongsentinels###;

**Comment by dtolnay** [comment]
I would prefer to keep this as is. You may be misunderstanding how raw strings work in Rust: https://play.rust-lang.org/?gist=5a640031a5b3517fc365e9e7b3dd071a

**Comment by omac777** [comment]
Let me clarify with compilable main.rs:

extern crate serde;
extern crate serde_json;
#[macro_use]
extern crate serde_derive;
use serde_json::{Error};
#[derive(Serialize, Deserialize, Debug)]

struct Person { password: String }

fn typed_example() -> Result<Person, Error> {
    //compile error when '#' is within the password string 
    //or any other string found in the raw literal.
   //let data = r#"{ "password": "#12345" }"#; 

   //this multi-character sentinel is less vulnerable to compile errors
   //if we decide to place 
   //other sample json files within the raw string.
   let data = r########"{ "password" : "#12345" }"########;
    let p: Person = serde_json::from_str(data)?;
    Ok(p)
}

fn main() {
    let blah = typed_example();
    println!("password:<<{:?}>>", blah);
}

There is no misinterpretation as to where we expect the raw string literal to end.  My recommendation does not apply simply with your example, but with the assumption that others are going to try other files within your json data variable.
