### ISSUE TITLE
Don't fail when parsing an escaped lone surrogate

### ISSUE THREAD

**Issue by staktrace** [serde-rs/json#495]
Recently the Spidermonkey JS engine implemented a change to JSON.stringify that emits lone unicode surrogates as escaped rather than unescaped. This causes a parsing failure with serde-json. The people behind that change feel that this should be fixed in the parsing library. See https://bugzilla.mozilla.org/show_bug.cgi?id=1496747 and https://github.com/tc39/proposal-well-formed-stringify/issues/13 for additional details. I have a test case in  https://github.com/staktrace/jsontest that demonstrates the error on all three Rust JSON parsing libraries.

**Comment by staktrace** [comment]
Sorry, I got this wrong. The suggestion was to make everything fail consistently, which already happens in serde-json.

**Comment by staktrace** [comment]
Although... one thing that would help here for my use-case would be the ability to have json-rust automatically replace these lone surrogates with the U+FFFD replacement character. This would probably be behind some sort of runtime option. My reading of the JSON syntax on JSON.org doesn't actually prohibit lone surrogate characters from being valid JSON, but Rust as a language doesn't allow them in strings. As the library that bridges these two, it might make sense to provide alternative ways to handle this incompatibility. Something to consider.

**Comment by dtolnay** [comment]
Thanks. I would prefer not to silently accept lone surrogates by replacing them with a different character. Applications that want this behavior can preprocess the JSON document before deserializing it.

**Comment by webmaster128** [comment]
+1 for erroring for lone surrogates. From https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates

> Isolated surrogate code points have no general interpretation; consequently, no character code charts or names lists are provided for this range.

So this can be considered broken data, even if can be encoded as valid JSON. It is probably best to trace down the source of this broken data.

**Comment by bnoordhuis** [comment]
I filed an issue about this with the V8 people the other day and their conclusion is that the presence of unpaired surrogates in JSON is per spec: https://bugs.chromium.org/p/v8/issues/detail?id=11193

It seems like serde_json ought to handle this somehow. I'm also not a fan of replacing it with U+FFFD. Is decoding to WTF-8 maybe an option?

I always hate it when people ask me to reopen issues but... can this issue be reopened? :-)
