### ISSUE TITLE
Deserialization fails for enums with `#[!serde(tag = "...")]` if they have maps with integer keys

### ISSUE THREAD

**Issue by ztorage** [serde-rs/json#496]
This would deserialize just fine:

```rust
#[derive(Serialize, Deserialize)]
enum Bar {
    Map(HashMap<u8, u8>),
}
```

While this will fail to deserialize (if map is not empty in the JSON):

```rust
#[derive(Serialize, Deserialize)]
#[serde(tag = "variant")]
enum Bar {
    Map(HashMap<u8, u8>),
}
```

The error is (assuming the JSON contains the key `"2"`):

```
Err(Error("invalid type: string \"2\", expected u8", line: 0, column: 0))
```

**Comment by dtolnay** [comment]
Thanks, this needs to be fixed in Serde so is being tracked in https://github.com/serde-rs/serde/issues/1183.

**Comment by piegamesde** [comment]
As the upstream issue is open, what would be a recommended workaround for this?

**Comment by jonasbb** [comment]
@piegamesde With [`serde_with = 1.5.0-alpha.2`](https://docs.rs/serde_with/1.5.0-alpha.2/serde_with/) you can write:

```rust
#[serde_as]
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "variant")]
enum Bar {
    Map(
        #[serde_as(as = "HashMap<DisplayFromStr, _>")]
        HashMap<u8, u8>
    ),
}

println!("{:?}", serde_json::from_str::<Bar>(r#"{"variant": "Map", "1": 123}"#));
```

**Comment by piegamesde** [comment]
This works, thank you. An alternative I found in the meantime is to simply change the tagging representation of the enum in question, as the bug is specifig to internally tagged enums. Obviously, this isn't always feasible though.
