### ISSUE TITLE
Intercepting/modifying serializ{er} output

### ISSUE THREAD

**Issue by arthurprs** [serde-rs/json#510]
I'm looking for a way of modifying the output a Serialize/Serializer implementation like if the original type is from another crate. More specifically, injecting extra data in the output. Consider:

```
#[derive(Serialize, Deserialize)]
struct Person {
    name: String,
    age: u8,
}

let person = Person::new();
serde_json::to_string(&person)?;
```

I'd like to get some extra fields on `Person` output, like `{"name": "Joe", "age": 55, "extra": 123}`.

What is the best way of accomplishing this (if possible)? Ideally a wrapper type of some kind.

**Comment by dtolnay** [comment]
Check out [this adapter](https://github.com/serde-rs/serde/blob/v1.0.84/serde/src/private/ser.rs#L16-L336) which we use for inserting tags into internally tagged enum variants. That one inserts `"$tag": "$variant_name"` as the first entry of the serialized representation.

**Comment by arthurprs** [comment]
Thank you! So a wrapper for the Serializer is the way to go.

**Comment by dtolnay** [comment]
Yes I believe so. If the amount of code is scary, another possibility would be to serialize Person to serde_json::Value, insert your extra fields, and serialize the Value into the output.
