### ISSUE TITLE
skip null for Value generated by json!

### ISSUE THREAD

**Issue by kahing** [serde-rs/json#513]
I know there's `#[serde(skip_serializing_if = "Option::is_none")]` but how would one do the same thing for values generated with `json!`?

**Comment by dtolnay** [comment]
If you mean serializing serde_json::Value to JSON in which entries with a null value are omitted, you could write a Serialize impl for a newtype wrapper around serde_json::Value that skips serializing the null entries.

```rust
struct SkipNulls(Value);

impl Serialize for SkipNulls {...}
```

Or if the Value is a field of a struct, a serialize_with function.

```rust
#[derive(Serialize)]
struct S {
    #[serde(serialize_with = "skip_nulls")]
    j: Value,
}

fn skip_nulls<S>(v: &Value, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{...}
```

**Comment by kahing** [comment]
How would I do that if I am inlining the json generation? ie:
```
let field: Option<String>;
let foo = json! ({
    "field": field,
});
```

**Comment by dtolnay** [comment]
You would wrap the serde_json::Value in the SkipNulls newtype.

```rust
SkipNulls(json!({
    "field": field,
})
```
