### ISSUE TITLE
Enhancement: associated functions for deserialization

### ISSUE THREAD

**Issue by jethrogb** [serde-rs/json#52]
Let me know if there is a better venue to discuss possible changes to serde.

Currently, the easiest way to do serialization is to do e.g.:

``` rust
let obj: MyType=serde_json::from_slice(&my_buf);
```

I think it would look “cleaner” if you could write it as an associated function on a type, e.g.:

``` rust
let obj=MyType::from_json_slice(&my_buf);
// cf. MyType::new()
```

There's currently the `Deserialize` trait which does this but constructing a Deserializer is very verbose. One way to implement this would be:

``` rust
trait JsonDeserialize: serde::Deserialize {
    fn from_json_slice(v: &[u8]) -> Result<Self,JsonError> {
        serde_json::from_slice(v)
    }
    // etc. for _str, _iter, _reader
}

impl<T: serde::Deserialize> JsonDeserialize for T {}
```

Thoughts?

**Comment by dtolnay** [comment]
We could even take it a step further by having the trait method itself take a trait which is implemented for &[u8], &str and Reader.

```rust
let obj = MyType::from_json(&my_buf);
```

Or is that more confusing?

**Comment by jethrogb** [comment]
I think that's a good idea. `from_json` could take an `Into<SerdeDeserializeInput>` or such.

**Comment by dtolnay** [comment]
I would like to see this explored in its own crate - implemented exactly the way you suggested.
