### ISSUE TITLE
json! macro reverses order

### ISSUE THREAD

**Issue by karasjoh000** [serde-rs/json#523]
I have this: 

```rust 
pub fn http_response_from_json(body: Value) -> HttpResponse {
	HttpResponse::Ok().json(json!({"status": "ok", "description": body}))
}
```

The http request returns the reverse: 
```json
{
    "description": {
        "deleted": {
            "email": "hello3@world.com"
        }
    },
    "status": "ok"
}
```

which is in reverse order. I dont know if this is an issue with the macro or the framework that sends this data over the network.

**Comment by dtolnay** [comment]
Consider enabling `features = ["preserve_order"]` if you care about the order of map keys. Normally maps are not sensitive to order.

**Comment by karasjoh000** [comment]
not sure how to add the feature in cargo.toml
```toml
[features]
features = ["preserve_order"]
```
this does not work

**Comment by karasjoh000** [comment]
```toml
[dependencies.serde_json]
features = ["preserve_order"]
```
this gives 
```shell
error: failed to parse manifest at `/Users/johnkarasev/capstone-backend/Cargo.toml`


Caused by:
  could not parse input as TOML

Caused by:
  duplicate key: `serde_json` for key `dependencies`
```

**Comment by dtolnay** [comment]
It should be covered in the Cargo documentation, either
&emsp;https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
or
&emsp;https://doc.rust-lang.org/cargo/reference/manifest.html.

**Comment by karasjoh000** [comment]
works!
```toml
serde_json = {version = "1.0.32", features = ["preserve_order"]}
```
```json
{
    "status": "ok",
    "description": {
        "deleted": {
            "email": "bob@world.com"
        }
    }
}
```

**Comment by neilyoung** [comment]
Sorry, this must be an actix-web issue (or a different configuration). The serialization is OK, if I call serde_json directly in order to serialize.

Please ignore.
