### ISSUE TITLE
StreamDeserializer errors on cut-off decimal numbers

### ISSUE THREAD

**Issue by 17dec** [serde-rs/json#524]
Simple example:
```rust
fn main() {
    dbg!(serde_json::Deserializer::from_slice(b"[1.").into_iter::<Vec<f64>>().next());
}
```
I'd expect that to return None or an EOF error - the array is not finished yet and the number is valid if it's followed by more digits. But instead it returns an early parse error:
```rust
serde_json::Deserializer::from_slice(b"[1.").into_iter::<Vec<f64>>().next() = Some(
    Err(
        Error("invalid number", line: 1, column: 3)
    )
)
```

(What I'm really doing is using a StreamDeserializer with a little bit of custom parsing to parse a large array of values, so my problem would also be solved with #404 )

**Comment by dtolnay** [comment]
Thanks, I would accept a PR to return an EOF error in this case.
