### ISSUE TITLE
serde_json::value::RawValue does not exist in 1.0.39

### ISSUE THREAD

**Issue by chillcaw** [serde-rs/json#529]
In the API docs there is a struct: https://docs.serde.rs/serde_json/value/struct.RawValue.html that doesn't seem to exist in version 1.0.39.

The documentation for this struct also doesn't show when I generate the docs for serde_json locally, does this mean the production API documentation for serde_json are out of date?

**Comment by dtolnay** [comment]
It should be available behind a feature:
https://docs.rs/serde_json/1.0.39/serde_json/value/struct.RawValue.html#note.

**Comment by arve0** [comment]
The feature-note is hard to discover, I missed it too, being below the example and ownership section in the [documentation](https://docs.serde.rs/serde_json/value/struct.RawValue.html). Move note above example?

**Comment by dtolnay** [comment]
Fixed, thanks for letting me know.
