### ISSUE TITLE
ObjectBuilder: Rename unwrap?

### ISSUE THREAD

**Issue by jgillich** [serde-rs/json#53]
Correct me if I'm wrong, but `ObjectBuilder::unwrap` doesn't actually `panic!()`, right? If so, I think it should be renamed to `to_value` or something like that.

**Comment by caspark** [comment]
I'd suggest `build` as the new name because it's shorter than `to_value` while being at least as clear.

**Comment by dtolnay** [comment]
:+1: for `build`. Same thing for ArrayBuilder.

**Comment by erickt** [comment]
+1 to `build`, especially since it's a builder.
