### ISSUE TITLE
Value::Null should always be able to deserialize into Option::None

### ISSUE THREAD

**Issue by stevenroose** [serde-rs/json#532]
In my opinion, when having an `Option<T>` with `T: serde::Deserialize`, it should always be possible to deserialize a `serde_json::Value::Null` into the `None` variant.

F.e. this should work:
```rust
let opt: Option<String> = serde_json::from_value(serde_json::Value::Null).unwrap();
assert_eq!(opt, None);
```

Currently I'm getting errors for this. Would it be possible to make sure this is always possible? When using structs, we can use the `#[serde(default)]` tag which, while cumbersome, can workaround this. But when not using structs, a more complex match is required.

**Comment by dtolnay** [comment]
I believe this is how serde_json already works. [Playground of the code in your comment](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ba341d5abe892016f0e3d211e55b5125)
