### ISSUE TITLE
Add to_bytes and from_bytes

### ISSUE THREAD

**Issue by pickfire** [serde-rs/json#533]
Seems weird that techempower did a bunch of extra code just to convert struct to bytes, it would be nice to have a feature parity to encode/decode from bytes as for string.

As well, I wonder why generic like `From<Bytes>` are not used for Serialization.

https://github.com/TechEmpower/FrameworkBenchmarks/pull/3752#discussion_r274387900

**Comment by dtolnay** [comment]
I think I would prefer not to build this into serde_json, but it would be possible for an external crate to provide these signatures as a convenience around the Serializer / Deserializer API exposed by serde_json.
