### ISSUE TITLE
PrettyFormatter - support Windows line endings

### ISSUE THREAD

**Issue by jonathanmcelroy** [serde-rs/json#535]
Currently when trying to pretty print JSON, it uses Unix line endings, even on Windows. It would be useful to add an option to PrettyFormatter to choose the type of line ending. I also think it would be useful to default to the platform default, so that to_writer_pretty behaves as expected on Windows.

**Comment by dtolnay** [comment]
I think I would prefer not to build this configuration into serde_json, but it would be reasonable to provide an alternative pretty formatter in a different crate for people that need this.

**Comment by sffc** [comment]
The lack of Windows support in PrettyFormatter means that re-generating JSON files causes those files to have a diff.

Is there an alternative supported yet?
