### ISSUE TITLE
treat empty string as None for Option<?>

### ISSUE THREAD

**Issue by Ryan-Git** [serde-rs/json#539]
In case of 
`
let r: Option<Any> = serde_json::from_str("").unwrap();
`
Why not return None? Currently it's an error.

I'm using actix-web, and there's an optional request body in json format. I'd like the Json<Option<MyStruct>> to return None rather than an error when the body is empty.

**Comment by dtolnay** [comment]
Thanks for the suggestion! I would prefer not to make this change. Empty is not a valid JSON document and serde_json only deserializes input that is valid JSON. It would be better if you could implement this logic in your application, by checking whether the string is empty before deserializing it.
