### ISSUE TITLE
Feature request: TryInto implementation for serde_json::Value

### ISSUE THREAD

**Issue by ghost** [serde-rs/json#547]
The [TryInto trait](https://doc.rust-lang.org/nightly/core/convert/trait.TryInto.html) allows for conversions that can fail.

Currently, there is generic casting from various values to `serde_json::Value`, but not the other way around. Since there are already the explicit `.as_f64()` casting methods, they could be used to implement the `TryInto` trait.

**Comment by dtolnay** [comment]
I think I would prefer not to provide these impls.

But fortunately serde_json::Value isn't anything special to serde_json, it is just some type with a Serialize and Deserialize impl. That means an external crate could provide an alternative Value implementation with more or different impls depending on what different people want.

**Comment by kaimast** [comment]
Whats the reasoning for not wanting to provide TryInto? That seems to be the most idiomatic way to provide the functionality requested in #385.
