### ISSUE TITLE
serde_json::ser::Formatter has no write_u128/write_i128 methods

### ISSUE THREAD

**Issue by gnuvince** [serde-rs/json#548]
The current version of serde_json (1.0.39) has no methods to format u128/i128 values.  Such support would be useful when we want to print u128/i128 values and make sure that the full value is be printed out (e.g., in a string).

```rust
struct HexFormatter;

impl serde_json::ser::Formatter for HexFormatter {
    // This is accepted
    fn write_u64<W: Write + ?Sized>(&mut self, w: &mut W, value: u64) -> std::io::Result<()> {
        write!(w, r#""0x{:016x}""#, value)
    }

    // This is invalid
    fn write_u128<W: Write + ?Sized>(&mut self, w: &mut W, value: u128) -> std::io::Result<()> {
        write!(w, r#""0x{:032x}""#, value)
    }
}
```

**Comment by gilescope** [comment]
Is this still the case? I see there's a serde_if_integer128 in the codebase...

**Comment by Neopallium** [comment]
We used u128 with `serde_json` and `jsonrpc`.  Just had to enable feature `arbitrary_precision`:

```
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
```
