### ISSUE TITLE
json_macros dropping fields

### ISSUE THREAD

**Issue by sheganinans** [serde-rs/json#55]
Hello! I have an API that is returning JSON with certain fields missing:

```JSON
{ "one":45, "two":5, "four":17 }
```

```JSON
{ "one":81, "three":35 }
```

My rust file looks something like:

```rust
#[derive(Debug, PartialEq, Serialize, Deserialize, Clone)]
pub struct JsonStruct {
  pub one: Option<usize>,
  pub two: Option<usize>,
  pub three: Option<usize>,
  pub four: Option<usize> }
```

I'm not sure if Option is the way to model missing fields, but any missing field all the fields afterwards are parsed as None. For example, when I try to parse the first example, the data returned has the fourth field parsed as None. For the second data example, I would expect the second and fourth field to be None, but the third field is also None. Great library, thanks!

**Comment by dtolnay** [comment]
I cannot reproduce this. Can you share the code you were using? Maybe we can spot the problem.

Here is what I tested:

```rust
#![feature(plugin, custom_derive)]
#![plugin(serde_macros)]

extern crate serde;
extern crate serde_json;

#[derive(Debug, PartialEq, Serialize, Deserialize, Clone)]
pub struct JsonStruct {
  pub one: Option<usize>,
  pub two: Option<usize>,
  pub three: Option<usize>,
  pub four: Option<usize> }

fn main() {
    let j = r#"{ "one":45, "two":5, "four":17 }"#;
    let s: JsonStruct = serde_json::from_str(j).unwrap();
    assert_eq!(s, JsonStruct {
        one: Some(45),
        two: Some(5),
        three: None,
        four: Some(17) });

    let j = r#"{ "one":81, "three":35 }"#;
    let s: JsonStruct = serde_json::from_str(j).unwrap();
    assert_eq!(s, JsonStruct {
        one: Some(81),
        two: None,
        three: Some(35),
        four: None });
}
```

**Comment by sheganinans** [comment]
I double checked my code, it was actually an error on my side. Thank you very much!
