### ISSUE TITLE
Index access for String

### ISSUE THREAD

**Issue by sunng87** [serde-rs/json#551]
At the moment, `get` on `Value` supports both `Array` and `Map`. It will be nice to support `String` too, for returning single char as borrowed Json String

**Comment by sunng87** [comment]
Related handlebars-rust#269

**Comment by dtolnay** [comment]
I would prefer if this could be implemented by handlebars instead. `get` returns a &Value and there is no borrowable Value corresponding to substrings of a Value::String.
