### ISSUE TITLE
Floats are serialized with unnecessary decimal place

### ISSUE THREAD

**Issue by nwoltman** [serde-rs/json#562]
With this struct definition:

```rust
#[derive(Serialize)]
struct MyStruct {
    a: f64,
    b: f64,
}
```

Instantiated like this:

```rust
MyStruct {
    a: 1.0,
    b: 1.2
}
```

`serde_json` serializes the struct like this:

```json
{
  "a": 1.0,
  "b": 1.2
}
```

But I'd expect the serialized output to be:

```json
{
  "a": 1,
  "b": 1.2
}
```

Even though the JSON that serde produces is technically valid, it's different from how most other languages serialize floats, and it's even different from how rust's built-in formatter formats floats: `format!("{}", 1.0f64)` returns `1`.

**Comment by ssokolow** [comment]
On the other hand, it *does* provide a hint to languages without implicit integer→float conversion that the value should be deserialized as a float, not an integer. Whether that's useful in a real-world context is anybody's guess though.

**Comment by nwoltman** [comment]
> it *does* provide a hint to languages without implicit integer→float conversion that the value should be deserialized as a float, not an integer.

Perhaps that is useful. Maybe there could be an option to choose how the JSON gets formatted?

**Comment by dtolnay** [comment]
This is intentional, but can be customized by providing a Formatter impl with the behavior you want.
https://docs.rs/serde_json/1.0.56/serde_json/struct.Serializer.html#method.with_formatter

**Comment by JaydenElliott** [comment]
For anyone with this problem but only want to change the behavior for one struct field, `  #[serde(serialize_with = "custom_func")]` is a good alternative to writing your own formatter

**Comment by tr3ysmith** [comment]
I guess my bigger question to this, is why is this intentional? This isn't common with web based applications. I'm running into an issue right now where I have a rust application talking to a web application and they're trying to compare their JSON payloads byte wise, and this is causing indifferences.

@dtolnay

**Comment by fawdlstty** [comment]
I have a question that How to serialize an `serde_json::Value` object and specify the number of decimal places for all floating-point types inside it?

**Comment by nyurik** [comment]
What's even more concerning is that my struct with `f64` floats whose value is `180.0` sometimes serializes to text with an extra `.0`, and sometimes without it - depending if it runs in GitHub action or on my linux laptop. This makes integration testing much harder as the values are less predictable.
