### ISSUE TITLE
Serialization can create duplicative field names which is invalid json

### ISSUE THREAD

**Issue by crmckenzie** [serde-rs/json#563]
In certain circumstances, serde_json creates an invalid json document with field names duplicated.

Consider the following code:
```rust
#[macro_use]
extern crate serde;


extern crate serde_derive;
extern crate strum;
extern crate strum_macros;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Root {
    pub operation: String,

    #[serde(flatten)]
    pub props: Properties,
}


#[derive(Clone, Debug, strum_macros::EnumString, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "operation")]
pub enum Properties {
    #[strum(serialize = "v1")]
    V1(V1Props),
    #[strum(serialize = "v2")]
    V2(V2Props),
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct V1Props {
    pub prop1: String,
    pub prop2: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct V2Props {
    pub prop2: String,
    pub prop3: String,
}

impl Default for V1Props {
    fn default() -> V1Props {
        V1Props {prop1: "fred".to_string(), prop2: "bob".to_string() }
    }
}

impl Default for V2Props {
    fn default() -> V2Props {
        V2Props{prop2: "foo".to_string(), prop3: "bob".to_string()}
    }
}

pub fn main() {
    let input = Root {
        operation: "fredbob".to_string(),
        props: Properties::V1(V1Props { prop1: "foo".to_string(), prop2: "bar".to_string()}),
    };

    let json = serde_json::to_string_pretty(&input).unwrap();

    println!("The json is: {}", json);        
}
```

The output is:
```sh
The json is: {
  "operation": "fredbob",
  "operation": "V1",
  "prop1": "foo",
  "prop2": "bar"
}
```

Notice that the "operation" field is duplicated. I would hope that serde_json would return an error describing the problem so that this gets caught at serialization time instead of later.

Thanks!

**Comment by dtolnay** [comment]
> In certain circumstances, serde_json creates an invalid json document with field names duplicated.

As far as I know, this is valid JSON. Is it specified somewhere that duplicate field names is invalid?

**Comment by crmckenzie** [comment]
Apparently it's complicated. 😜

https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object

**Comment by crmckenzie** [comment]
Historically this always created exceptions for me but apparently it's up to the serialization implementer to decide.

**Comment by shuoli84** [comment]
Met same problem today, any follow up? I think even spec allows this, it is not what user want most case. Also current impl is not symmetry, when serde_json::from_str, it raises Error("duplicate field").

**Comment by dtolnay** [comment]
I think I would prefer not to make a change here. To deduplicate keys during serialization you can write:

```rust
let v = serde_json::to_value(&data)?;
let j = serde_json::to_string(&v)?;
```

Alternatively it would be possible to make a wrapper Serializer that buffers and deduplicates keys for *any* data format.

```rust
let mut ser = serde_json::Serializer::new(&mut out);
let ser = dedup_keys::Serializer::new(&mut ser);
data.serialize(ser)?;

// or as one call:
let mut ser = serde_json::Serializer::new(&mut out);
dedup_keys::serialize(&data, &mut ser)?;
```
