### ISSUE TITLE
Deserializing internally tagged enum: error line information inaccurate

### ISSUE THREAD

**Issue by karlri** [serde-rs/json#565]
When failing to parse inner values of an internally tagged enum, the error line information points to the wrong place. The issue does not occur with externally tagged enums.

Issue submitted against serde, as I expect that it is mostly related to serde_derive, but I am submitting it here too as I don't really know where this line information is assigned or where a possible solution could be implemented.

https://github.com/serde-rs/serde/issues/1621

**Comment by dtolnay** [comment]
Thanks for the issues. I will close this in favor of https://github.com/serde-rs/serde/issues/1621.
