### ISSUE TITLE
Question: Extending errors

### ISSUE THREAD

**Issue by jamessewell** [serde-rs/json#569]
Hi,

I would like to be able to get Errors which I can convert into the following:

```javascript
{
  "results": [
    {
      "resultType": "SOME_ERROR",
      "description": "Json deserialize error: invalid value: floating point `-79.53480529785156`, expected an easting value between -180 and 180 at line 1 column 366"
    }
  ]
}
```

However this means that I need to be able send three bits of information from the error site rather than two (I need to get the standard description AND the resultType error code.

If just two are sent then I would use a `resultType` of "ERROR"

I am currently doing validation like this:

```rust
[serde(deny_unknown_fields)]
#[derive(Debug, Serialize, Deserialize)]
pub struct Coordinates {
    #[serde(deserialize_with = "easting_validator")]
    easting: f32,
    #[serde(deserialize_with = "northing_validator")]
    northing: f32,
}

fn easting_validator<'de, D>(d: D) -> Result<f32, D::Error>
where
    D: de::Deserializer<'de>,
{
    let value = f32::deserialize(d)?;

    if value < -10.0 || value > 10.0 {
        return Err(de::Error::invalid_value(
            de::Unexpected::Float(value.into()),
            &"an easting value between -180 and 180",
        ));
    }

    Ok(value)
}
```
Is there some nice way of doing this?

**Comment by singggum3b** [comment]
I'm not expert with Rust but may be you could try writing custom macro for those attribute
`#[my_error(details)]`

**Comment by dtolnay** [comment]
Hi @jamessewell, sorry that no one was able to provide more help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
