### ISSUE TITLE
Data format version

### ISSUE THREAD

**Issue by OoDeLally** [serde-rs/json#572]
Thanks for this amazing library!
Is there a builtin function to specify a version number for the data I serialize?
The idea is to fail when the data version is different from the deserializer version, preventing a compatibility issue when deserializing.
I currently use a version number:
```
{
  "version": 42,
  // other fields
}
```
and I manually read the `version` field from the root `serde_json::Value`.

This is an "ok" solution. I was wondering if there is some builtin solution I have overlooked.

**Comment by OoDeLally** [comment]
I also tried to validate the version in the deserializer's visitor function. However since I do not control the order of deserialization, it chokes on the unexpected format before checking the version number.

**Comment by dtolnay** [comment]
I would recommend deserializing in two passes, once to get the version and once to process the rest of the data if the version is right.

```rust
#[derive(Deserialize)]
struct Validate {
    version: u32,
}

#[derive(Deserialize)]
struct Data {
    /* everything else */
}

let j = /* ... */;
let v: Validate = serde_json::from_str(j)?;
if v.version != 42 {
    return ...;
}
let d: Data = serde_json::from_str(j)?;
```

**Comment by OoDeLally** [comment]
Thank you. It could be a big JSON. There a way to avoid parsing it twice?
I was successful at it because it seems like `serde_json::from_value` consumes the value.

**Comment by dtolnay** [comment]
Maybe something like this:

```rust
use serde::Deserialize;
use serde_json::Value;


let value: Value = serde_json::from_str(j)?;
let validate = Validate::deserialize(&value)?;
if validate.version != 42 {
    return ...;
}
let d = Data::deserialize(&value)?;
```
