### ISSUE TITLE
Suggestion on way to get additional values from deserialization

### ISSUE THREAD

**Issue by yagnasrinath** [serde-rs/json#574]
I am a newbie to rust. I am interested in knowing if there is a way to achieve the following:
json:

{
"a":1,
"b":2
}

struct {
a:int32,
b:int32
}

Serde json can deserialize the json to struct. But let's say I have additional fields in the json, which I want to capture into a map<string, object>, how can I achieve that?
{
"a":1,
"b":2
"c": 3
}

struct {
a:int32,
b:int32,
additional_properties:map<string, object>
}

Now when I am deserializing, I want all the fields that are not defined in the struct to be put into additional_properties map. This is useful in defining swagger client library which is forward compatible.
Please ignore my syntax errors.

**Comment by dtolnay** [comment]
This would be written as:

```rust
use serde::Deserialize;
use serde_json::Value;
use std::collections::BTreeMap;

#[derive(Deserialize, Debug)]
struct S {
    a: i32,
    b: i32,
    #[serde(flatten)]
    additional_properties: BTreeMap<String, Value>,
}
```

**Comment by yagnasrinath** [comment]
@dtolnay  Thank you very much for the prompt answer.

**Comment by yagnasrinath** [comment]
Also, is the debug trait necessary?
