### ISSUE TITLE
Question: Parsing javascript package.json

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [serde-rs/json#582]
This might be a silly question but how would one go about parsing a package.json file? There are many fields you can not expect and vice versa. I am specifically interested in getting scripts from a package.json file.

**Comment by dtolnay** [comment]
I don't know anything about package.json. Is it this? https://docs.npmjs.com/creating-a-package-json-file#example-1

If so, the scripts look like they would be:

```rust
#[derive(Deserialize)]
pub struct PackageJson {
    scripts: BTreeMap<String, String>,
}
```

**Comment by Th3Whit3Wolf** [comment]
Yes that's a great example. So all the examples I've seen with serde_json you know exactly what type of fields are going to be used when you parse the json. If you don't know what the other fields are do you parse it the same way?

**Comment by dtolnay** [comment]
Yes, you can parse the package.json in the link into the struct I showed, using serde_json::from_str.
