### ISSUE TITLE
serde_json::value::Value set_value

### ISSUE THREAD

**Issue by LucianoBestia** [serde-rs/json#583]
I found the `get()` and `get_mut()` methods on `serde_json::value::Value`.
I miss a `set_value(key, value)` method.
Now I have to write:
```rust
record["entry"] = v.clone();
```
But this is confusing. What happens if this entry does not exist? 
Does it panic? Or does it create a new entry?
Also annoyingly Clippy continues to warn me "indexing may panic".

**Comment by dtolnay** [comment]
That does the right thing. Indexing in Value does not panic. This seems like a Clippy lint being too aggressive.

**Comment by LucianoBestia** [comment]
Doesn't `set_value(key, value)` look more Rust idiomatic?
So we can chain the functions call like:
`set_value(key, value).do_something()...`
With the assignment style `record["entry"] = v.clone();` this is not possible.
