### ISSUE TITLE
Can't parse two nested list 

### ISSUE THREAD

**Issue by SharksT** [serde-rs/json#592]
I'm trying to parse this file  https://jsoneditoronline.org/?id=a95b73e489014b679de227559944e645

But its giving me an error when it have more than one complement (the second nested list), if it have less works fine.

'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `]`", line: 1, column: 57)',

**Comment by dtolnay** [comment]
The file you shared doesn't have a column 64 on line 1. Can you share the exact file you are parsing?

**Comment by SharksT** [comment]
Link and error message updated with the exact json

**Comment by SharksT** [comment]
This is not a json problem, is something with the graphql lib (juniper). Just tested with the raw json and work perfeclty.
