### ISSUE TITLE
How to Serialize/Deserialize a fn type struct field?

### ISSUE THREAD

**Issue by manishgupta24** [serde-rs/json#593]
I have a struct like:

```
#[derive(Debug, Deserialize, Serialize)]
pub struct Message {
    // Message struct to store the content and details of
    // a Message object.
    pub uuid: Uuid,
    pub callback: fn(Value) -> Value,
    pub content: Value,
}
```

Is it possible to Serialize/Deserialize an object like this? The issue lies with the callback field because it is callable type.
The error when compiling:

> error[E0277]: the trait bound `fn(serde_json::Value) -> serde_json::Value: serde::Deserialize<'_>` is not satisfied
  --> src/message/message.rs:10:5
   |
10 |     pub callback: fn(Value) -> Value,
   |     ^^^ the trait `serde::Deserialize<'_>` is not implemented for `fn(serde_json::Value) -> serde_json::Value`
   |
   = note: required by `serde::de::SeqAccess::next_element`
error[E0277]: the trait bound `fn(serde_json::Value) -> serde_json::Value: serde::Deserialize<'_>` is not satisfied
  --> src/message/message.rs:10:5
   |
10 |     pub callback: fn(Value) -> Value,
   |     ^^^ the trait `serde::Deserialize<'_>` is not implemented for `fn(serde_json::Value) -> serde_json::Value`
   |
   = note: required by `serde::de::MapAccess::next_value`
error[E0277]: the trait bound `fn(serde_json::Value) -> serde_json::Value: serde::Serialize` is not satisfied
 --> src/message/message.rs:5:30
  |
5 | #[derive(Debug, Deserialize, Serialize)]
  |                              ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `fn(serde_json::Value) -> serde_json::Value`
  |
  = note: required by `serde::ser::SerializeStruct::serialize_field`

**Comment by dtolnay** [comment]
Hi @manishgupta24, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
