### ISSUE TITLE
Iterate Nested Array

### ISSUE THREAD

**Issue by viper6277** [serde-rs/json#597]
Hey guys, I've been trying to find an answer to my problem, tried a few different ways, but the errors keep mounting, I'll try again tomorrow. I guess I'm unsure about how to convert the serde_json::value::Value to something I can iterate over, perhaps an array...

Thanks in advance. 

```rust
    use serde_json::json;
    ...
    ...
    ...

    let tbl_cc_data_config = json!({
        "key_name": "__main__",
        "fields": [
            {"Field Name": "cc_id", "Type": "VARCHAR", "Length": 36, "Constraint": "PKEY"},
            {"Field Name": "user_id", "Type": "VARCHAR", "Length": 36, "Constraint": "None"},
            {"Field Name": "user_name", "Type": "VARCHAR", "Length": 50, "Constraint": "None"}
        ]        
    });

    let table_name = &tbl_cc_data_config["table_name"];

    // Works !!!
    println!("Table Name: {}\n", table_name);

    let fields_list = &tbl_cc_data_config["fields"];

    // Works !!!
    println!("{}\n", fields_list[0]["Type"]);
   
    // Fails from here on...
    let fields_iter = fields_list.as_object();

    for (k, v) in fields_iter.iter() {
        println!("{:?} {:?}", k, v);
    }
```

**Comment by jonasbb** [comment]
`Value` has a method [`as_array`](https://docs.rs/serde_json/1.0.48/serde_json/value/enum.Value.html#method.as_array), which you can use to iterate over the content. You need to unwrap the option first though.

This snippet iterates over all objects in the array and for each object prints all the fields:
```rust
    for obj in fields_list.as_array().unwrap() {
        let fields_iter = obj.as_object().unwrap();
    
        for (k, v) in fields_iter.iter() {
            println!("{:?} {:?}", k, v);
        }
    }
```

**Comment by dtolnay** [comment]
Hi @viper6277, sorry that no one was able to provide more help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
