### ISSUE TITLE
Remove escape_bytes in 0.8.0

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#60]
I don't see a reason that this was part of the public API in the first place. GitHub search does not show any callers. The implementation has never been remotely correct (it is somewhat better as of #58 but still can produce invalid JSON).

This would be a breaking change.

**Comment by raphlinus** [comment]
+1 from me on this, see discussion in #51.

**Comment by erickt** [comment]
@dtolnay: +1. We can remove it. I don't think I did that intentionally.

**Comment by erickt** [comment]
@dtolnay: Now that the enum variant change landed, the breaking change window is now open. Want to land this?

**Comment by dtolnay** [comment]
Yes I'll take care of it. I already have [this guy](https://github.com/serde-rs/json/pull/88) on an 0.8.0-rc branch so I will merge that in as well.
