### ISSUE TITLE
Add object creation syntax sugar to the macro.

### ISSUE THREAD

**Issue by XAMPPRocky** [serde-rs/json#601]
It would be nice if the `json!` macro had the same syntax present in Rust and JavaScript, namely that you can initialised a object like the following `{ foo, bar, baz }` which is expanded to `{ "foo": foo, "bar": bar, "baz": baz }`.

For writing one off JSON objects that don't require strict validation it can be quite annoying to have `serde_json::json!({ "foo": foo, "bar": bar, "baz": baz })` for each. This should be possible to implement in the macro, though I don't know enough about the current `json_internal` macro to know how difficult it would be.

#### Current
```rust
serde_json::json!({ "foo": foo, "bar": bar, "baz": baz })
```
#### Proposed
```rust
serde_json::json!({ foo, bar, baz })
```

**Comment by dtolnay** [comment]
I think I would prefer not to build this into serde_json; but it would be possible to create a separate crate with a more flexible `json!` macro.

**Comment by XAMPPRocky** [comment]
Well I don't think I would ever spend time making an entirely new macro just for syntax sugar but thanks for considering.
