### ISSUE TITLE
Custom handling of Enum with empty variant

### ISSUE THREAD

**Issue by realcr** [serde-rs/json#602]
I am trying to bridge between a rust binary and a Flutter (dart) app using json, but I have issues with the case of empty variants in Enums.

I have a few enums in my Rust code that contain variants without anything inside them.
The following example shows two types of such variants I could think of (Unit2 has an actual unit `()` inside of it).

```rust
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
enum ExampleEnum {
    Unit1,
    Unit2(())
}
```

This is the code I use to serialize the enum:

```rust
fn main() {
    let ser_str = serde_json::to_string_pretty(&ExampleEnum::Unit1).unwrap();
    println!("{}", ser_str);
    let ser_str = serde_json::to_string_pretty(&ExampleEnum::Unit2).unwrap();
    println!("{}", ser_str);
}
```
Output:

```bash
"Unit1"
```
```bash
{
  "Unit2": null
}
```

Unfortunately, my code on the dart side (After managing to introduce sum-types there) expects to get something like this:
```
{"unit": {}}
```
**I was wondering if there is any hope for me to convince `serde_json` to produce this kind of output.**

## Thoughts about {}

The first time I have seen the above representation (the one with the `{}`) I thought it was somewhat strange, but a few hours later I began to think it might be an interesting idea after all.

The first representation of `Unit1`, as serialized from the `serde_json`, is not very natual in my opinion because it is very different from the representation of any other variant that contains a type.

The second representation of `Unit2` has `null`, which is indistinguishable from a variant with `Option`. In other words:

```rust
enum MyEnum {
    Unit3(Option)
}
```
will serialize into:
```bash
{
  "Unit3": null
}
```
just like `Unit2`.

**Comment by frol** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ba19ea6cadc367ad804f594f56049ff0

```rust
use serde::{Serialize, Deserialize};
use serde_json;

#[derive(Debug, Serialize, Deserialize)]
enum Enum {
    A,
    B {},
}

fn main() {
    println!("{}", serde_json::to_string(&Enum::A).unwrap());
    println!("{}", serde_json::to_string(&Enum::B {}).unwrap());
}
```

This produces the output:

```json
"A"
{"B":{}}
```

So, you should be fine with using `B {}` enum variant.

In my case, however, I would like to keep my structures sane (without useless `(())` or `{}`), but produce the `{"B": null}` or `{"B": {}}` output since I have a list of enum variants and it is very annoying to see a string or an object like:

```rust
use serde::{Serialize, Deserialize};
use serde_json;

#[derive(Debug, Serialize, Deserialize)]
struct Struct {
    i: i32,
}

#[derive(Debug, Serialize, Deserialize)]
enum Enum {
    A,
    B {},
    C(Struct),
}

fn main() {
    println!("{}", serde_json::to_string_pretty(&vec![Enum::A, Enum::B {}, Enum::C(Struct { i:1})]).unwrap());
}
```

```json
[
  "A",
  {
    "B": {}
  },
  {
    "C": {
      "i": 1
    }
  }
]
```

Notice the "A" element of the array.

**Comment by realcr** [comment]
Thanks @frol!, never thought of using `B {}` !
For future readers who might want to be able to use json interface between Rust and Dart, I made `built_union`. See:
- https://github.com/freedomlayer/built_union.dart
- https://github.com/google/built_value.dart/issues/395
