### ISSUE TITLE
Status of float roundtrips? (noticing deviations stemming from parsing)

### ISSUE THREAD

**Issue by bluenote10** [serde-rs/json#604]
I have JSON data generated by JavaScript (node). Thus, all containing float values should be valid IEEE 754 double precision literals. However, a parse + write roundtrip through serde_json leads to modified data.

#128 has been closed with the info that there will be a follow-up issue to track, but I couldn't find it, and the conversation is locked. I'm wondering what is the current status of float roundtrips. I'm noticing surprising effects:

```rust
// To verify that 117.63331139400017 is a literal that can be fully represented.
let x_val = 117.63331139400017;
let x_str = x_val.to_string();
println!("{} == {}", x_val, x_str);

// serialization => deserialization roundtrip
let x_parsed: f64 = serde_json::from_str(&json!(x_val).to_string()).unwrap();
println!("{} == {}", x_val, x_parsed);

// It looks like it is actually the deserialization:
println!("117.63331139400017 == {:?}", serde_json::from_str::<f64>("117.63331139400017").unwrap());
```
Output:
```
117.63331139400017 == 117.63331139400017
117.63331139400017 == 117.63331139400016
117.63331139400017 == 117.63331139400016
```

Tested with latest version (1.0.44) of serde_json.

**Comment by dtolnay** [comment]
This is tracked in #536.

**Comment by dtolnay** [comment]
If you need parse + write roundtrip to preserve full precision, consider enabling the arbitrary_precision feature and using serde_json::Number instead of f64.

```toml
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
```

**Comment by bluenote10** [comment]
Thanks, that helps a lot!

I noticed that this doesn't work in general though, in particular the example I gave above also fails with `arbitrary_precision` feature flag enabled. The reason seems to be that parsing behaves differently when going straight to `f64` compared to taking a detour through `Value`, which could lead to tricky bugs:

```rust
println!("117.63331139400017 == {:?}", 
    serde_json::from_str::<f64>("117.63331139400017").unwrap());
println!("117.63331139400017 == {:?}", 
    serde_json::from_str::<serde_json::Value>("117.63331139400017").unwrap());
```
Output:
```
117.63331139400017 == 117.63331139400016
117.63331139400017 == Number(117.63331139400017)
```
