### ISSUE TITLE
cannot compile serde_json 1.0.45

### ISSUE THREAD

**Issue by Kilerd** [serde-rs/json#612]
```
   Compiling serde_json v1.0.45
error[E0405]: cannot find trait `StdError` in module `serde::de`
   --> /Users/xin/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.45/src/error.rs:317:17
    |
317 | impl serde::de::StdError for Error {
    |                 ^^^^^^^^ not found in `serde::de`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0405`.
error: could not compile `serde_json`.
```

toolchain 
```
active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.40.0 (73528e339 2019-12-16)
```

**Comment by jebrosen** [comment]
It looks like `serde_json` now depends on `serde` => `1.0.100`, which isn't reflected in `Cargo.toml`.

**Comment by Kilerd** [comment]
yep, it seems dependency `serde` is not updated to latest version.

**Comment by Alexhuszagh** [comment]
You can fix this by running `cargo update` to update all dependencies. This happens when serde-json is added as a new dependency, and the existing serde isn't new enough. Ideally, this shouldn't happen, but managing old version dependencies can be hard with as many moving parts as serde has.
