### ISSUE TITLE
Breaking API change in Minor Version

### ISSUE THREAD

**Issue by cetra3** [serde-rs/json#615]
Just documenting it here, but I'm trying to use `jmespath` which relies on `serde_json::error::ErrorCode` which was public, but is no longer public.

This was made private in version `1.0.45`, due to this commit:  https://github.com/serde-rs/json/commit/97f87f2587037dcd50b9504815ee1f1540b1c2b8

Regardless of whether this is hidden in the documentation or not it is a breaking change to adjust the visibility of these structs/enums and should strictly require a major version release if following semver.  I understand that it was never meant to be public & this is a weird situation but unfortunately this will probably break other crates.

Here is the error I'm getting:

```
error[E0603]: enum `ErrorCode` is private
 --> /home/cetra/.cargo/registry/src/github.com-1ecc6299db9ec823/jmespath-0.2.0/src/variable.rs:9:32
  |
9 | use serde_json::error::{Error, ErrorCode};
  |                                ^^^^^^^^^
```

```
error[E0624]: method `syntax` is private
    --> /home/cetra/.cargo/registry/src/github.com-1ecc6299db9ec823/jmespath-0.2.0/src/variable.rs:1205:29
     |
1205 |             _ => return Err(Error::syntax(ErrorCode::KeyMustBeAString, 0, 0)),
     |                             ^^^^^^^^^^^^^
```

I believe releasing a 2.0 should've been appropriate here, but understand there is a huge aversion to major release numbers in the ecosystem.

My fix has been to hardset the minor release in Cargo.toml:

```
serde_json = "=1.0.44"
```

**Comment by dtolnay** [comment]
This is a bug in jmespath for relying on internal APIs that are clearly not public.

**Comment by cetra3** [comment]
Just documenting here in case someone else runs into it.
