### ISSUE TITLE
Are from_value(value) and from_str(&value.to_string()) equivalent?

### ISSUE THREAD

**Issue by Hirrolot** [serde-rs/json#618]
Will `serde_json::from_value(value)` and `serde_json::from_str(&value.to_string())` always produce the same result, where `value` is `serde_json::Value`?

I have code that discards it, but it uses a numerous amount of user-defined `Deserialize` types. Should I try to make MRE?

**Comment by dtolnay** [comment]
They are supposed to do the same thing, but the current implementation is based on totally separate Deserializer impls for those two input types so there could be inconsistencies. Could you put together a MRE if you've found an inconsistency?

**Comment by Hirrolot** [comment]
Here is MRE: https://hastebin.com/zoqucusolo.php.
Is it my mistake or one's of those crates?

**Comment by dtolnay** [comment]
Ah I see, deserializing from `Value` isn't going to give you borrowed strings because the entire input `Value` is destroyed before from_value returns, so none of those string references would be valid to hold on to. You would need to use visit_str for strings that get destroyed.

**Comment by Hirrolot** [comment]
Thank you!
