### ISSUE TITLE
Improve ergonomics: ToValue, impl FromStr, ToString

### ISSUE THREAD

**Issue by s-panferov** [serde-rs/json#62]
Recently I've moved my projects to Serde and I found it amazing, but it has several inconveniences:

1. `FromStr` trait is not implemented for `Value`, so I can't use `str.parse()`
2. rustc-serialize has [`ToJson`](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/trait.ToJson.html) trait which improves ergonomics a lot.
3. ToString is not implemented for `Value`.

I've made several pull requests:

1. #64 - create and impl ToJson trait
2. #63 - impl Display and FromStr traits

I believe that this will improve ergonomics. This will also improve compatibility with `rustc-serialize` and simplify migration.

**Comment by dtolnay** [comment]
Your two PRs have merged and I filed #71 to track ToString.
