### ISSUE TITLE
Question: Is it possible to optin or optout when deserializing to use the default values ?

### ISSUE THREAD

**Issue by patrickelectric** [serde-rs/json#624]
I have a json string that have missing fields, but I would like to reject it in some cases and accept in others. is it possible ?
If I use `serde(default)` it always accept the input and create a struct with the default values, but I would like to have control over it somehow, to populate with the default values or fail.

**Comment by fegies** [comment]
You could try implement a custom Deserializer for your type that performs what you want.
https://serde.rs/deserialize-map.html might be helpful.

**Comment by dtolnay** [comment]
Hi @patrickelectric, sorry that no one was able to provide more help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
