### ISSUE TITLE
Serialize embedded JSON string

### ISSUE THREAD

**Issue by sayden** [serde-rs/json#626]
Hi, I just have a question about how to embed a JSON structure into a known struct. Let's say I have the following code https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc6c0b9f2ce51f236311ac82441bb565:
```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
struct MyStruct {
    data: String //I have tried with Vec<u8> too
}


fn main(){
    let data = r#"{"hello":"world"}"#.to_string();
    let my_s = MyStruct { data };

    println!("{}", serde_json::to_string_pretty(&my_s).unwrap())
}
```

Which produces:
```json
{
  "data": "{\"hello\":\"world\"}"
}
```

What I'm trying to achieve is that the output do not escape quotes on the `data` field:

```json
{
  "data": {
    "hello": "world"
  }
}
```
I have seen in the docs the explanation around using `as_str()` or avoid the use of `Value` (I cannot use `Value` because the embedded JSON structure is always unknown). I somehow understand the explanation and I feel like the library does what's expected from but I simply can't wrap my head around to achieve what I need.

I also tried write a custom Serializer like this https://serde.rs/impl-serialize.html achieving the same result. With some rework, I can change the type of `data` to a different value if that's necessary too.

Any help is appreciated. Thanks!

**Comment by dtolnay** [comment]
> I cannot use `Value` because the embedded JSON structure is always unknown

Can you clarify what you mean by this? `Value` is for JSON data where the structure is unknown.

**Comment by sayden** [comment]
Ooops, my bad. `Value` actually works, I think I got mislead with this sentence in README.md:

> Printing as a plain string without quotation marks involves converting from a JSON string to a Rust string with as_str() or avoiding the use of Value as described in the following section.

Not saying that the sentence is wrong, just that I understood "to avoid quotes, convert with `as_str() or use a specific struct"

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc6c0b9f2ce51f236311ac82441bb565

```rust
extern crate serde_json;
extern crate serde;
use serde::{Deserialize, Serialize};
use serde_json::Value; 

#[derive(Serialize, Deserialize)]
struct MyStruct {
    data: Value
}


fn main(){
    let data = r#"{"hello":"world"}"#.to_string();
    let my_s = MyStruct { data: serde_json::from_str(data.as_str()).unwrap() };

    println!("{}", serde_json::to_string_pretty(&my_s).unwrap())
}
```

Thank you very much!
