### ISSUE TITLE
decimal control during serde_json::to_string()

### ISSUE THREAD

**Issue by xudesheng** [serde-rs/json#629]
when I convert a JSON object into string for MQTT transmission, I can't find a proper way to control decimals.
`
"temperature":20.50000000000002
`
I expect the result can be:
`
"temperature":20.50
`
if I specific 2 decimals.

is there a way to control this during "to_string()"?

**Comment by dtolnay** [comment]
There is no way to make serde serialize a different float value than what the data contains, but if the data really contains 20.5f64 then it should be getting serialized as `20.5`. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7b0dddfc0e1b3f58fdc09c2fd60da475)

You can get less precision by switching to f32 though. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9c54fcdb81b509a6aa1141f91d73265b).

**Comment by xudesheng** [comment]
> There is no way to make serde serialize a different float value than what the data contains, but if the data really contains 20.5f64 then it should be getting serialized as `20.5`. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7b0dddfc0e1b3f58fdc09c2fd60da475)
> 
> You can get less precision by switching to f32 though. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9c54fcdb81b509a6aa1141f91d73265b).

thank you! It helps.
