### ISSUE TITLE
Zero-copy deserialization - support deserializing slices as tuples (offset, length)

### ISSUE THREAD

**Issue by Pand9** [serde-rs/json#636]
My use-case is deserializing JSON without copy, from static buffer, and then using the results later on. Rust doesn't support moving self-referencing structs, so I can't deserialize strings as slices, I think. A natural choice is to keep deserialization results as pairs of (offset, length).

Basically, whenever serve sees my type "RelativeSlice { offset: u64, length: u64}" in the model, I want it to expect "str" in JSON and deserialize that. What is the best way to define such deserialization in serde_json?

**Comment by Plecra** [comment]
This is how I'd do it:

```rust
use serde::*;

#[derive(Debug)]
struct RelativeSlice {
    offset: usize,
    length: usize,
}

fn to_relative(s: &str, inside: &str) -> Option<RelativeSlice> {
    (s.as_ptr() as usize)
        .checked_sub(inside.as_ptr() as usize)
        .map(|offset| RelativeSlice {
            offset,
            length: s.len(),
        })
}

#[derive(Deserialize)]
struct Data<'a> {
    foo: &'a str,
}

#[derive(Debug)]
struct Structure {
    source: &'static str,
    foo_place: RelativeSlice,
}

fn main() {
    let json = r#"{
        "foo": "bar"
    }"#;

    let value = Structure {
        foo_place: to_relative(serde_json::from_str::<Data>(json).unwrap().foo, json).unwrap(),
        source: json,
    };
}
```

While a `DeserializeSeed` *could* make this more internal, it'd be tedious to write, and wouldn't earn its' keep. The `to_relative` conversion costs just about nothing, so don't worry about it.

**Comment by dtolnay** [comment]
Hi @Pand9, sorry that no one was able to provide more help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
