### ISSUE TITLE
Extend Map's trait implementations to any value type instead of only Value

### ISSUE THREAD

**Issue by jplatte** [serde-rs/json#645]
Hi! I'd like to know whether a PR would be welcome that extends the trait implementations of `Map` to `Map<String, T>` instead of just `Map<String, Value>`, so for example

```diff
-impl<'de> Deserialize<'de> for Map<String, Value> { … }
+impl<'de, T> Deserialize<'de> for Map<String, T>
+where
+    T: Deserialize<'de>,
+{ … }
```

**Comment by dtolnay** [comment]
You would need to expand on the use case a bit more. Why do you need this?

**Comment by jplatte** [comment]
Currently, when I want to deserialize a JSON object with arbitrary data, the obvious choice (for me) is `Map<String, Value>` since that's what `Value` uses as the object representation. Now if I want to deserialize a JSON object with arbitrary keys but a fixed value type, I suddenly have to choose a different map type, and it's not obvious which would be best / there's no easy way to use the same underlying map type as `serde_json::Map`, since the underlying map type for `serde_json` could be changed by other crates in the dependency chain through the `preserve_order` field.

**Comment by dtolnay** [comment]
Got it. I would prefer not to make this change. In your use case it doesn't sound like there is any reason it needs to match the same choice of map that Value uses, any other map would work fine. I would prefer to stick with serde_json::Map only meaning an arbitrary json object.

**Comment by jplatte** [comment]
Yeah, it's not like I have a strong requirement for this feature, just that I was kind of already expecting it to work and then found it didn't. I will stop using `serde_json::Map` directly then and select one of its underlying representations (probably the `std` one).
