### ISSUE TITLE
StreamDeserializer enters a busy-loop for malformed input

### ISSUE THREAD

**Issue by matklad** [serde-rs/json#647]
See the test in

https://github.com/oli-obk/cargo_metadata/pull/106/commits/ea84dc353dc4367c507eec0f4fd1f73892cf4d28

There, the `for message in stream_deserilizer` loop loops infinitelly, because serde repeteadly tries to parse the same invalid portion of input. 

I *think* the correct behavior here is to "poison" the Iterator after the first error and return `None`. I can also imagine some error-recovey strategy (like skipping to the next utf8 codepoint), but poisoning seems more reliable to me.

**Comment by dtolnay** [comment]
Fixed in 1.0.51.
