### ISSUE TITLE
serde_json breaks type inference of user code in some cases

### ISSUE THREAD

**Issue by acanthite** [serde-rs/json#651]
I'm not sure whether this is serde_json's issue or rustc's. If you think this is not related tho this repo, but rather a bug in rustc, file it to them or tell me and I'll do this.

OK, now the issue. This code does not compile unless the first line is removed:
```rust
use serde_json;

#[cfg(test)]
mod test {
    #[test]
    fn into_iter() {
        assert_eq!(10, vec![1, 2, 3, 4].iter().sum());
    }
}
```
The problem is that compiler cannot infer types for `sum()`. However, removing or putting the `use serde_json;` into a comment makes it compile.
The problem is even more strange as it brakes similar code in other modules of the same package.

I made a demo [repo](https://github.com/acanthite/serde_json-breaks-type-inference) that shows the problem.
It brakes only with_serde json. At least importing `serde` and `failure` does not brake it.

**Comment by acanthite** [comment]
I managed to localize the issue in serde_json. This macro  expansion causes it: [src/value/partial_eq.rs#L90](https://github.com/serde-rs/json/blob/f77c84dd3df7fe4db8932d62d8b3b7c440417dda/src/value/partial_eq.rs#L90).
Without this macro expansion inference works. 
If I understand correctly, rustc cannot figure what I want to compare in the `assert_eq`, because the `partialeq_numeric` makes the primitives all equatable to `Value`. And this makes 

I can see that the macro is used only in tests. The main library compiles fine, without this. 
But it cannot be moved into tests because of the rust's orphan rules for trait implementations. Neither #[cfg(test)] will work. Because the tests module implemented as a separate crate (very strange as for me, why not in the same carte?), and uses serde_json as a regular dependency. Which builds as regular depndency and throws all of the #[cfg(test)] code.

**Comment by dtolnay** [comment]
Thanks for the report -- I'll close this in favor of https://github.com/rust-lang/rust/issues/46257 / https://github.com/serde-rs/json/issues/380.
