### ISSUE TITLE
Deserialize duplicate json fields

### ISSUE THREAD

**Issue by ralpha** [serde-rs/json#652]
I came across the error: `Error("duplicate field `key`", line: x, column: y)`

Here is en example JSON file: ([yes this is valid json](https://stackoverflow.com/a/21833017/2037998))
```
{
    "main_node": {
          "key": "value",
          "key": "value2"
    }
}
```
Example Rust code:
```
#[derive(Serialize, Deserialize)]
struct MainNode{
    key: String,
}
```

Looking for a solution I came across this: https://github.com/serde-rs/serde/issues/690
But this does not show a solution.
I also tried a enum, but this does not work (source: https://github.com/RReverser/serde-xml-rs/issues/55 )
Using an `Vec<String>` returns a `Error("invalid type: map, expected a sequence",...)`

I tried writing my own deserialize adapter but could not get it to work.
The JSON I'm using is from a Wireshark export, so this is used in other applications.

How should I handle this case? I could not find any solution to this.

**Comment by jonasbb** [comment]
You can deserialize this with serde if you change what `main_node` deserializes too.
You could serialize it into a map, in which case serde by default has a last-key-wins strategy
```rust
#[derive(Debug, Deserialize)]
struct D {
    main_node: BTreeMap<String, String>,
}
```

or you can use the `serde_with` crate to turn it into a [first-key-wins strategy](https://docs.rs/serde_with/1.4.0/serde_with/rust/maps_first_key_wins/index.html)
```rust
#[derive(Debug, Deserialize)]
struct D {
	#[serde(with = "::serde_with::rust::maps_first_key_wins")]
    main_node: BTreeMap<String, String>,
}
```

There is also the option to deserialize it into [a list of tuples](https://docs.rs/serde_with/1.4.0/serde_with/rust/tuple_list_as_map/index.html) if you want to preserve all key-value pairs.
```rust
#[derive(Debug, Deserialize)]
struct D {
	#[serde(with = "::serde_with::rust::tuple_list_as_map")]
    main_node: Vec<(String, String)>,
}
```

If you need `MainNode` to be new type, then you won't have a choice but write your own deserialization code, either using the `#[serde(with=...)]` annotations or implementing `Deserialize` for your type.

**Comment by ralpha** [comment]
Thanks this worked perfectly. 
It is bit tricky at first because tuple_list_as_map abstract one layer way (in the tuple of course)
But works fine, both for serialization and deserialization.

Thanks a lot for the examples!

**Comment by SOF3** [comment]
Is there a solution that works on derived structs directly?
