### ISSUE TITLE
Feature request: to_raw_value

### ISSUE THREAD

**Issue by jplatte** [serde-rs/json#654]
It would be nice to have an equivalent to `to_value` for `RawValue`s, to simplify the following / skip parsing in it:

```rust
let json_string = serde_json::to_string(serializable_thing).unwrap();
RawValue::from_string(json_string).unwrap()
```

**Comment by dtolnay** [comment]
I would be prepared to accept a PR for this inside the serde_json::value module, since that is where RawValue is exposed.
