### ISSUE TITLE
Converting JSON structure into byte array using serde JSON.

### ISSUE THREAD

**Issue by aastis123** [serde-rs/json#657]
Our use case is to get JSON data structure and serialise/deserialise it to byte array. We are using no std platform for our project in rust. What is the best way to do it using serde-json?

**Comment by dtolnay** [comment]
Hi @aastis123, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.

**Comment by evbo** [comment]
@aastis123 here's how (consider handling `Result` type more gracefully rather than `unwrap`):

```rust
pub fn json_bytes<T>(structure: T) -> Vec<u8> where T: Serialize {
    let mut bytes: Vec<u8> = Vec::new();
    serde_json::to_writer(&mut bytes, &structure).unwrap();
    bytes
}
```
