### ISSUE TITLE
Deserializing property files, "a.b.c.e=value" into json

### ISSUE THREAD

**Issue by JRAndreassen** [serde-rs/json#662]
I've been battling how to do this...
It is fairly common for interfaces to dump structures into a format like
(java property files):
root.prop1.sub1.key1=val
root.prop1.sub1.key2=val
root.prop1.sub2.key2=val
...
Generically, it would be:
key0{<ksep>keyn}<minor_sep>Value<major_sep>
where 
ksep = Key separator, default '.'
minor_sep = Minor or Key/value separator, default '='
major_sep = Major or Record/entry separator, default '\n'
What would be the best way of serializing/deserializing into json using serde ?
If you have a example, I can take a crack at it...

Thanks
  JR

**Comment by dtolnay** [comment]
Hi @JRAndreassen, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
