### ISSUE TITLE
Suggestion: Improve error message for this failed parse

### ISSUE THREAD

**Issue by MrTact** [serde-rs/json#674]
[Minimal project with repro case](https://github.com/serde-rs/json/files/4648136/serde_suggestion.zip)

When attempting to parse a simple JSON file, the attached code fails with a somewhat cryptic error message:
```
serde_suggestion git:(master) ✗ cargo run
   Compiling serde_suggestion v0.1.0 (/Users/tkeating/git-repos/serde_suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/serde_suggestion`
Error: invalid type: map, expected unit at line 1 column 1
```

The problem is this line:
`let _json = serde_json::from_reader(file)?;`

This PROBABLY ought not to compile. The problem seems to be you have to give the compiler a hint as to what it should expect here:
`let _json: Value = serde_json::from_reader(file)?;`

Presumably, it is guessing, and its guess is wrong. Adding the type hint fixes it.

**Comment by dtolnay** [comment]
I think this is a compiler bug that it doesn't require you to specify the expected type of `_json`. :(

Normally it requires a type:

```rust
use std::fs::File;

fn main() {
    let file = File::open("test.json").unwrap();
    let _json = serde_json::from_reader(file).unwrap();
}
```

```console
error[E0282]: type annotations needed
 --> src/main.rs:5:9
  |
5 |     let _json = serde_json::from_reader(file).unwrap();
  |         ^^^^^ consider giving `_json` a type
```
