### ISSUE TITLE
Deserializing into remote type from Value

### ISSUE THREAD

**Issue by DarkFenX** [serde-rs/json#676]
Let me begin with saying that I am a rust newbie, so all the rust macro magic is beyond me. But, i think i've run into some kind of serde_json interface limitation (although I suppose this limitation might be lifted, and here I am asking how).

I will explain my full use-case, since there might be better ways to handle it - I am open to that. I have JSON data in following format: `{"1": {"FieldOne": "value1-1"}, "2": {"FieldOne": "value1-2"}}`. I have structs defined by an external lib, which should be filled with this data:
```
pub struct Entity {
    pub id: i32,
    pub field1: String,
}
```

My data handler has to return result in following form of struct, which contains vector of Entity structs and amount of decode errors.

How I am doing it is:

- decode json into Value
- move keys of the top-level dictionary into its values ( `{"1": {"FieldOne": "value1-1", "id": 1}, "2": {"FieldOne": "value1-2", "id": 2}}`) and return vector of the top-level dictionary's values
- decode them one-by-one into intermediate struct (while recording amount of errors I failed to process), then convert it into target struct (using `Into` trait implementation)

However, I decided to give `#[serde(remote = "")]` a shot and I am struggling with applying it to my case. I have set up following code (using example and some tickets from serde repo as example) which works for me:
```
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

mod sub {
    #[derive(Debug)]
    pub struct Token {
        pub key: String,
        pub secret: String,
    }
}


#[derive(Deserialize, Debug)]
#[serde(remote = "sub::Token")]
struct TokenDef {
        pub key: String,
        pub secret: String,
}

fn main() {
    let mut de = serde_json::Deserializer::from_str(r#"{"key":"foo","secret":"bar"}"#);
    let t = TokenDef::deserialize(&mut de).unwrap();
    // let json: serde_json::Value = serde_json::from_str(r#"{"key":"foo","secret":"bar"}"#).unwrap();
    // let t = TokenDef::deserialize().unwrap();
    println!("Token: {:?}", t);
}
```
However, what do I do if I have to decode from `Value` (commented out code)? There is no `serde_json::Deserializer::from_value` implementation, and I found no way to get that, to pass it to `deserialize()` later. Is there a way to achieve what I want without manual conversion from intermediate struct into target struct?

**Comment by dtolnay** [comment]
Looks like all you're missing is passing the argument to TokenDef::deserialize. The following would work:

```rust
let t = TokenDef::deserialize(json).unwrap();
```

**Comment by DarkFenX** [comment]
Indeed, my bad for not trying that. I tried to feed `Value` somewhere to make `Deserializer` to pass it to `deserialize()`, and did not realize that I can just pass `Value` directly. Thanks!
