### ISSUE TITLE
JavaScript BigInt support

### ISSUE THREAD

**Issue by minioin** [serde-rs/json#678]
It seems that this library supports serializing values(u64 and i64) greater than Number::MAX_SAFE_INTEGER(9007199254740991) without any error. But while accessing that value from JavaScript, the value gets truncated. Is there any way BigInt support could be added so that any value surpassing it will be labelled as BigInt.

I was able to write serializer, as it seems to be easy(just append n at the end of value). However, I wasn't able to figure out to write the deserializer as I'm a novice.

Thanks.

**Comment by dtolnay** [comment]
If I've understood correctly, you are asking about deserializing numbers with `n` suffixes as seen in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt.

That notation isn't part of JSON, so it wouldn't be something that would be deserialized using serde_json (which is focused on JSON).
