### ISSUE TITLE
Error when parsing integer - expected signed integer

### ISSUE THREAD

**Issue by cdbrkfxrpt** [serde-rs/json#681]
Here's the code in question:
```rust
        let document =
          serde_json::from_str(&fs::read_to_string(&format!("{}/{}.json",
                                                   collection_name,
                                                   document_name))?)?;
```

Both `collection_name` and `document_name` refer to text files on disk, which contain JSON formatted data serialized by `serde_json`. It works its way through what I'm throwing it at until it encounters the following JSON:

```json
{
  "uuid": "0d8f1e25-aee6-30b9-bee6-7fbd0fa93b02",
  "best": "8318e41a-8a96-3cd4-b066-17a968651981",
  "theoretical": "8318e41a-8a96-3cd4-b066-17a968651981",
  "top_speed": "6cbab7c9-8e22-3c58-a14b-707f3521a4ca",
  "results": {
    "5b2cdf84-3b97-32f8-9d20-ae288d30813c": {
      "best_laptime": 5,
```
(further content ommitted; the file is a couple thousand lines long)

At this point, it bails out with the error:

```
invalid type: integer `5`, expected a signed integer at line 8 column 23
```

Line 8 column 23 is exactly this `"best_laptime"` index - the 5 - and I can't figure out what this error even means. It's true that it is serialized from an `i32`, but that shouldn't make a difference - in between, it is (1) serialized, (2) saved to disk with a bunch of other stuff, as a pretty string (`to_string_pretty`), (3) re-read from disk into a string and (4) parsed to a JSON value (4 and 5 see above code).

It's reproducible on other files with similar content, and persists also when using `to_string` instead of `to_string_pretty`. it consistently fails upon encountering the first `"best_laptime"`, which is also the first integer value in all of these files.

**Comment by dtolnay** [comment]
Please provide a self contained minimal compilable program that reproduces this, ideally on https://play.rust-lang.org/.

**Comment by cdbrkfxrpt** [comment]
I would've if I were able to produce it with a simple example; that is kind of the whole point.

Anyway, it's probably my fault for misusing something and I can't figure out what it is yet.
