### ISSUE TITLE
MAX_SAFE_INTEGER is parsed as MAX_SAFE_INTEGER - 1

### ISSUE THREAD

**Issue by jplatte** [serde-rs/json#692]
So I've found lots of discussion about decimal places in floats not roundtripping through serde_json perfectly, but it seems like even `f64`s without decimal places don't roundtrip perfectly without the `float_roundtrip` feature.

Specifically, 9007199254740991 (or 0x001F_FFFF_FFFF_FFFF), which is the largest integer that can be encoded un-ambiguously in an `f64` (`Number.MAX_SAFE_INTEGER` in JavaScript), is parsed as 9007199254740990 with the default features.

Is this expected behaviour?

**Comment by dtolnay** [comment]
I was not able to reproduce this.

```rust
fn main() {
    println!("{}", serde_json::from_str::<f64>("9007199254740991").unwrap());
}
```

```console
9007199254740991
```

Serde_json's behavior on that input with float_roundtrip off is equivalent to `9007199254740991u64 as f64`, so if the result is wrong then it could be a compiler bug.

**Comment by jplatte** [comment]
That's... Interesting. Thanks for responding so quick! I'll check whether there's an existing report for this in the compiler, or create one if not.

**Comment by jplatte** [comment]
@dtolnay Okay, so my bug report was incomplete. I didn't try to deserialize `9007199254740991`, I tried to deserialize `9007199254740991.0`. This reliably results in `9007199254740990` being returned both on my machine and the playground. Is this expected behaviour?

**Comment by dtolnay** [comment]
Yeah in that case I think the computation is `90071992547409910_f64 / 1e1_f64`.
