### ISSUE TITLE
Feature request: Compile time errors for maps that don't have strings as keys

### ISSUE THREAD

**Issue by ckaran** [serde-rs/json#696]
I'm using serde to serialize my datastructures.  Most of my code is similar to the following (simplified for readability):

```rust
#[derive(Serialize, Deserialize)]
pub struct Thing {
    field: HashMap<u32, Datum>,
}
```

Where `Datum` has `Serialize` and `Deserialize` derived on it.

The issue is the `HashMap`.  `Serialize` and `Deserialize` are perfectly happy with non string types as keys, as are many of the encoding backends that implement the `Serializer` and `Deserializer` traits, but the JSON serializer will return a `KeyMustBeAString` error if it encounters a non-string.  Is there **any** way to make this a compile-time error?  Looking through the `serde` API, I strongly suspect that the answer is 'no', but I'm hoping that you guys are know some clever trick that will make it possible that I'm unaware of.

**Comment by dtolnay** [comment]
It seems to work: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d82bb323f3e06893fd9bf4e7df42e76a

```rust
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize, Debug)]
pub struct Thing {
    field: HashMap<u32, Datum>,
}

#[derive(Serialize, Deserialize, Debug)]
struct Datum();

fn main() {
    let mut thing = Thing {
        field: HashMap::new(),
    };
    thing.field.insert(0, Datum());

    let j = serde_json::to_string(&thing).unwrap();
    println!("{}", j);

    let thing: Thing = serde_json::from_str(&j).unwrap();
    println!("{:?}", thing);
}
```

```console
{"field":{"0":[]}}
Thing { field: {0: Datum} }
```

**Comment by ckaran** [comment]
I simplified my example that I showed you.  The real code is significantly more complex.  I just created a workaround, I'll see if I can come up with a reduced example that I can give you.

**Comment by ckaran** [comment]
I'm going to close this issue out because I haven't had time to work on it further, and if I can't provide you a minimal example of the issue I'm having, then I can't ask you to look in to it.  If I have time in the future, I'll log a better issue, with a complete example.
