### ISSUE TITLE
Readme.md has an issue

### ISSUE THREAD

**Issue by techwoes** [serde-rs/json#697]
Unless you use use 

`serde_derive::{Serialize, Deserialize};`

in the typed example and add the dependency in Cargo.toml  the "cargo build" command will fail.

**Comment by dtolnay** [comment]
I think the code is fine, and there is a "Run" link to the Rust playground that lets you confirm this:

> ![Screenshot from 2022-01-22 12-15-57](https://user-images.githubusercontent.com/1940490/150654085-2d7cfa64-f14f-4c66-88ed-7c046d16aa69.png)

<br>

The same section includes a link that explains how to set up the serde dependency:

> ![Screenshot from 2022-01-22 12-16-39](https://user-images.githubusercontent.com/1940490/150654113-447afb81-0459-442c-a3b3-1d337ba0f40a.png)
