### ISSUE TITLE
Update alt_serde_json as well🙏

### ISSUE THREAD

**Issue by jimmychu0807** [serde-rs/json#698]
@dtolnay 
Would you be so kind to update serde_json as [alt_serde_json crate](https://crates.io/crates/alt_serde_json) as well? I need the latest feature of "alloc", but needing to include the serde package as `alt_serde`. 

Thanks.

**Comment by dtolnay** [comment]
Hi @jimmychu0807, I am not an owner of that crate so I cannot publish updates to it.
