### ISSUE TITLE
GitCop experience is unfriendly to a new contributor

### ISSUE THREAD

**Issue by kamalmarhubi** [serde-rs/json#7]
I made a small doc fix PR and received a GitCop email. I have a few issues with it:

- there are no contribution guidelines in any prominent place, and the location the email pointed me to certainly had none.
- none of the commit messages by the primary author follow the format GitCop said to use, and I did check before making my commit
- the tone and wording of the email is unfriendly

This isn't a great experience for a new contributor!

**Comment by droundy** [comment]
I must say I had the same of offputting experience.

**Comment by erickt** [comment]
Hi! Sorry about that, I've been experimenting with gitcop really to remind myself to improve my commit messages. I certainly don't want you to feel unwelcome from it. I'll see if I can improve the email, and try to write up some contribution guidelines somewhere.

**Comment by kamalmarhubi** [comment]
That makes sense. Yeah if there were guidelines that would help a lot, however basic. Even if you just pointed people at the [Angular guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) to prevent the GitCop message from being a rude surprise. :-)

**Comment by erickt** [comment]
I removed gitcop, it was too obnoxious.
