### ISSUE TITLE
i128 is not supported

### ISSUE THREAD

**Issue by ddouglas87** [serde-rs/json#701]
Hi, is i128 supported?  Here is the error I'm getting:

>called `Result::unwrap()` on an `Err` value: Syntax("i128 is not supported")
>thread 'generate_qld_msgpack::tests::check_msgpack' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("i128 is not supported")', src/generate_qld_msgpack.rs:91:60

The offending code:

```
        let pyramids = open_qld(String::from("resources/stock.txt"));

        let mut buf = Vec::new();
        pyramids.serialize(&mut Serializer::new(&mut buf)).unwrap();
```

Pyramids is `Vec<Pyramid>` and within Pyramid there are fixed precision number types from the [fixed](https://crates.io/crates/fixed) crate.  These fixed decimal types are stored as an i128.

Libraries I'm using:
 - rmp-serde = "0.14.4"
 - serde = { version = "1.0.114", features = ["derive"] }
 - fixed = { version = "1.1.0", features = ["serde"] }

Is this an issue within the fixed library?

**Comment by dtolnay** [comment]
This repo is for serde_json. Since you aren't using serde_json, you would need to track down what other library you are using is producing the error. It looks like rmp-serde does not support it (https://github.com/3Hren/msgpack-rust/issues/169).

**Comment by ddouglas87** [comment]
My apologies.
