### ISSUE TITLE
Add assert or enhance check for input

### ISSUE THREAD

**Issue by VictorBulba** [serde-rs/json#706]
```rust
use serde;
use serde::Serialize;


mod serde_iter {
    use serde::ser::{Serialize, SerializeSeq, Serializer};

    pub fn serialize<S, T, V>(iter: &T, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
        T: Iterator<Item = V> + Clone,
        V: Serialize,
    {
        let mut seq = serializer.serialize_seq(Some(0))?;
        for value in iter.clone() {
            seq.serialize_element(&value)?;
        }
        seq.end()
    }
}


#[derive(Serialize)]
struct ValuesStruct<I: Iterator + Clone> where I::Item: Serialize {
    #[serde(with = "serde_iter")]
    values: I,
}


fn main() {
    let json = serde_json::to_string_pretty(&ValuesStruct{values: 0..5}).unwrap();
    println!("{}", json);
}
```

This code panic in debug because subtract overflow:

```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/bulba/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.57/src/ser.rs:2025:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In release I don't know what is happening. In this example code executing infinity period of time, but in my project (I don't know why) it produced invalid json such as:

```json
{
    "example": []
        1,
        2,
        3
    ]
}
```

but I can't reproduce it.

It is because I set invalid value `Some(0)` as a sequence len.
I think in this case method `serialize_element` shoud return error rather then panics.

**Comment by dtolnay** [comment]
> I think in this case method `serialize_element` should return error rather than panics.

Panics are supposed to be used for signalling a bug in the program, so I think a panic is appropriate in this case.

Errors are supposed to be used for expected failure conditions in a *correct* program.

**Comment by VictorBulba** [comment]
> > I think in this case method `serialize_element` should return error rather than panics.
> 
> Panics are supposed to be used for signalling a bug in the program, so I think a panic is appropriate in this case.
> 
> Errors are supposed to be used for expected failure conditions in a _correct_ program.

It panics only in debug with subtract overflow. In release it does nothing but infinity executing. I think this case requires better panic message.
