### ISSUE TITLE
to_string and fields with literal backslash

### ISSUE THREAD

**Issue by horacimacias** [serde-rs/json#709]
I'm seeing some strange behaviour when doing a to_string of a struct with String fields containing backslashes.
I was expecting to find the exact same value on the resulting to_string but looks like backslashes are escaped?

I'm running the following

```rust
#[test]
    fn test_to_string() {
        #[derive(Deserialize, Serialize)]
        struct MyStruct {
            txt: String,
        }
        const VALUE: &str = "value\\n";
        println!("VALUE is {}", VALUE);
        let m = MyStruct {
            txt: VALUE.to_string(),
        };
        assert!(m.txt.contains(VALUE));
        let s = to_string(&m).unwrap();
        println!("to_string is {}", s);
        assert!(s.contains(VALUE));
}
```

which prints
```
VALUE is value\n
to_string is {"txt":"value\\n"}
```
and test fails on `assert!(s.contains(VALUE));`

Shouldn't this test pass?
If not, is this escaping documented somewhere? I couldn't find it so far.

**Comment by dtolnay** [comment]
This is the correct behavior. Section 9 of https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf explains that a backslash character (which they call reverse solidus character but is the same thing) is escaped as `\\` inside of a JSON string.

**Comment by horacimacias** [comment]
you're absolutely right, thanks!
