### ISSUE TITLE
impl ToString for Value

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#71]

**Comment by dtolnay** [comment]
[Rustc_serialize's Json](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/enum.Json.html) does not have this. @s-panferov is this still something that you think would be valuable to you?

**Comment by s-panferov** [comment]
@dtolnay to string is already implemented in #63 because Display is implemented.

https://doc.rust-lang.org/std/string/trait.ToString.html

> This trait is automatically implemented for any type which implements the Display trait. As such, ToString shouldn't be implemented directly: Display should be implemented instead, and you get the ToString implementation for free.

**Comment by dtolnay** [comment]
Ah perfect. Thanks again for your PRs.

**Comment by s-panferov** [comment]
@dtolnay thanks for review! Now it's much easier to migrate from rustc-serialize to serde_json and even support them both because they implement common traits.
