### ISSUE TITLE
should add_f64 return an option?

### ISSUE THREAD

**Issue by jaupe** [serde-rs/json#710]
In my opinion, `as_f64` shouldn't return an `Option<f64>` as all patterns return back `Some`.

It looks like it's only returning an `Option<f64>` because of the arb. precision features; which drops the error via `ok()`.

**Comment by deeprobin** [comment]
I do not know to what extent option is necessary or not, but I would like to point out that wrapping something into an option can sometimes reduce performance.

**Comment by dtolnay** [comment]
This is intentional because JSON numbers can hold quantities that are bigger than fit into f64. See https://github.com/serde-rs/json/commit/b1ca6c718674e5d1f9f66f9cbe12b930f547fc0b.

**Comment by dtolnay** [comment]
@deeprobin: if the performance difference between f64 and Option\<f64\> is a bottleneck for your codebase then it should not be using serde_json::Value.
