### ISSUE TITLE
serde_json round-trip failure for Option<T>, where T is a zero-sized type.

### ISSUE THREAD

**Issue by BoydstonNicholas** [serde-rs/json#711]
I don't know if this qualifies as a bug or not, though it was certainly surprising behavior when I encountered it. If `T` is a zero-sized type, then both variants of `Option<T>` serialize to the same JSON value.

Example code:
```
use serde::{Deserialize, Serialize};
use serde_json::Serializer;

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
struct MarkerA;

fn main() {
    let mut serializer = Serializer::new(std::io::stdout());
    let simple1: Option<MarkerA> = None;
    let simple2: Option<MarkerA> = Some(MarkerA);
    simple1.serialize(&mut serializer).unwrap();
    println!("");
    simple2.serialize(&mut serializer).unwrap();
    println!("");
}
```

Will print:

> null
> null
 
Even though `Some(MarkerA)` is very different from `None`. This causes types containing `Option<T>` to not round trip correctly through serialization followed by deserialization when `T` is a zero-sized type. All my `Some(MarkerA)` values became None.

I ran this test using serde = "1.0.116" and serde_json = "1.0.57", and the derive feature enabled for serde.

This behavior also occurs for `Option<T>` values inside of larger structs.

This is specific to serde_json. I tried a similar program with ron = "0.6.2" and the got distinct values for `Some<MarkerA>` and `None`.

It may seem odd to use `Option<T>` with a zero-sized `T` instead of `bool` or a custom enum, but it can arise while using various kinds of library. I first encountered this while trying to serialize types from the specs ECS library.

**Comment by dtolnay** [comment]
This is intended behavior, and in general it isn't a guarantee that values round trip or that serialization is injective. If you need a different behavior, you could wrap serde_json's Serializer with a different behavior for serializing unit structs, or use a `serialize_with` attribute on the Serialize side to serialize Option<T> in a different way.
