### ISSUE TITLE
Emitting newline at end when writing JSON to file with `to_writer_pretty`

### ISSUE THREAD

**Issue by linclelinkpart5** [serde-rs/json#716]
Hello, I'm having trouble figuring out how to emit a newline at the end of a file write using `serde_json`. These JSON files I'm serializing get added to a git repo, and diff complains about the lack of newlines at the end. Not to mention, `cat`-ing these files out messes with the display.

I'd love for there to be a flag on the `*Formatter` traits to allow this, but there doesn't seem to be one. Is there an easy fix that I'm overlooking? Thanks!

**Comment by dtolnay** [comment]
I would prefer not to introduce a formatter flag for this. You could write the newline like this:

```rust
use std::io::Write;

serde_json::to_writer_pretty(&mut writer, value)?;
writer.write_all(b"\n")?;
```

**Comment by piegamesde** [comment]
I think that ending the output with a newline should be the default behavior for pretty formatting. I don't think there are many situations where one would want pretty formatting but without a trailing newline
