### ISSUE TITLE
Parsing keys with spaces into a struct

### ISSUE THREAD

**Issue by adamsoutar** [serde-rs/json#718]
Hi,
I have a piece of JSON like so:
```json
{
  "Player count": 1234,
  "Games played": 5678
}
```

How would I go about parsing this into a struct, since struct field names (as far as I can tell), can't contain spaces?
Would I need to use the loosely typed serde mode?

**Comment by jonasbb** [comment]
You can use the `rename` or `alias` attributes of serde to change how the keys are matched during de/serialization.

https://serde.rs/field-attrs.html#rename

**Comment by adamsoutar** [comment]
Exactly what I was looking for. Thanks!
