### ISSUE TITLE
Convert a struct to another

### ISSUE THREAD

**Issue by AurelienFT** [serde-rs/json#724]
Hello,

I'm currently working on a API GraphQL in Rust. I have structures with similar fields for models in database and input parameter of the GraphQL Query. To convert one of the structure into an other similar I implemented `From` trait. It was very annoying and very redundant to write so I started to make a crate to automatically implement it (https://github.com/AurelienFT/default-conversion-rs). But after I find out [this SO answer](https://stackoverflow.com/a/57488708/10419533) which explain how to do it with this crate.

I don't know if my way to do it with `From` implementations have pros versus the json middle conversion.

What do you think about it guys ?

**Comment by Szperak** [comment]
Your design decision...
- `From` slow to code, fast to run
- `serde_json` faster to code, slower to run

**Comment by AurelienFT** [comment]
Ok so you confirm it's slower to run to do it with serde_json ?

So If I make a nice way to generate it with macros it could be useful ?  @Szperak
