### ISSUE TITLE
Different behaviour between from_str and from_reader

### ISSUE THREAD

**Issue by FintanH** [serde-rs/json#725]
We have a use case where we're using `try_from` as a way to implement `Deserialize`. When testing it, we used `from_str` which worked perfectly fine. Then later when using it we noticed it was breaking on `from_reader`. The exact use case was using `&Path` but I was able to make a reproducible case with `&str` here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8ba461b4e5edf4de8d96d325751b2741

Then second `assert_eq` statement with throw an error when `unwrap`ping the deserialized result.

I'll include the code below as well:
```rust
use std::{convert::TryFrom, fmt};
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(into = "String", try_from = "&str")]
struct Foo {
    field: String,
}

impl fmt::Display for Foo {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.field)
    }
}

impl From<Foo> for String {
    fn from(foo: Foo) -> Self {
        foo.field
    }
}

impl TryFrom<&str> for Foo {
    type Error = String;
    
    fn try_from(field: &str) -> Result<Self, Self::Error> {
        match field {
            "foo" => Ok(Foo { field: "foo".to_string() }),
            _ => Err("It's not 'foo'".to_string())
        }
    }
}

fn main() {
  let x = Foo { field: "foo".to_string() };
  let json = serde_json::to_string(&x).unwrap();
  assert_eq!(x, serde_json::from_str(json.as_str()).unwrap());
  assert_eq!(x, serde_json::from_reader(json.as_bytes()).unwrap());
}
```

**Comment by jonasbb** [comment]
Deserializing a `&str`, which is what the `try_from` does, requires that you can borrow the data from somewhere. With `from_str` you can borrow from the input string but a reader only hands out owned data, no borrow. Think about what would happen if the reader reads from a network socket.
The deserialize can also fail for `from_str`. Try what happens if the JSON contains escape sequences, e.g., `"fo\"o"`.

**Comment by FintanH** [comment]
Nice, thanks for the explanation @jonasbb :blush: Opted to go through owned data in the end.
