### ISSUE TITLE
examples don't work

### ISSUE THREAD

**Issue by dataf3l** [serde-rs/json#728]
here is the example:
```
[package]
name = "serde_examples"
version = "0.1.0"
authors = ["Felipe@MBP2 <auditor400@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"




```

code:

```
use serde::{Deserialize, Serialize};
use serde_json::Result;

#[derive(Serialize, Deserialize)]
struct Address {
    street: String,
    city: String,
}

fn print_an_address() -> Result<()> {
    // Some data structure.
    let address = Address {
        street: "[null,4,'\\'$\\'#,##0.00']".to_owned(),
        city: "London".to_owned(),
    };

    // Serialize it to a JSON string.
    let j = serde_json::to_string(&address)?;

    // Print, write to a file, or send to an HTTP server.
    println!("{}", j);

    Ok(())
}
```

somehow, I get this error:

error[E0432]: unresolved import `serde`
 --> src/main.rs:1:5
  |
1 | use serde::{Deserialize, Serialize};
  |     ^^^^^ use of undeclared type or module `serde`

error: cannot determine resolution for the derive macro `Serialize`
 --> src/main.rs:4:10
  |
4 | #[derive(Serialize, Deserialize)]
  |          ^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the derive macro `Deserialize`
 --> src/main.rs:4:21
  |
4 | #[derive(Serialize, Deserialize)]
  |                     ^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error[E0601]: `main` function not found in crate `serde_examples`
  --> src/main.rs:1:1
   |
1  | / use serde::{Deserialize, Serialize};
2  | | use serde_json::Result;
3  | |
4  | | #[derive(Serialize, Deserialize)]
...  |
23 | |     Ok(())
24 | | }
   | |_^ consider adding a `main` function to `src/main.rs`

error[E0277]: the trait bound `Address: serde::ser::Serialize` is not satisfied
    --> src/main.rs:18:35
     |
18   |     let j = serde_json::to_string(&address)?;
     |                                   ^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `Address`
     |
    ::: /Users/b/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.59/src/ser.rs:2221:17
     |
2221 |     T: ?Sized + Serialize,
     |                 --------- required by this bound in `serde_json::to_string`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0277, E0432, E0601.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `serde_examples`.

To learn more, run the command again with --verbose.

cargo build
   Compiling serde_examples v0.1.0 (/Users/b/work/ntutree/tutree_jobs_v2_dev2/serde_examples)
error[E0432]: unresolved import `serde`
 --> src/main.rs:1:5
  |
1 | use serde::{Deserialize, Serialize};
  |     ^^^^^ use of undeclared type or module `serde`

error: cannot determine resolution for the derive macro `Serialize`
 --> src/main.rs:4:10
  |
4 | #[derive(Serialize, Deserialize)]
  |          ^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the derive macro `Deserialize`
 --> src/main.rs:4:21
  |
4 | #[derive(Serialize, Deserialize)]
  |                     ^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error[E0601]: `main` function not found in crate `serde_examples`
  --> src/main.rs:1:1
   |
1  | / use serde::{Deserialize, Serialize};
2  | | use serde_json::Result;
3  | |
4  | | #[derive(Serialize, Deserialize)]
...  |
23 | |     Ok(())
24 | | }
   | |_^ consider adding a `main` function to `src/main.rs`

error[E0277]: the trait bound `Address: serde::ser::Serialize` is not satisfied
    --> src/main.rs:18:35
     |
18   |     let j = serde_json::to_string(&address)?;
     |                                   ^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `Address`
     |
    ::: /Users/b/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.59/src/ser.rs:2221:17
     |
2221 |     T: ?Sized + Serialize,
     |                 --------- required by this bound in `serde_json::to_string`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0277, E0432, E0601.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `serde_examples`.

To learn more, run the command again with --verbose.

**Comment by dataf3l** [comment]
which kinda sucks

**Comment by jonasbb** [comment]
According to the error message you need to do two things.
You need to add a dependency on `serde` in your `Cargo.toml`. Something like this should work.
```toml
serde = { version = "1.0", features = [ "derive" ] }
```

Second, you also need to have a `main` function, if you want to run the code. You can add
```rust
fn main() -> Result<()> {
    print_an_address()
}
```
to your `main.rs` file.

**Comment by dataf3l** [comment]
Hi, this is correct, and that was the solution.

Thank you for spending time debugging my issue.

now can somebody please add that critical information to the actual example, so new people don't trample on the same issue?
