### ISSUE TITLE
About Vec<enum> in an object deserialize with no tag can referenced

### ISSUE THREAD

**Issue by tommady** [serde-rs/json#729]
Hi, I am new to rust and facing a problem with deserializing and seeking help here.

I got 
```rust
#[derive(Default, Debug, Deserialize)]
#[serde(default, rename_all = "snake_case")]
pub struct A {
    pub name: String,
    pub age: u32,
}

#[derive(Default, Debug, Deserialize)]
#[serde(default, rename_all = "snake_case")]
pub struct B {
    pub name: String,
    pub age: u32,
    pub heigh: u16,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "snake_case", untagged)]
pub enum Person {
   A(A), 
   B(B),
}

#[derive(Default, Debug, Deserialize)]
#[serde(default, rename_all = "snake_case")]
pub struct Response {
    pub status: u64,
    pub data: Vec<Person>, 
}
```

here is the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7d9b17d901c59535365bf25acad2d347)

as the result shows
```bash
Response { status: 200, data: [A(A { name: "A-A", age: 100 }), A(A { name: "A-B", age: 100 })] }
Response { status: 200, data: [A(A { name: "B-A", age: 100 }), A(A { name: "B-B", age: 100 })] }
```

what I expected is the second one can be deserialized into B type should be like below
```bash
Response { status: 200, data: [A(A { name: "A-A", age: 100 }), A(A { name: "A-B", age: 100 })] }
Response { status: 200, data: [B(B { name: "B-A", age: 100, height: 180 }), B(B { name: "B-B", age: 100, height: 170 })] }
```
is there has any way to do that?

thank you

**Comment by jonasbb** [comment]
Untagged enum deserialization works by trying all variants in declaration order until it finds one which successfully deserializes. If you want to prioritize `Person::B` you need to move that before `Person::A`. 

In your example everything which can be deserialized as `B` can also be deserialized as `A`, because `A` has the same fields as `B` but fewer of them.

**Comment by tommady** [comment]
Hi, @jonasbb thanks for your reply.

I tried this [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2263578674969ad61dfcae81b7065ec3) also but still getting the expected result.

that example I change the B type into
```rust
#[derive(Default, Debug, Deserialize)]
#[serde(default, rename_all = "snake_case")]
pub struct B {
    pub heigh: u16,
}
```
but the result still using A type to deserialize
```bash
Response { status: 200, data: [A(A { name: "A-A", age: 100 }), A(A { name: "A-B", age: 100 })] }
Response { status: 200, data: [A(A { name: "", age: 0 }), A(A { name: "", age: 0 })] }
```

which is not match the statement you said 

> Untagged enum deserialization works by trying all variants in declaration order until it finds one which successfully deserializes.

please guide 🙇🏻

**Comment by jonasbb** [comment]
@tommady You have specified `#[serde(default` for both `A` and `B`. This means deserialization will (almost) always succeed. If it cannot find the field, then it will just take the default value. This will not work for untagged enum deserialization. Untagged enum deserialization requires that deserialization will fail for the wrong variants and only succeed for the correct variant.

Removing `default` and changing the enum as explained in my first response works:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=85b411524ef7608eb759a1e249d8abe5

**Comment by tommady** [comment]
ya cool! thanks, man, this did the task!

thank you for your guiding 🙇🏻
