### ISSUE TITLE
customer deserializer not called when property is missing and parsing nested objects

### ISSUE THREAD

**Issue by mikechambers** [serde-rs/json#734]
I am not sure if this is a bug, but I wanted to report here in case it was.

I have a custom deserializer method to raise values out of nested json objects:

Here is the JSON

```json
"activitiesWon": {
    "statId": "activitiesWon",
    "basic": {
        "value": 3.0,
        "displayValue": "3"
    }
},
```

And here is the data structure and custom deserializer:

```rust
#[derive(Serialize, Deserialize, Debug, Default, Clone, Copy)]
pub struct PvpStatsData {
    #[serde(rename = "activitiesWon", deserialize_with="property_to_float")]
    pub activities_won:f32,
}

pub fn property_to_float<'de, D>(deserializer: D) -> Result<f32, D::Error>
    where D: serde::de::Deserializer<'de>,
{
    #[derive(Deserialize)]
    struct Outer {
        pub basic: Inner,
    }
    
    #[derive(Deserialize)]
    struct Inner {
        pub value: f32,
    }

    let helper = Outer::deserialize(deserializer)?;
    Ok(helper.basic.value)
}
```

This works great. However, some of the structures / properties might not exist, and thus their field signature looks like this, with the custom deserializer which either returns a Option<f32>, or None:

```rust
#[derive(Serialize, Deserialize, Debug, Default, Clone, Copy)]
pub struct PvpStatsData {
	#[serde(rename = "bestSingleGameKills", deserialize_with="property_to_option_float")]
	pub best_single_game_kills:Option<f32>,
}

pub fn property_to_option_float<'de, D>(deserializer: D) -> Result<Option<f32>, D::Error>
    where D: serde::de::Deserializer<'de>,
{
    println!("PARSER");
    #[derive(Deserialize, Debug, )]
    struct Outer {
        pub basic: Inner,
    }
    
    #[derive(Deserialize, Debug, )]
    struct Inner {
        pub value: f32,
    }

    Option::<Outer>::deserialize(deserializer).map(|o:Option<Outer>| match o {
        Some(e) => {
            println!("{:?}", e);
            Some(e.basic.value)
        },
        None => None,
    })
}
```

However, when parsing, if the property doesn't exist in json, then I get a parse error:

```
serde_json::Error : Error("missing field `bestSingleGameKills`", line: 1, column: 4358)
```

and my custom de-serialization method is never called.

Ive posted a playground of the example here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=022d7ca3513e411644d186518d177645

(just uncomment the second json block to see the issue)

Expected behavior is that the customer desrialization method is call in both / all cases.

I have other deserializers that can deal with Optional results, but I suspect this has something to do with the combination of the nested json and option.

**Comment by jonasbb** [comment]
This behavior is by design. You can apply `#[serde(default)]` to restore the default behavior of `Option`s, i.e., deserialize as `None` on missing fields, or use `#[serde(default = "path")]` to run an arbitrary function. You can check the available [field attributes](https://serde.rs/field-attrs.html).

What is the `property_to_option_float` function supposed to do when called on a missing field? It cannot deserialize anything from its `deserializer` argument, since the field does not exist. This would only lead to a deserialization error. The function also does not know that the field is missing. There is no mechanism (argument or via the `deserializer`) to communicate this to the function.
