### ISSUE TITLE
please update to 0.7.1 in crates.io

### ISSUE THREAD

**Issue by daogangtang** [serde-rs/json#74]
meet a dependency problem, thx.

**Comment by oli-obk** [comment]
> meet a dependency problem

can you be more specific about the issue you are having?

**Comment by daogangtang** [comment]
0.7.0 has not implement ToJson trait. But some other place need it to replace rustc_serialize. Thx.

**Comment by dtolnay** [comment]
Just waiting for @erickt to publish: #72

**Comment by erickt** [comment]
@dtolnay / @oli-obk: I merged #72 in. I'm just waiting for #75 to be auto-merged by homu. I also gave the both of you permission to push up serde and serde_json crates in the future, so you won't be blocked by me anymore :)

**Comment by erickt** [comment]
v0.7.1 has been released!

**Comment by dtolnay** [comment]
[Release notes](https://github.com/serde-rs/json/releases/tag/v0.7.1)

**Comment by daogangtang** [comment]
thanks
