### ISSUE TITLE
Deserialize vector of mixed types.

### ISSUE THREAD

**Issue by arthurkhlghatyan** [serde-rs/json#741]
Hi Guys, 

I'm trying to represent the GraphQL error message format according to a [spec](https://spec.graphql.org/June2018/#sec-Errors) as a Deserializable struct. So far I have this.

```rust
#[derive(Deserialize, Debug)]
pub struct GraphQLErrorMessage {
  message: String,
  locations: Option<Vec<GraphQLErrorLocation>>,
  extensions: Option<HashMap<String, String>>,
  path: Option<Vec<String>>
}
```

But the problem is that the **path** parameter can contain both string and integer values like in this example.

```JSON
{
  "message": "Name for a character with ID 1002 could not be fetched.",
  "locations": [ { "line": 6, "column": 7 } ],
  "path": [ "hero", "heroFriends", 1, "name" ]
}
```
What is the possible solution for such a case?

Thank you.

**Comment by jonasbb** [comment]
You can use a specialized enum for this use case and annotate it with `#[serde(untagged)]` or use something like [`serde_json::Value`](https://docs.rs/serde_json/1.0.61/serde_json/enum.Value.html) to be most flexible.

```rust
#[derive(serde::Deserialize)]
#[serde(untagged)]
enum StringOrNumber {
	String(String),
	Number(u32),
}
```

You `path` can then be `path: Option<Vec<StringOrNumber>>`.

**Comment by arthurkhlghatyan** [comment]
Thank you @jonasbb. It worked fine on my end!
