### ISSUE TITLE
to_writer_pretty doesn't add newline at end of file

### ISSUE THREAD

**Issue by cdstanford** [serde-rs/json#746]
Hello,

I am using `serde_json` for a project and noticed that `to_writer_pretty` doesn't add a newline at the end of file. For a simple example, the following code:

Cargo.toml:
```
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```

```
use serde::ser::Serialize;
use std::fmt::Debug;
use std::fs::File;
use std::io::{BufWriter, Write};

fn main() {
    let writer = BufWriter::new(File::create("test.json").unwrap());
    serde_json::to_writer_pretty(writer, "not_newline_terminated").unwrap();
}
```

results in a non-newline-terminated file at `test.json`.

Does anyone have an idea of how to easily change the code above to add a newline? And can anyone think of a good way to publicly expose an easy solution in the serde_json API?

Why it's important: non-newline-terminated files, though generally recognized by some programs, can cause serious errors in systems programming in general. It would be good if the easy way to do this does not result in subtle bugs for downstream users.

Why it's not (at obviously so) a one-line fix: the problem is that `to_writer_pretty` takes ownership of the BufWriter, so you cannot simply afterwards use the BufWriter to add a newline, e.g.:
```
fn main() {
    let mut writer = BufWriter::new(File::create("test.json").unwrap());
    serde_json::to_writer_pretty(writer, "not_newline_terminated").unwrap();
    writeln!(&mut writer).unwrap();
}
```

fails to compile.

**Comment by jonasbb** [comment]
Your code works if you replace `writer` with `&mut writer` in the third line:

```rust
fn main() {
    let mut writer = BufWriter::new(File::create("test.json").unwrap());
    serde_json::to_writer_pretty(&mut writer, "not_newline_terminated").unwrap();
    writeln!(&mut writer).unwrap();
}
```

The `io::Write` trait is implemented for `&mut W` where `W: io::Write`, which allows you to keep the writer alive.

**Comment by cdstanford** [comment]
@jonasbb Thanks! Looks like you are right. I'm glad that works! Is there a good reason in the design that `serde_json::to_writer_pretty` was chosen to not terminate with a newline?

**Comment by jonasbb** [comment]
@cdstanford No, I do not know that. It seems like the safer default, since adding it is easier than removing it in case it is undesired.

**Comment by cdstanford** [comment]
Files without newline termination can be a real safety issue, but I would agree in this case since you can borrow the writer that not newline terminating is more flexible. This way I suppose allows for writing to the same file multiple times and adding a newline at the end, though I don't have in mind a real use case for that.
