### ISSUE TITLE
Serializing an enum with an unknown value to a special case

### ISSUE THREAD

**Issue by avnerbarr** [serde-rs/json#749]
Hi,
I'd like to serialize enum such that if the case is unknown it will be assigned to "other" 

```
pub enum Action {
A1,  // explicit match
A2, // explicit match
A3, // explicit match
Other(String), // if the  case is unknown it should be part of the "other" case
}
```

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/json/tree/v1.0.77#getting-help. Sorry that no one was able to provide guidance here.
