### ISSUE TITLE
Support struct update syntax for json! macro

### ISSUE THREAD

**Issue by andrewbanchich** [serde-rs/json#761]
Would it be possible to support this syntax for merging objects?

```rust
let thing = Thing {
    foo: true  
};

let one = json!({
    "bar": false,
    ..thing
});

let two = json!({
    "baz": true,
    ..one
});
```

**Comment by dtolnay** [comment]
I think I would prefer not to make this change, but it would be reasonable to support in a more elaborate `json!` macro outside of the serde_json crate.
