### ISSUE TITLE
Desrialize Option<Vec<struct>> with flatten

### ISSUE THREAD

**Issue by doddi** [serde-rs/json#765]
I am new to Rust in general and I have been trying to deserialize the following JSON object:
```
{
    "version": "1.2.3",
    "bars": [
        {
            "baz": "hello",
            "other": "world"
        }
    ]
}
```

but currently, I am required to use the following structures (due to other deserializer requirements):

```rust
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Foo {
    pub version: String,
    pub bars: Option<Bar>
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Bar {
    pub bar: Vec<Baz>
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Baz {
    pub baz: String,
    pub other: String
}
```

I realise that I can use `bars: Option<Vec<Bar>>` but this has restrictions on other parts of my project.

The only way I can get this code to run when passing the JSON object described is to add `#[serde(flatten)]` to the `pub bars: Option<Bar>` however the deserialized object is always `None`.

Is there a way to get the JSON object to deserialize with the provided structs?

**Comment by GREsau** [comment]
I think the [`transparent`](https://serde.rs/container-attrs.html#transparent) attribute does what you want:
> - `#[serde(transparent)]`
> Serialize and deserialize a newtype struct or a braced struct with one field exactly the same as if its one field were serialized and deserialized by itself. Analogous to #[repr(transparent)].

```rust
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Bar {
    pub bar: Vec<Baz>
}
```

Demo: https://play.rust-lang.org/?edition=2018&gist=e8a9f80b582d7e60b5dfa33ec05ec4be

**Comment by doddi** [comment]
@GREsau perfect thank you!
