### ISSUE TITLE
Deserialize HashMap with tuple keys

### ISSUE THREAD

**Issue by ThisIsRex** [serde-rs/json#772]
Hello. I've already found how to serialize this kind of HashMaps in [this issue](https://github.com/serde-rs/json/issues/456)
But how should I deserialize it from JSON string like this:
  ```
{
	  "(1,2)": { ... },
	  "(3,4)": { ... },
	  "(5,6)": { ... }
  }
```
The types in the key tuple are always numbers (i32, usize, etc). It's unnecessary but it will be better if the type could also be String

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/json/tree/v1.0.77#getting-help. Sorry that no one was able to provide guidance here.
