### ISSUE TITLE
Fail to parse tuple with length 1

### ISSUE THREAD

**Issue by stephenctw** [serde-rs/json#781]
Below code doesn't work.
```
use serde::Deserialize;

#[derive(Deserialize)]
pub struct BoolField {
    pub name: String,
    pub ty: String,
    pub value: bool,
}

#[derive(Deserialize)]
pub struct CtxParsed(
    BoolField,
);

fn main() {
    let json_data = "[{ \"name\": \"success\", \"ty\": \"bool\", \"value\": false }]";
    let parsed: core::result::Result<CtxParsed, serde_json::error::Error> =
            serde_json::from_str(json_data);
}
```
`Err(Error("invalid type: map, expected a string", line: 1, column: 1))`
However doubling (or multiplying) the elements in json_data and CtxParsed, it's working.
```
#[derive(Debug, Deserialize)]
pub struct CtxParsed(
    BoolField,
    BoolField,
);
let json_data = "[{ \"name\": \"success\", \"ty\": \"bool\", \"value\": false }, { \"name\": \"success\", \"ty\": \"bool\", \"value\": false }]";
```

I don't see an obvious reason for this behaving differently.

**Comment by jonasbb** [comment]
In [serde's data model](https://serde.rs/data-model.html) `CtxParsed(BoolField)` is a newtype struct, while `CtxParsed(BoolField, BoolField)` is a tuple struct.
serde_json chooses to treat them differently. A newtype struct is simply [serialized as the inner element](https://github.com/serde-rs/json/blob/df1fb717badea8bda80f7e104d80265da0686166/src/ser.rs#L257) but a tuple struct is [serialized as a sequence of elements](https://github.com/serde-rs/json/blob/df1fb717badea8bda80f7e104d80265da0686166/src/ser.rs#L346).

If `CtxParsed` is only supposed to have a single `BoolField`, you could use a 1-element tuple `CtxParsed((BoolField,))` or a  1-element array `CtxParsed([BoolField; 1])`. Maybe also adding `#[serde(transparent)]` to the struct.

**Comment by stephenctw** [comment]
> 
> 
> In [serde's data model](https://serde.rs/data-model.html) `CtxParsed(BoolField)` is a newtype struct, while `CtxParsed(BoolField, BoolField)` is a tuple struct.
> serde_json chooses to treat them differently. A newtype struct is simply [serialized as the inner element](https://github.com/serde-rs/json/blob/df1fb717badea8bda80f7e104d80265da0686166/src/ser.rs#L257) but a tuple struct is [serialized as a sequence of elements](https://github.com/serde-rs/json/blob/df1fb717badea8bda80f7e104d80265da0686166/src/ser.rs#L346). Same for deserialization.
> 
> If `CtxParsed` is only supposed to have a single `BoolField`, you could use a 1-element tuple `CtxParsed((BoolField,))` or a 1-element array `CtxParsed([BoolField; 1])`. Maybe also adding `#[serde(transparent)]` to the struct.

Thanks the document explains really well.
