### ISSUE TITLE
[Discussion] Is there a way to estimate serialized json string size before actual serialization?

### ISSUE THREAD

**Issue by JackLiar** [serde-rs/json#784]
The scenario is I'm trying to using the elasticsearch-rs crate to index json data by using bulk API(sending multiple json objects in one TCP request). However I don't wanna make a bulk request too big since that may cause Elasticsearch's index performance to drop.

Now I could only prevent that by controlling how many documents(json objects) to be send by a single request, but that is not precise enough. Sure I could do a serialization operation first to control request size, but that means I have to make an extra copy of the json string or do an extra serialization operation, which is kind of annoying.

So is it possible to do some estimation about how big the serialization result is?

**Comment by dtolnay** [comment]
Yeah here is a way to count just the size without producing a heap allocated json string:

```rust
use serde::Serialize;
use std::io::{self, Write};

struct ByteCount(usize);

impl Write for ByteCount {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.0 += buf.len();
        Ok(buf.len())
    }
    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

fn main() {
    let mut ser = serde_json::Serializer::new(ByteCount(0));
    let value = vec!["3", "2", "1"];
    value.serialize(&mut ser).unwrap();
    let len = ser.into_inner().0;

    assert_eq!(len, serde_json::to_string(&value).unwrap().len());
}
```

**Comment by JackLiar** [comment]
Awesome mate! Thx! I'll give it a shot :)
