### ISSUE TITLE
Gnereate serde code from JSON schema

### ISSUE THREAD

**Issue by linonetwo** [serde-rs/json#791]
Currently, we can guess serde code from https://transform.tools/json-to-rust-serde

But it loses the variety when it needs enum. And we cannot guarantee the JSON we are using covers every case that we need.

If we can generate serde code from JSON Schema, we don't have to worry about this. So is there a generator that can generate serde code from JSON Schema?

**Comment by AlyoshaVasilieva** [comment]
https://github.com/quicktype/quicktype
