### ISSUE TITLE
Better error (or skip) if json starts with the byte order mark

### ISSUE THREAD

**Issue by ChrisDenton** [serde-rs/json#805]
Some JSON encoders or file tools (illegally) add a byte order mark to the start of a json file. This lead to a very confusing error when de-serializing as the editor I used to display the file hid the BOM.

```
expected value at line 1 column 1
```

It would be great if there was a better diagnostic for this situation. Or maybe skip the BOM if it's at the start of a stream.

**Comment by ChrisDenton** [comment]
For the record, the spec says:

> Implementations **MUST NOT** add a byte order mark to the beginning of a
> JSON text.  In the interests of interoperability, implementations
> that parse JSON texts **MAY** ignore the presence of a byte order mark
> rather than treating it as an error.

**Comment by dtolnay** [comment]
I think I don't feel the need to add dedicated handling of this case into serde_json.

It's possible that the "expected value" error can be improved *in general*, for example by rendering what character is the next in the input. IIRC "expected value" is occasionally used as a fallback "I don't really know what happened" error codepath. I would be interested in a PR that attempts to clean that up.
