### ISSUE TITLE
Remove does not preserve order

### ISSUE THREAD

**Issue by d0cd** [serde-rs/json#807]
The `preserve_order` feature uses an IndexMap as the backing data store for `serde_json::Map`
However, the `remove` method for IndexMap is equivalent to `swap_remove`. 
If the `preserve_order` feature is enabled, then `shift_remove` should be used instead.

**Comment by dtolnay** [comment]
Closing per https://github.com/serde-rs/json/pull/860#pullrequestreview-889061502 -- I think this is all right as currently implemented.
