### ISSUE TITLE
Incorrect result when using custom serialize_with method on struct member

### ISSUE THREAD

**Issue by jlgerber** [serde-rs/json#81]
I have encountered what I believe to be a bug. I am using 0.7's ability to specify a custom serialize_with function. I have a struct with a string and an enum wrapping either a u64 or a vector of the same. When serializing a struct with the vector, I get a comma after the field name and colon, but before the array. If I rearrange my struct, so that the enum wrapping the vector comes first, before the other field, it behaves as expected. 
See the following gist
[problem code](https://gist.github.com/jlgerber/bf9c768c553acca6a8535cc609654796)

**Comment by dtolnay** [comment]
Can you share more of the code including the struct definition and the serialize_with function?

**Comment by dtolnay** [comment]
I was not able to reproduce this with the following code. Perhaps it is something wrong with your serialize_with function?

```rust
#![feature(plugin, custom_derive)]
#![plugin(serde_macros)]

extern crate serde;
extern crate serde_json;

#[derive(Serialize)]
struct StringThenEnum {
    relation: String,
    #[serde(serialize_with="serialize_with")]
    values: Object,
}

#[derive(Serialize)]
struct EnumThenString {
    #[serde(serialize_with="serialize_with")]
    values: Object,
    relation: String,
}

#[derive(Serialize)]
enum Object {
    Id(u64),
    Ids(Vec<u64>),
}

fn serialize_with<S>(x: &Object, serializer: &mut S) -> Result<(), S::Error>
    where S: serde::Serializer,
{
    match *x {
        Object::Id(ref u) => serde::Serialize::serialize(u, serializer),
        Object::Ids(ref v) => serde::Serialize::serialize(v, serializer),
    }
}

#[test]
fn string_then_enum() {
    let obj = StringThenEnum {
        relation: String::from("foo"),
        values: Object::Id(444),
    };
    let result = serde_json::to_string(&obj).unwrap();
    let expectation = "{\"relation\":\"foo\",\"values\":444}";
    assert_eq!(result, expectation);

    let obj = StringThenEnum {
        relation: String::from("foo"),
        values: Object::Ids(vec![333,444]),
    };
    let result = serde_json::to_string(&obj).unwrap();
    let expectation = "{\"relation\":\"foo\",\"values\":[333,444]}";
    assert_eq!(result, expectation);
}

#[test]
fn enum_then_string() {
    let obj = EnumThenString {
        values: Object::Id(444),
        relation: String::from("foo"),
    };
    let result = serde_json::to_string(&obj).unwrap();
    let expectation = "{\"values\":444,\"relation\":\"foo\"}";
    assert_eq!(result, expectation);

    let obj = EnumThenString {
        values: Object::Ids(vec![333,444]),
        relation: String::from("foo"),
    };
    let result = serde_json::to_string(&obj).unwrap();
    let expectation = "{\"values\":[333,444],\"relation\":\"foo\"}";
    assert_eq!(result, expectation);
}

```

**Comment by jlgerber** [comment]
whoops. i thought that i pasted the complete repro in the gist. i just updated the gist to have the complete code.

**Comment by jlgerber** [comment]
Perhaps this is just a case of documentation needing to be updated to guide developers? I thought that i should be delegating to the serializer class in the match expression of the custom serialize_with function:

This is the match arm which got me into trouble...
`Object::Ids(ref vi) => serializer.serialize_seq_elt(vi)`

**Comment by jlgerber** [comment]
Question: is there a way to associate a custom serializing function for a type in general? IE in the example above, if i wanted to always serialize Object using the serialize_with function, as opposed to only within the StringThenEnum struct, how would i go about that?

**Comment by dtolnay** [comment]
> `Object::Ids(ref vi) => serializer.serialize_seq_elt(vi)`

The [serialize_seq_elt](https://serde-rs.github.io/serde/serde/ser/trait.Serializer.html#tymethod.serialize_seq_elt) method is for serializing one element (elt) of a sequence (vec or list). It is supposed to be used by the [serialize_seq](https://serde-rs.github.io/serde/serde/ser/trait.Serializer.html#tymethod.serialize_seq) method, with a SeqVisitor that calls serialize_seq_elt for each element in the sequence that is being serialized.

In JSON, the behavior of serialize_seq_elt is to write a comma if this is not the first element, then serialize the element. This explains the behavior you were seeing.

The broader problem here is that the "serde" protocol is not yet enforced by the type system, so as of right now serde_json assumes you've implemented Serialize/Deserialize correctly. #33 is a similar issue.

**Comment by dtolnay** [comment]
> Question: is there a way to associate a custom serializing function for a type in general? IE in the example above, if i wanted to always serialize Object using the serialize_with function, as opposed to only within the StringThenEnum struct, how would i go about that?

The "custom serializing function for a type" is just the serde::Serialize impl for that type. Just replace your `impl MySerialization` with `impl Serialize`:

```rust
#[derive(PartialEq, Debug)]
pub enum Object {
    Id(Id),
    Ids(Ids),
}

#[derive(Debug, PartialEq, Serialize)]
pub struct ObjWrap {
    pub relation: String,
    pub values: Object,
}

impl serde::Serialize for Object {
    fn serialize<S: Serializer>(&self, serializer: &mut S) -> Result<(), S::Error> {
        match *self {
            Object::Id(ref i) => Serialize::serialize(i, serializer),
            Object::Ids(ref vi) => Serialize::serialize(vi, serializer),
        }
    }
}
```

**Comment by dtolnay** [comment]
You will also need to provide a corresponding Deserialize impl to handle your format. It needs to be able to deserialize both u64 and sequence. Something like:

```rust
impl Deserialize for Object {
    fn deserialize<D: Deserializer>(deserializer: &mut D) -> Result<Self, D::Error> {
        struct ObjectVisitor;
        impl de::Visitor for ObjectVisitor {
            type Value = Object;
            fn visit_u64<E: de::Error>(&mut self, i: u64) -> Result<Self::Value, E> {
                Ok(Object::Id(i))
            }
            fn visit_seq<V: de::SeqVisitor>(&mut self, vis: V) -> Result<Self::Value, V::Error> {
                let mut vec_visitor = de::impls::VecVisitor::new();
                let ids = try!(vec_visitor.visit_seq(vis));
                Ok(Object::Ids(ids))
            }
        }
        deserializer.deserialize(ObjectVisitor)
    }
}
```

**Comment by jlgerber** [comment]
@dtolnay - thanks a bunch for the help. My actual use case is a  bit more complicated. The object enum has two potential sequence types - a vector of ints and a vector of strings. I am assuming that would replace the ids=try!... in your example with a match expression....

On the subject of Strings, what is the canonical way of handling deserialization of strings? In the case where i want a vector of them, should i simply declare them as such and take ownership? Should i create a new vector and copy the originals somehow? Any advice on that topic would be much appreciated....

**Comment by dtolnay** [comment]
> My actual use case is a bit more complicated. The object enum has two potential sequence types - a vector of ints and a vector of strings.

Here is one possibility: deserialize each element as either an int or a string.

```rust
fn visit_seq<V: de::SeqVisitor>(&mut self, mut vis: V) -> Result<Self::Value, V::Error> {
    enum IdOrString {
        Id(u64),
        String(String),
    }
    impl Deserialize for IdOrString {
        fn deserialize<D: Deserializer>(deserializer: &mut D) -> Result<Self, D::Error> {
            struct IdOrStringVisitor;
            impl de::Visitor for IdOrStringVisitor {
                type Value = IdOrString;
                fn visit_u64<E: de::Error>(&mut self, i: u64) -> Result<Self::Value, E> {
                    Ok(IdOrString::Id(i))
                }
                fn visit_str<E: de::Error>(&mut self, s: &str) -> Result<Self::Value, E> {
                    Ok(IdOrString::String(s.to_string()))
                }
            }
            deserializer.deserialize(IdOrStringVisitor)
        }
    }

    let mut ids = Vec::new();
    let mut strings = Vec::new();
    while let Some(value) = try!(vis.visit()) {
        match value {
            IdOrString::Id(i) => ids.push(i),
            IdOrString::String(s) => strings.push(s),
        }
    }
    try!(vis.end());

    if strings.is_empty() {
        Ok(Object::Ids(ids))
    } else if ids.is_empty() {
        Ok(Object::Strings(strings))
    } else {
        Err(de::Error::custom("cannot have ids and strings in the same vector"))
    }
}
```
