### ISSUE TITLE
"$serde_json::private::Number" positional dependence prevents round-tripping Values

### ISSUE THREAD

**Issue by saethlin** [serde-rs/json#826]
I'm experimenting with a new fuzz target, intending to find inputs that do not round-trip correctly. Instead, I found something quite different (than I expected). This example program crashes on the last line when the `arbitrary_precision` feature is turned on:
```rust
fn main() {
    let input = r#"{"C":0,"$serde_json::private::Number":0}"#;
    let value = serde_json::from_str::<serde_json::Value>(input).unwrap();
    let serialized = serde_json::to_string(&value).unwrap();
    println!("{:?}", serialized);
    let roundtrip = serde_json::from_str::<serde_json::Value>(&serialized).unwrap();
}
```

That... doesn't seem right to me. As far as I understand, if `"$serde_json::private::Number"` is the first key in a map, the deserializer expects its value to be a string, but otherwise just treats it as a normal key. Which seems... a bit unnecessarily magical, but the fact that the order of keys may be changed by the round-trip really pushes this more towards "there is a bug here" in my opinion. As far as I can tell everything here is intentional but it seems like this is quite the papercut.

Thoughts?

---
Also I'm just sitting here in awe that cargo-fuzz synthesized this example

**Comment by dtolnay** [comment]
Thanks for flagging. I think I'm fine sticking with this behavior. As you noted, all of the code involved is intentional.
