### ISSUE TITLE
Deserialize OffsetDateTime from serde_json::Value

### ISSUE THREAD

**Issue by madmaxio** [serde-rs/json#832]
I'm using this simple code, and getting Err(Error("invalid type: string \"2021-11-22 21:34:12.1901555 +00:00:00\", expected a borrowed string", line: 0, column: 0)).
I checked the code - should I try to fix it inside time crate with the Cow, probably?

```
serde_json = "1.0.71"
time = { version = "0.3.5", features = ["serde-human-readable"] }

use time::OffsetDateTime;

fn main() {
    let now = time::OffsetDateTime::now_utc();
    let ser = serde_json::json!(now);

    println!("{:?}", ser);
    
    let de = serde_json::from_value::<OffsetDateTime>(ser);

    println!("{:?}", de);
}
```

and getting error:

```
String("2021-11-22 21:34:12.1901555 +00:00:00")

Err(Error("invalid type: string \"2021-11-22 21:34:12.1901555 +00:00:00\", expected a borrowed string", line: 0, column: 0))
```

**Comment by dtolnay** [comment]
This is a bug in the time crate. There is no reason they should require a borrowed string rather than a transient string.

**Comment by madmaxio** [comment]
Time crate maintainer said here https://github.com/time-rs/time/discussions/398#discussioncomment-1725446 that it is possible for serde to request &str string instead of working with owned string in time crate. Is it possible to propose such feature for serde?
