### ISSUE TITLE
wasm_bindgen::JsValue <-> serde_json::Value, using serde_json with web assembly

### ISSUE THREAD

**Issue by caperaven** [serde-rs/json#836]
I want to use serde_json in a web assembly but you can't seem to use it directly.
One of the ways I thought I could solve this problem is by exposing my function parameters as JsValue and then convert it to serde_json Value objects for further use and then reverse the process for results.

Is this possible?

I will want to deal with 100k records in a single structure so the conversion must be as performant as possible.
Obviously not having to convert between the two formats would be first prize.
Can you use serde_json where the parameters are of type Value?

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/json/tree/v1.0.77#getting-help. Sorry that no one was able to provide guidance here.
