### ISSUE TITLE
Dependencies is not working for the Address example

### ISSUE THREAD

**Issue by IoT-master** [serde-rs/json#837]
https://github.com/serde-rs/json/blob/master/README.md#serde-json----
dependencies should be:
[dependencies]
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"

**Comment by dtolnay** [comment]
I think this is covered by the link in that section about setting up the derive macros:

> ![Screenshot from 2022-01-22 12-16-39](https://user-images.githubusercontent.com/1940490/150656066-330880b5-5dc5-4050-8605-9ac9f6ba2823.png)
