### ISSUE TITLE
Feature Discussion: Support nonfinite numeric values via feature flag

### ISSUE THREAD

**Issue by kykosic** [serde-rs/json#838]
Currently this crate follows strict JSON protocol and does not allow nonfinite numeric values. However, when interacting with other services such as the [Python standard library](https://docs.python.org/3/library/json.html) or [Snowflake](https://docs.snowflake.com/en/sql-reference/parameters.html) it would be nice to opt-in support for `NaN`, `Infinity`, and `-Infinity` numeric values with a feature flag. This is very important data when serializing from machine learning or scientific computing applications.

I'm able to implement it, but before I'd like to confirm if this is a feature that would get accepted into the crate.

**Comment by dtolnay** [comment]
I would prefer not to build this into serde_json but it would be reasonable for somebody else to maintain a different library for this.
