### ISSUE TITLE
Deserialize Map as String

### ISSUE THREAD

**Issue by Proxtx** [serde-rs/json#840]
serde_json seems to ignore the types provided in the struct rsulting in a panick. 
`{
    "success": true,
    "data": {
        "success": true,
        "location": "modules.user.Module.checkCredentials",
        "error": 0,
        "user": {
            "userId": "----",
            "username": "Proxtx",
            "email": "-----"
        }
    }
}`

This is the json data

and this is the struct: 
`#[derive(Serialize, Deserialize, Debug)]
struct CombineResult {
  success: bool,
  data: String
}`

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a string", line: 1, column: 23)', src\main.rs:180:74`

As you can probably tell: Data should be Deserialized as a String and not as a map.
Am I doing something wrong? Is this intended behavior?

**Comment by dtolnay** [comment]
Yep, this is the intended behavior. String means `"..."` in JSON, and `{...}` is not that.

The panic isn't in serde_json though; it's line 180 of your main.rs that is panicking.

**Comment by Proxtx** [comment]
Thanks for answering so quick. I know this isn't an issue anymore but is there a way to force serde to interpret this as a string?
