### ISSUE TITLE
Serialization of NaN in f64 will not deserialize.

### ISSUE THREAD

**Issue by John-Nagle** [serde-rs/json#842]
Serializing an f64 with a NaN value produces a Null, because Number does not represent NaNs. But deserializing a Null into an f64 is an error. I understand why this happens; it kind of falls out of the way deserialization works. But it can be a problem. Some data won't round-trip. 

The same bug exists in .NET, because JSON doesn't have a representation for NaN. So I don't expect it to be fixed, but it should be documented.

**Comment by dtolnay** [comment]
Which page would you have expected to find the documentation of this?

**Comment by John-Nagle** [comment]
Perhaps a note on the main page, pointing out that there are cases what will compile but some valid values for types will not work. Because serde_json takes full responsibility for serialization and deserialization of entire data structures, this deserves a mention.

At least in https://docs.serde.rs/serde_json/error/struct.Error.html
it should be mentioned under semantic errors.

**Comment by dtolnay** [comment]
I think I'm not convinced that describing this case either in the readme/crate-level rustdoc or the `Error` type's page would save people from stumbling on this. In general the more documentation we write the less of it people read, so we need to balance including only what is maximally relevant to the most readers.
