### ISSUE TITLE
Make utf8 serialization (including escaping) public

### ISSUE THREAD

**Issue by jorgecarleitao** [serde-rs/json#857]
We had to copy-paste some code from `serde_json` (https://github.com/jorgecarleitao/arrow2/pull/813). It would be better if `serde_json::ser` would offer such a functionality in its public API.

Goal: given a `&[u8]` representing valid utf8, we would like a function that writes it to a writer (e.g. `&mut Vec<u8>`) taking into account that some bytes will need to be escaped accordingly.

**Comment by dtolnay** [comment]
I don't fully understand what your crate is doing that it can't just use the existing API of serde_json, but there isn't anything else not already exposed that I would prefer to expose here.

**Comment by jorgecarleitao** [comment]
I wanted to serialize a `&str` to json, but it that is indeed supported because `&str` implements Serialize. I thought that we had to roundtrip over `Value`, which would require an allocation. Sorry for the noise. :/
