### ISSUE TITLE
Field order is based on order of fields in the struct even with preserve-order enabled

### ISSUE THREAD

**Issue by milesj** [serde-rs/json#858]
I can't seem to get this working and I have no idea why. From my googling and browsing this repo, it _should_ be possible, but I may be confusing it with deserializing only.

Anytime I serialize it orders fields based on the order of fields in the struct, and not in the order of fields in the file before deserializing. 

I have a PR here to try and fix it: https://github.com/milesj/moon/pull/45

And this is the struct: https://github.com/milesj/moon/blob/fix-json/crates/config/src/package.rs#L12

Is my understanding of `preserve_order` wrong?

**Comment by milesj** [comment]
Wrote a test that verifies this: https://github.com/milesj/moon/pull/45/files#diff-f4e3009eb125d0d4de2eb6fa3f5c4e90ffdb424fb9f0d8dc99d5d04a23313e35R371

```
---- package::test::preserves_order_when_de_to_ser stdout ----
thread 'package::test::preserves_order_when_de_to_ser' panicked at 'assertion failed: `(left == right)`
  left: `"{\n  \"description\": \"world\",\n  \"name\": \"hello\",\n  \"private\": true\n}"`,
 right: `"{\"name\": \"hello\", \"description\": \"world\", \"private\": true}"`', crates/config/src/package.rs:381:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dtolnay** [comment]
I think this is working as intended: preserve_order only affects the representation of serde_json::Map (and thus serde_json::Value). It makes that data structure store additional information about the entry order, in addition to the keys/values themselves. If you are deserializing to a struct that is defined in your own program, that struct isn't gonna have a place to put such order information.

**Comment by milesj** [comment]
For anyone coming to this issue, this is my workaround. https://github.com/milesj/moon/pull/68
