### ISSUE TITLE
Add `unwrap_or_default` method to the `Map`.

### ISSUE THREAD

**Issue by Jerrody** [serde-rs/json#859]
`unwrap_or_default` should return a default value: `Value::Null`. Exists places, where's duplicating, and these places are annoying.

**Comment by dtolnay** [comment]
I'm not clear on exactly what signature you have in mind, but the standard `BTreeMap` and `HashMap` do not have an `unwrap_or_default` method, so I would prefer not to add one to serde_json's map.
