### ISSUE TITLE
Support I-JSON

### ISSUE THREAD

**Issue by chris-morgan** [serde-rs/json#862]
I’m seeking to implement some JMAP ([RFC 8620](https://datatracker.ietf.org/doc/html/rfc8620)). It specifies that its messages are I-JSON ([RFC 7493](https://datatracker.ietf.org/doc/html/rfc7493)), which is “a restricted profile of JSON designed to maximize interoperability and increase confidence that software can process it successfully with predictable results”.

I desire that serde_json support I-JSON in some capacity, giving me the ability to reject certain messages, so that I can implement JMAP correctly, returning a `urn:ietf:params:jmap:error:notJSON` error on documents that are not valid I-JSON.

I-JSON’s *requirements* (as in, MUSTs) are these:

> I-JSON messages MUST be encoded using UTF-8;

✓ This is already the case in serde_json, including in escape sequences as required.

> Object member names, and string values in arrays and object members, MUST NOT include code points that identify Surrogates or Noncharacters as defined by Unicode.

✓ Untyped deserialisation prevents unpaired surrogates.
✓ String deserialisation prevents unpaired surrogates.
✗ I gather, from a quick glance at the code, that it’s still *possible* to do bytewise deserialisation, which would allow unpaired surrogates. But you have to go out of your way to achieve this, so I don’t think it’s a practical concern, though it would be good to fix it in I-JSON mode if incidentally possible.
✗ Nothing guards against [Noncharacters](https://www.unicode.org/faq/private_use.html#noncharacters).

> Objects in I-JSON messages MUST NOT have members with duplicate names.

✓ For typed access using `#[derive(Deserialize)]` on an enum or struct, duplicates cause errors.
✗ For untyped access, `serde_json::Value` allows duplicates, the last declaration winning.
✗ `std::collections::HashMap` is in the same boat. There are probably other types that are as well, which is not *ideal* at the least.

That this touches existing types’ deserialisers, including ones defined in Serde itself, makes it more difficult to remedy; in specific cases, `#[serde(deserialize_with = …)]` could work, but I wonder if it may be expedient to have an I-JSON `Deserializer` that tracks properties and issue duplicate property errors itself, despite the performance hit.

----

There are a few more *recommendations*, but not ones that need affect this crate.

I’m happy to implement this, but seek opinions before I do. From a little bit of looking, I suspect the best path might be to start with a fork of the crate (to minimise diffs, so that I can just bluntly edit what I need where I need), then see if there’s appetite to merge it back in, probably as a new module gated by a disabled-by-default Cargo feature. Here’s what I have in mind, from only fairly slight serde_json source code reading:

- Turn on UTF-8 validation in deserialize_bytes somehow (I don’t think anything similar is needed in serialisation—`serialize_bytes` can only emit a sequence of numbers, not a string). Also ensure noncharacters are forbidden, however that goes.
- Error on noncharacters in deserialize_str.
- Error on noncharacters in serialize_str.
- Provide new deserialise function/s for `Value`, `HashMap` and whatever else is applicable, which denies duplication. Could be done as one function that takes all such types generically (so that you can write `#[serde(deserialize_with = "serde_ijson::deserialize")]` regardless of the type), or as separate functions per type (`#[serde(deserialize_with = "serde_ijson::deserialize::Value")]`, *&c.*).
- Maybe provide new top-level helper functions for invoking the appropriate deserialisers?
- Duplicate `Serializer` and `Deserializer` and whatever else is necessary, to provide a strict I-JSON mode that tracks object property names and returns an error on duplicates, for a significant reduction in required mindfulness at a certain runtime overhead. (It’d be kinda nice if a linter could look at it all, but I don’t think that’ll be technically feasible for at least a few years.)

The path to merging this back into serde_json would essentially be that everything that has been modified gets moved into the new module, and changes are made as required to support code reuse.

It has just occurred to me just how fragile the `deserialize_with` path would be, because of how it can’t handle recursion. It believe can be sound for `Value`, and `HashMap<String, StructThatDerivesDeserialize>` would be fine, but `HashMap<String, Value>` or `HashMap<String, HashMap<…>>` would be broken. Y’know, I’m starting to lean towards just embracing eating the cost of property tracking for duplicate detection and having one slightly more expensive serialiser/deserialiser pair. The alternative is just too unsound and too fragile. Isolating it this much more and minimising its surface area is probably also good for merging it back into serde_json.

**Comment by dtolnay** [comment]
I would prefer not to accept any changes motivated only by I-JSON support into this crate. Someone can make a different crate dedicated to I-JSON support using Serde.
