### ISSUE TITLE
String literal with no structural elements retains quotes

### ISSUE THREAD

**Issue by maharg101** [serde-rs/json#872]
I have encountered some output from an API that returns a JSON response containing a bare string literal - for example, the body of the response might contain the following JSON document:

    "foo"

Note there are no structural elements present, and so it is not obvious how one might use a `Struct` to deserialise the document.

Using `json!` to deserialise this document results in a `Value` that is considered to be a string by `is_string()`

There is [some discussion](https://stackoverflow.com/q/13318420) about whether a bare string literal is considered a valid document, but as `json!` does parse the document into a string `Value`, would it be reasonable to assume that calling `.as_str().unwrap()` on it would result in `foo` and not `"foo"` ?

I have put together a [MCVE](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c318a23e8df6a6e823fcd7afb0e776b1)

It's easy enough to work around, but I thought it worth flagging this as it seems possibly inconsistent with the documentation and other issues e.g. #367

**Comment by dtolnay** [comment]
This is behaving correctly. `data` is a string containing quotes. So `v` is a string containing quotes.
