### ISSUE TITLE
Value and zeroize: How to securely use serde_json?

### ISSUE THREAD

**Issue by simmel** [serde-rs/json#874]
Sorry if this is not the right place to ask this.

I'm a beginner at Rust and I'm writing [something](https://github.com/simmel/bitwarden-backup) that uses `serde_json` and `valico` to validate that the inputed JSON is valid according to a JSON schema.

[The code](https://github.com/simmel/bitwarden-backup/blob/8d205e/src/main.rs#L48-L50) has the JSON as a string (`backup_json`) and deserializes it into a `serde_json::value::Value` (`backup_json_parsed`) which then `json_schema.validate` validates.

```rust
    let backup_json_parsed =
        serde_json::from_str(backup_json).expect("Bitwarden backup is not valid JSON");
    let valid = json_schema.validate(&backup_json_parsed).is_valid();
```

Since I want my program to be as secure as I possibly can make it I want to zero out the sensitive data in memory. `zeroize` (and `secrecy`) seems to be how to do this in Rust. If I was using serde to parse the JSON into a struct [it would be easy with `secrecy`](https://docs.rs/secrecy/latest/secrecy/#serde-support) but as I'm just using a `serde_json::value::Value` I have no idea. I've searched The Internet™ and Github for examples but I've found no one using `zeroize` to zero out a `serde_json::value::Value`.

Does anyone have any pointers on how to zero out the `serde_json::value::Value` object?

P.s. I know I'm not zeroing out the `backup_json` string yet, I haven't pushed that code = )

**Comment by dtolnay** [comment]
You would need to use a different crate designed for this. Even if you zero the stuff in `Value`, there would be internal state inside the json deserializer which you can't get to.
