### ISSUE TITLE
deserializing `NaN` values result in `expected value at line X column Y`

### ISSUE THREAD

**Issue by oronsh** [serde-rs/json#879]
Lets say I have this struct
```rust
#[derive(Deserialize)]
struct Floats {
 values: Vec<f64>,
}
```
and I have input from some api as 
```
{
 "values": [1, 2, NaN]
}
```
I'm getting this error `expected value at line X column Y`
From what I could see, the column number is that `NaN` and since it's not a String but just `NaN` I don't really know how to handle it. 
any suggestions?

Thanks a lot!

**Comment by jonasbb** [comment]
The unquoted `NaN` makes this invalid JSON. The `serde_json` crate does not attempt to parse invalid JSON. I think there are three ways you can address this problem.

1. Try to fix the API to return valid JSON.
2. Use a different JSON library. Other libraries might be more willing to add workarounds for invalid JSON, or maybe already support unquotes `NaN`s. There are also variants like HJSON or JSON5 which are more lenient in parsing.
3. You can pre-process the string before deserialization. if this is the only problem you face, something like `.replace("NaN", "\"NaN\"")` might already be enough. This simple replace will also alter other occurrences, for example in strings. Something more robust might be necessary.

**Comment by oronsh** [comment]
Thank you for the fast reply @jonasbb ! 
I was able to work around this issue by using `json5` instead of `serde_json`.
