### ISSUE TITLE
Inappropriate CAPPEDWORD conversion from PascalCase to snake_case

### ISSUE THREAD

**Issue by hillin** [serde-rs/json#881]
Json:
```json
{
    CSSColor: "#FFFFFF"
}
```

Rust:
```rust
#[derive(Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Data {
    // css_color: String,  // does not work, expects field "CssColor" in json
    c_s_s_color: String,   // works but ugly
}
```

**Comment by kangalio** [comment]
This is basically impossible to fix. How should the Deserialize macro know that "css" is an abbreviation, and "color" is a contiguous word? It would need a dictionary of known words, which is over-engineered. Additionally, in Rust, the `CssColor` casing would actually be considered correct:

> In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, Usize rather than USize or Stdin rather than StdIn

<https://rust-lang.github.io/api-guidelines/naming.html>

I'd advise you to write `#[serde(rename = "CSSColor")] css_color: String` here

**Comment by hillin** [comment]
How about: e.g. match `([A-Z]+)[^a-z]` and treat the first group as a word?

Test cases:
```
"ABC" -> "Abc"
"ABCd" -> "AbCd"
"ABC1" -> "Abc1"
```

**Comment by kangalio** [comment]
Serde converts from Rust field name to JSON field name internally and then parses; not the other way around. Are you saying that PascalCase should turn the first _ delimited word into all uppercase, and the others into normal uppercase? That would turn css_color into CSSColor, but it would also turn e.g. access_token into ACCESSToken

**Comment by hillin** [comment]
Sorry, I misread my own question (it's a little bit old that I don't even remember I asked it ;-)). I think you have the point, and `#[serde(rename` should work for my case.
