### ISSUE TITLE
Missing Github release entry for v1.0.80

### ISSUE THREAD

**Issue by gthb** [serde-rs/json#884]
The v1.0.80 release does not yet have an entry in https://github.com/serde-rs/json/releases, just a tag in https://github.com/serde-rs/json/tags.

This causes Dependabot PRs to be missing the release notes for v1.0.80, as they source release notes from Github releases:

![screenshot of a Dependabot PR lacking v1.0.80 release notes](https://user-images.githubusercontent.com/153580/166438576-8f85aa1c-0595-40ea-b2bb-3f1306ff934a.png)

**Comment by dtolnay** [comment]
Fixed!
