### ISSUE TITLE
Serialization always fails with "key must be a string"

### ISSUE THREAD

**Issue by br-olf** [serde-rs/json#887]
Hi, I don't know if this issue belongs here or to serde itself.

I try to serialize this object 
``` rust
use serde;
use serde_json;
use std::collections::BTreeMap;
use std::path::PathBuf;

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct DedupTree {
    hash_tree: BTreeMap<[u8; 32], Vec<PathBuf>>,
    file_tree: BTreeMap<PathBuf, [u8; 32]>,
}

impl DedupTree {
    pub fn to_json(&self) -> String {
        serde_json::to_string(&self).unwrap()
    }

    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }
}
```

but any time I want to use `to_json()` I get this error:
`Error("key must be a string", line: 0, column: 0)`

I tried a number of different approaches to fix this by implementing serialize for `[u8,32]` myself but eventually I always got the same error.
As far as I see from the [docs](https://docs.serde.rs/serde/ser/trait.Serialize.html) all used types (`BTreeMap`,`[u8; 32]`,`Vec`, `PathBuf`) are supported by serde.

**Comment by dtolnay** [comment]
I think this is behaving correctly. JSON maps only have string keys. Map keys are not allowed to be arrays in JSON.
