### ISSUE TITLE
Deserializing fails when numeric values are given as strings

### ISSUE THREAD

**Issue by mohs8421** [serde-rs/json#888]
I have this short test code here:
```
    #[derive(Debug, PartialEq, Deserialize)]
    struct TestType {
        a: u32,
    }

    #[test]
    fn test_deserialize_string_to_u32() {
        assert_eq!(
            TestType { a: 1 },
            serde_json::from_str("{\"a\": \"1\"}").unwrap()
        );
    }
```
It points out, that a value that could easily be parsed into the correct value fails miserably like this:
> called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"1\", expected u32", line: 1, column: 9)
> thread 'module::Tests::test_deserialize_string_to_u32' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"1\", expected u32", line: 1, column: 9)'

I would expect, that at least a `parse()` call would be attempted, or that it is documented how this behaviour can be achieved easily.

**Comment by dtolnay** [comment]
> I would expect, that at least a `parse()` call would be attempted

What is this expectation based on? Is it experience with a different JSON library (in a different language?) that behaves this way? Which one?

**Comment by mohs8421** [comment]
the expectation is based on the reality, that from weak typed contexts like javascript or php, numeric values might be given as strings into the serialization, which then would fail on the other end.
