### ISSUE TITLE
Cannot deserialize optional field with `deserialize_with` function

### ISSUE THREAD

**Issue by jdrouet** [serde-rs/json#893]
I'm trying to deserialize a `Option<String>` field with a `deserialize_with` function but it seems to not be working.
Do I miss something somewhere?

Here is the playground with the error to reproduce: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=601eaa8459dd7b1ed6d58af336c0c739
And here is the [gist](https://gist.github.com/rust-play/601eaa8459dd7b1ed6d58af336c0c739).

**Comment by jdrouet** [comment]
It just needed `#[serde(default)]`...

**Comment by alexvanolst** [comment]
Fixed version of the playground for anyone wondering where the `default` goes: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=117717dc4575bb8f025df12cf83731b6
