### ISSUE TITLE
Add option to serialize all non-ASCII characters in strings with `\uXXXX` escapes

### ISSUE THREAD

**Issue by jwodder** [serde-rs/json#907]
Sometimes, when producing JSON, you need to ensure that the output is all-ASCII.  The JSON format  makes this possible via the option of encoding all non-ASCII characters with `\uXXXX` escape sequences.  However, serde_json does not appear to have any mechanism for producing such output; it always serializes the string `"föö"` as `"föö"` rather than as `"f\u00f6\u00f6"`.

I hereby request for a mechanism to be added for serializing strings as all-ASCII.

**Comment by dtolnay** [comment]
You need to use your own `Formatter` for this.

I am closing the issue because I am not interested in building anything specific to this behavior into serde_json.

```rust
use serde::Serialize;
use std::io::{self, Write};

struct EscapeNonAscii;

impl serde_json::ser::Formatter for EscapeNonAscii {
    fn write_string_fragment<W: ?Sized + Write>(
        &mut self, 
        writer: &mut W, 
        fragment: &str
    ) -> io::Result<()> {
        for ch in fragment.chars() {
            if ch.is_ascii() {
                writer.write_all(ch.encode_utf8(&mut [0; 4]).as_bytes())?;
            } else {
                for escape in ch.encode_utf16(&mut [0; 2]) {
                    write!(writer, "\\u{:04x}", escape)?;
                }
            }
        }
        Ok(())
    }
}

fn main() {
    let value = "föö";
    let stdout = io::stdout();
    let formatter = EscapeNonAscii;
    let mut ser = serde_json::Serializer::with_formatter(stdout, formatter);
    value.serialize(&mut ser).unwrap();
}
```

**Comment by jwodder** [comment]
For anyone else who comes across this issue: I've packaged the above code (plus some extra functionality) into <https://crates.io/crates/serde-json-fmt>.
