### ISSUE TITLE
Parsing a json file fails ONLY on armv7

### ISSUE THREAD

**Issue by jdrouet** [serde-rs/json#914]
Hi!
I've been building a lib using `serde_json` and tried to use it on `armv7` and `amd64` and It's been failing only on `armv7` with the same payload.
You can try to reproduce it [here](https://github.com/jdrouet/serde-json-armv7), I put all the code and the way to reproduce it.
Is there a limitation given by `armv7`?

**Comment by dtolnay** [comment]
This crate does not contain any platform-specific or architecture-specific code so I am skeptical that this would be a serde_json issue. It will need to be minized further and reported as a compiler or LLVM bug.
