### ISSUE TITLE
Value is not Sync

### ISSUE THREAD

**Issue by victorteokw** [serde-rs/json#916]
Hi, Thanks for this fancy and great library.

I'm passing reference of Value around, the compiler complains that it's not Sync thus this function is not send. How to solve this?

Thanks

**Comment by dtolnay** [comment]
Pretty sure it is Sync: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc1658e9a2993def2c5bb283e153cd4d.
