### ISSUE TITLE
Support no_std +alloc -float

### ISSUE THREAD

**Issue by kvinwang** [serde-rs/json#926]
We are trying to do some JSON (de)serialization in the [ink!](https://paritytech.github.io/ink/)(a smart contract lang compiled to `WASM`) environment.

**There are some limitations of `ink!`**:
- no_std
- forbid float types and instructions to be deterministic. (statically checked before execution)

**And JSON features we want to use**:
- support `alloc::*` types
- no float types and instructions in the compiled output if we don't use it to ser/de float types.

**Current situation**:
`serde_json`: it always outputs float types/instructions in the WASM even if there isn't any floating point type in the Rust types.
`serde_json_core`: No unexpected floating point output but `alloc::*` types are not supported.

Could either `serde_json` or `serde_json_core` meet the requirements?

**Comment by dtolnay** [comment]
I would prefer not to handle this in this crate, but the code is appropriately licensed so that someone could take most of it and make a crate that meets this use case.
