### ISSUE TITLE
Bump indexmap

### ISSUE THREAD

**Issue by st3iny** [serde-rs/json#935]
First of all, thanks for maintaining this awesome library!

I'm using it in a project next to `serde_yaml` with `preserve_order` enabled. That feature pulls in the optional dependency `indexmap` and it conflicts with the version used in `serde_yaml`.

Therefore, I propose to bump the `indexmap` dependency as the current version was released about 2 years ago.

I'd be happy to open a PR if you agree.

**Comment by dtolnay** [comment]
This crate already depends on the most recent version of indexmap.

**Comment by st3iny** [comment]
Yeah, you're right. I was just confused by this line https://github.com/serde-rs/json/blob/94019a31c6036dc4ebb9afc44a214f950caf0d1f/Cargo.toml#L16

It was a problem in my lockfile.
