### ISSUE TITLE
Support for pretty-printing with lexicographically sorted map keys

### ISSUE THREAD

**Issue by cstrahan-blueshift** [serde-rs/json#945]
Is there support (either in `serde_json` or a supporting crate) for pretty printing `Value`s with map keys sorted lexicographically (or similar)?

Something along those lines would be helpful for [expect-style tests](https://docs.rs/expect-test/latest/expect_test/), something like:

```rust
use expect_test::expect;

let some_value: Value = get_some_value();
let actual = serde_json::to_string_pretty(some_value);
let expected = expect![["
    {
        "a" => [],
        "contrived" => [],
        "example" => [],
		"here" => []
    }
"]];
expected.assert_eq(&actual);
```

Unfortunately, for my use case it would not be feasible to enable the `preserve_order` feature to get what I want, and I need to work with `Value` directly.

I tried search terms along the lines of "serde_json value pretty print expect test keys sort", figuring it's likely that this is a solved problem, but have had no luck. My apologies if I just overlooked what I'm looking for, and thanks for `serde_json` :slightly_smiling_face: .

**Comment by dtolnay** [comment]
Yeah, as long as you don't enable `preserve_order` then `Value` will always print with map keys sorted lexicographically.

**Comment by cstrahan-blueshift** [comment]
Ah, I missed that logic while glancing through the code. Thanks for the feedback!
