### ISSUE TITLE
Wrong error when parsing struct-like enum variant from empty list

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#96]
[This unit test](https://github.com/serde-rs/json/blob/12f617d966e2169bfe90bb26397bc1ea7c124501/json_tests/tests/test_json.rs#L1014) caught my eye and does not make sense to me.

```rust
("{\"Cat\":[]}", Error::Syntax(ErrorCode::EOFWhileParsingValue, 1, 9)),
```

The `Animal::Cat` variant looks like `Cat { age: usize, name: String }`. Not clear where the EOF is coming from but it is not right.

**Comment by oli-obk** [comment]
we should probably start adding `trace!` logs to json. In xml they have helped greatly at figuring out this kind of error.

**Comment by dtolnay** [comment]
The error comes from [here](https://github.com/serde-rs/serde/blob/c0e8164792e8e2d5fbd3a589f5c2ecba3b50cf49/serde_codegen/src/de.rs#L427). It is not the right error to return there.
