### ISSUE TITLE
Serialize into strange format: serialize inner struct's name 

### ISSUE THREAD

**Issue by ibotty** [serde-rs/json#960]
I don't know how to phrase the question better.  Sorry.

I have to generate the following `json`.
```
[
  "commandName",
  {
    "parameter1": "value1",
    "parameter2": "value2"
   },
   "tag1"
]
```

The set of parameters depends on the command.

I defined the types

```rust
#![derive(Serialize)]
struct CommandName {
   parameter1: String,
   parameter2: String,
}
struct<a', T> Request {
  tag: &'a str,
  command: T
}
```

and tried to serialize using the following code.

```rust
impl<'a, T> Serialize for Request<'a, T>
where
    T: Serialize
{
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer
    {
        let mut tup = serializer.serialize_tuple(3)?;
        tup.serialize_element("commandName")?;
        tup.serialize_element(&self.req)?;
        tup.serialize_element(self.tag)?;
        tup.end()
    }
}
```

The Problem is that I cannot get `commandName`  from `self.req`.

I might be able not to use a `struct CommandName`, but an `enum` encompassing all possible commands, but that will make it harder in other parts of the code.

Any idea?  I would prefer not having to use proc macros.

**Comment by dtolnay** [comment]
Please take this question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.
