### ISSUE TITLE
The `json!` macro uses an impossible amount of memory when refering raw strings

### ISSUE THREAD

**Issue by CompeyDev** [serde-rs/json#962]
I'm currently working on a foreign function interface-based project, which involves constructing a `Value` from a JSON literal. Using `String::from_raw_parts`, I am constructing a string from a `c_char` pointer and a `size_t`. Below is code that can reproduce the unexpected situation.

```rs
use libc::{c_char, size_t};
use serde_json;
use std::ffi::{CString, CStr};

pub extern "C" fn construct_json(raw_c_string: *const c_char, raw_c_string_size: size_t) {
  let c_string = unsafe { String::from_raw_parts(raw_c_string as *mut u8, raw_c_string_size, raw_c_string_size) };

  let constructed_json = serde_json::json!({
    "constructed_string": c_string
  });

  println!("{:#?}", constructed_json);
}

fn main() {
    construct_json(CString::new("data").expect("CString::new failed").as_ptr(), 5)
}
```
The code **is** valid, it runs as expected on the [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b4bd989d2765453faf81424c9b8a4769) with a regular binary.

Note that this works with regular builds, but if the crate-type were `cdylib`or `dylib`, the following error would be emitted when calling the compiled shared library:
```
memory allocation of 140655883976708 bytes failed
```
Which is **HUGE**, around 140 TB. What could be causing this behavior?

**Comment by dtolnay** [comment]
The unsafe code you wrote is UB; it doesn't have anything to do with serde_json or the JSON macro.

**Comment by CompeyDev** [comment]
> The unsafe code you wrote is UB; it doesn't have anything to do with serde_json or the json macro.

Correct, but serde_json tries to allocate 140 TBs of memory when building a cdylib. Why?
