### ISSUE TITLE
 Allow deserialization of enum from integer types #349 

### ISSUE THREAD

**Issue by linonetwo** [serde-rs/json#970]
Same as #349

May need something like

```rust
#[derive(Type, Serialize, Deserialize, PartialEq, Eq, Debug, Clone, Copy, JsonSchema)]
#[serde(untagged)]
pub enum WorkspaceType {
    #[serde(with = "i8")]
    Private = 0,
    #[serde(with = "i8")]
    Normal = 1,
}
```

And `Deserialize_repr` is not compatible to `Deserialize`, not accepted by community crates that only accepts `Deserialize` so is not working in these cases.

**Comment by dtolnay** [comment]
The `with` attribute in the code you pasted is being used incorrectly, but other than that this is handled by the `serde_repr` crate.

**Comment by linonetwo** [comment]
@dtolnay but `Deserialize_repr` is not compatible to `Deserialize`, that is why I opened this issue, which is not resolved.

**Comment by dtolnay** [comment]
I don't understand what you mean, but you can try taking this to any of the resources shown in https://www.rust-lang.org/community and they should be able to help get whatever you need working. When asking though, do keep in mind that "I tried some unspecified code and it didn't work in some unspecified way" won't be actionable for anyone to help you.
