### ISSUE TITLE
serde_json::Error does not implement clone

### ISSUE THREAD

**Issue by rdelfin** [serde-rs/json#972]
Is there a particular reason why the `Error` type in this crate does not implement the `Clone` trait? I'm working on a problem where I basically send a `Result` type over a `tokio::sync::broadcast` channel, but unfortunately I can't make use of this since the Error type has a nexted JSON error without encapsulating the error in an Rc/Arc or some other similar container type. Thanks!

**Comment by dtolnay** [comment]
It's not usual for error types in Rust libraries to implement `Clone`.

Please use `Arc<serde_json::Error>` if both sides of the channel need ownership of the same JSON error.
