### ISSUE TITLE
Any way to support nested errors?

### ISSUE THREAD

**Issue by msdrigg** [serde-rs/json#975]
I have a use case where I deserialize a large depth-3 nested struct. `serde-json` handles the parsing perfectly, but when there are errors in this struct, the error can be very not descriptive:

> Error("expected value", line: 1, column: 3969))

I would like to see some kind of tree describing what should have been parsed and where it went wrong. Something like this:

```
Error::FieldError {
    field: "widgets",
    line: 1,
    column: 20,
    error: Error::FieldError {
        field: "color", 
        line: 1,
        column: 30
        error: Error::MissingError("expected value", line: 1, column: 3969)
    }
}
```

This may be out-of-scope for `serde-json`, but if so, is this possible to implement with the `serde` error model?

**Comment by jonasbb** [comment]
There is [`serde_path_to_error`](https://docs.rs/serde_path_to_error/latest/serde_path_to_error/) which provides at least some location information.

**Comment by msdrigg** [comment]
Perfect, thanks!
