### ISSUE TITLE
Add support for streaming data into a Deserializer.

### ISSUE THREAD

**Issue by dankcatlord** [serde-rs/json#983]
I have a library which uses a callback whenever it needs to write data. While I could read this data into a `Vec`, it can get very large and I am only using some select values from this data. I would like to stream this data into a `Deserializer` instead of storing it entirely in memory.

A possible implementation could be as follows:
```rust
impl<'de, R> Deserializer<R>
where
    R: Read<'de>,
{
    ...
    fn write_data(data: &[u8]) -> Result<usize>;
    fn end_data() -> Result<()>;
}
```

**Comment by dtolnay** [comment]
I am skeptical that this would be a good fit for this library, but it would be interesting for someone to pursue in a different library.
