### ISSUE TITLE
Consistent behavior when Serializing and Deserializing of f32::NaN, Infintiy and NegInfinity

### ISSUE THREAD

**Issue by TotalKrill** [serde-rs/json#985]
Hello, 

Looking through the quite large list of issues related to serialization and deserialization of floats NaN and Infinity types. I believe that the correct solution to this would be to at least return an error in serialization when running into this, as well as when deserializing. 

in #842 I agree with the statement that the more text you add to documentation the less people read, so people would run into this anyway. But I do not enjoy the inconsistency in throwing an error in deserializing, when it was valid to serialize. Since IEEE754 does not handle NaN and Infinite  it think its reasonable. 

I think that would be the best solution and I could implement it,  if @dtolnay agrees.

**Comment by Dirreke** [comment]
I agree it. It really confuse me when I serialize it succesfully but deserialize with an error at first.

**Comment by dtolnay** [comment]
I agree that erroring during serialization on infinity and NaN would be better behavior. I think it's not worth changing now though.
