### ISSUE TITLE
how to serialize bytearrays as hexadecimal strings?

### ISSUE THREAD

**Issue by mimoo** [serde-rs/json#996]
Heyo,

When I serialize my structs with serde_json I get ugly arrays of bytes instead of an hex string. I'm trying to figure out how I could continue serializing normally when using a binary serializer, and convert my bytearrays to hexadecimal strings when I use non-binary serializer like JSON.

My intuition would be that in my custom serialization function I could check if my `serializer: serde::Serializer` is textual or binary by calling a function or something, but I can't find one. I'm wondering if there's a way now : o

**Comment by mimoo** [comment]
reading more into it, it seems like serde_json itself should implement `serialize_bytes` differently no?

**Comment by jonasbb** [comment]
> My intuition would be that in my custom serialization function I could check if my `serializer: serde::Serializer` is textual or binary by calling a function or something, but I can't find one. I'm wondering if there's a way now : o

The function you are looking for is called [`is_human_readable`](https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable) and exists for the `Serializer` and `Deserializer`.

**Comment by mimoo** [comment]
oh thank-you so much! This is great. Here's what my code looks like (targeting the arkworks library) for people who are trying to solve the same issue:

```rust
pub struct SerdeAs;

impl<T> serde_with::SerializeAs<T> for SerdeAs
where
    T: CanonicalSerialize,
{
    fn serialize_as<S>(val: &T, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let mut bytes = vec![];
        val.serialize(&mut bytes)
            .map_err(serde::ser::Error::custom)?;

        Bytes::serialize_as(&bytes, serializer)
    }
}

impl<'de, T> serde_with::DeserializeAs<'de, T> for SerdeAs
where
    T: CanonicalDeserialize,
{
    fn deserialize_as<D>(deserializer: D) -> Result<T, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let bytes: Vec<u8> = Bytes::deserialize_as(deserializer)?;
        T::deserialize(&mut &bytes[..]).map_err(serde::de::Error::custom)
    }
}
```
