### ISSUE TITLE
Optional items `json!` Object and Array

### ISSUE THREAD

**Issue by rben01** [serde-rs/json#998]
Is something like the following — optionally including entire items in the `json!` macro — possible, or if not, would it be possible to add it to `serde_json`?

```rust
let include_a = true;
let include_z = false;
let value = json!({
    if include_a {
        "a": 1
    },
    "array": [
        "x",
        "y",
        if include_z {
            "z"
        }
})
```
Which would produce the `Value` equivalent to `{ "a: 1, "array": ["x", "y"] }` (but would be dynamic based on the values of `include_a` and `include_z`).

**Comment by rben01** [comment]
In terms of syntax/parsing this seems like a minefield, so maybe such expressions would have to be wrapped in parentheses (which can't appear in JSON) in order to enter “Rust mode” in `json!`.

**Comment by dtolnay** [comment]
I prefer not to support this. Please write:

```rust
if include_a {
    value["a"] = json!(1);
}
```
