### ISSUE TITLE
[Feature Request] serde_json::value::Serializer adds support for non human readable serialization

### ISSUE THREAD

**Issue by JackLiar** [serde-rs/json#999]
I know this sounds quite ridiculous for json format, but I will demonstrate the use case below.

serde_json is probably the most convenient serde crate I've ever used, and I do take json as my standard output format, for now.

My struct looks like this:
```rust
use serde_json::{Serialize, Value};

#[derive(Clone, Debug, Default, Serialize)]
struct Data {
    id: String,
    #[serde(flatten)]
    fields: Value,
}

impl Data {
    fn add_field<V: Serialize>(&mut self, k: String, v: V) {
        self.fields
            .as_object_mut()
            .unwrap()
            .insert(k, json!(value));
    }
}
```

I could easily add any data into this struct, and serialize it to json, perfect!

Now, I wanna serialize this struct to msgpack format, as we all know it is a binary data format, and is not human readable.

Using msgpack is primarily for io performance concern. However using `json!()` means all the values added into fields must be serialized to `serde_json::Value` using [`serde_json::value::Serializer`](https://docs.rs/serde_json/latest/serde_json/value/struct.Serializer.html) , which is a human readable serializer, the method described in [Serializer::is_human_readable](https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable) will not work anymore...

Full code:
```rust
use base64::prelude::{Engine, BASE64_STANDARD};
use bytes::Bytes;
use serde::{Serialize, Serializer};
use serde_json::{json, Value};

#[derive(Clone, Debug)]
pub struct BinaryData(Bytes);

impl Serialize for BinaryData {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        if serializer.is_human_readable() {
            // Serialize to a human-readable base64 string.
            serializer.serialize_str(&BASE64_STANDARD.encode(&self.0))
        } else {
            // Serialize to a compact binary representation.
            self.0.serialize(serializer)
        }
    }
}

#[derive(Clone, Debug, Default, Serialize)]
struct Data {
    id: String,
    #[serde(flatten)]
    fields: Value,
}

impl Data {
    fn add_field<V: Serialize>(&mut self, k: &str, v: V) {
        self.fields
            .as_object_mut()
            .unwrap()
            .insert(k.to_string(), json!(v));
    }
}

fn main() {
    let mut data = Data {
        id: "id".to_string(),
        fields: json!({}),
    };

    let bd = BinaryData(Bytes::copy_from_slice(&[1, 2, 3, 4, 5]));
    data.add_field("binary", bd);
    println!("json: {}", serde_json::to_string_pretty(&data).unwrap());

    println!(
        "msgpack: {}",
        String::from_utf8_lossy(&rmp_serde::to_vec_named(&data).unwrap())
    );
}
```

And output is:
```shell
$ cargo r
json: {
  "id": "id",
  "binary": "AQIDBAU="
}
msgpack: ��id�id�binary�AQIDBAU=
```

As we can see, what I wanted is when serialized to msgpack format, BinaryData should be a byte array, but it is a base64 string.

If [serde_json::value::Serializer](https://docs.rs/serde_json/latest/serde_json/value/struct.Serializer.html) have a flag is_human_readable to control the behavior, that would be a lot help.

**Comment by dtolnay** [comment]
I would prefer not to build anything for this into this crate. But you can always wrap serde_json::value::Serializer in your own Serializer impl that implements is_human_readable differently.
